/* Codex v2.4 — playable Early Egypt campaign */
V22_CAMPAIGN_CODES.EGYPT_EARLY='EGYPT';
activeCampaignCode=function(){return V22_CAMPAIGN_CODES[activeCampaignId()]||activeCampaignId();};
function activeCampaignNoun(){return activeCampaignId()==='EGYPT_EARLY'?'ЕГИПЕТ':activeCampaignId()==='MESOPOTAMIA_DAWN'?'МЕСОПОТАМИЯ':'РИМ';}
activeCampaignPackTitle=function(){return activeCampaignId()==='EGYPT_EARLY'?'Египетский архивный пак':activeCampaignId()==='MESOPOTAMIA_DAWN'?'Месопотамский архивный пак':'Римский архивный пак';};
activeCampaignPackCover=function(){return activeCampaignId()==='EGYPT_EARLY'?'assets/packs/egypt-pack.svg':activeCampaignId()==='MESOPOTAMIA_DAWN'?'assets/packs/mesopotamia-pack.svg':'assets/packs/rome-pack.svg';};
const V24_sync=syncActiveCampaignRuntime;
syncActiveCampaignRuntime=function(){V24_sync();if(activeCampaignId()==='EGYPT_EARLY'){const first=CAMPAIGN.nodes[0];(first?.cards||[]).forEach(id=>{if(!state.unlocked.includes(id))state.unlocked.push(id);});}};
const V24_campaign=campaign;
campaign=function(){syncActiveCampaignRuntime();let html=V24_campaign();if(activeCampaignId()==='EGYPT_EARLY')html=html.replace(/МЕСОПОТАМСКАЯ КАМПАНИЯ|РИМСКАЯ КАМПАНИЯ/g,'ЕГИПЕТСКАЯ КАМПАНИЯ');return html;};
packsScreen=function(){
 const pools=unlockedPools(),available=packPool().filter(c=>!isUnlocked(c.id)).length,history=state.packHistory.slice(-6).reverse();
 return shell(`<section class="packs-page-head reveal"><div class="packs-title-block"><div class="eyebrow">Архив · ${activeCampaignLabel()}</div><h2>Паки знаний</h2><div class="fragment-balance compact-fragment-balance"><span>◇</span><b>${state.fragments}</b><small>фрагментов</small></div></div></section><section class="packs-page-grid reveal"><article class="pack-page-card ${dailyPackReady()?'ready':''}"><img src="${packCover('DAILY')}" alt="Архивный пак дня"><div class="pack-page-copy"><small>ЕЖЕДНЕВНЫЙ · 3 КАРТЫ</small><h3>Архивный пак дня</h3><p>${dailyPackReady()?'Награда за учебную сессию готова.':dailyLearningCompleteToday()?'Сегодняшний пак уже открыт.':'Заверши короткую дневную сессию.'}</p>${packAction('DAILY')}</div></article><article class="pack-page-card campaign-pack"><img src="${activeCampaignPackCover()}" alt="${activeCampaignPackTitle()}"><div class="pack-page-copy"><small>${activeCampaignNoun()} · 4 КАРТЫ</small><h3>${activeCampaignPackTitle()}</h3><p>${available} новых карточек в ${pools.length} открытых пулах.</p><div class="pack-page-meta"><span>60 ◇</span><span>${pools.length} пулов</span></div>${packAction('ROMAN')}</div></article></section>${history.length?`<section class="section compact-card-section reveal"><div class="section-head"><h2>Последние открытия</h2><span>${history.length}</span></div><div class="pack-history-list">${history.map(h=>`<article><span>${h.kind==='DAILY'?'☀':activeCampaignId()==='EGYPT_EARLY'?'𓂀':activeCampaignId()==='MESOPOTAMIA_DAWN'?'𒀭':'SPQR'}</span><div><b>${h.kind==='DAILY'?'Архивный пак дня':'Коллекционный пак'}</b><small>${new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(h.date))}</small></div><em>${h.drops.filter(d=>d.fresh).length} новых</em></article>`).join('')}</div></section>`:''}`);
};
home=function(){
 syncActiveCampaignRuntime();const m=currentMission(),chapter=CAMPAIGN.chapters.find(ch=>ch.id===state.campaignChapter)||CAMPAIGN.chapters[0],code=activeCampaignCode();
 const icon=code==='EGYPT'?'𓂀':code==='MESOPOTAMIA'?'𒀭':'SPQR';
 return shell(`<section class="home-hero home-hero-clean reveal"><div class="hero-layout"><div class="hero-content"><div class="eyebrow">${activeCampaignLabel()} · ${chapter?.title||''}</div><h2>${m.title}</h2><div class="hero-actions"><button class="btn" onclick="openMission('${m.id}')">${m.emoji} Продолжить</button><button class="btn secondary" onclick="go('collection')">▦ Коллекция</button></div></div><div class="hero-orbit"><div class="orbit-core"><div class="core-value"><strong>${campaignProgress()}%</strong><span>пройдено</span></div></div><div class="orbit-chip one">Миссии<b>${completedMissionCount()}/${CAMPAIGN.nodes.length}</b></div><div class="orbit-chip two">Карточки<b>${state.unlocked.filter(id=>card(id)?.campaign===code).length}</b></div><div class="orbit-chip three">Фрагменты<b>${state.fragments} ◇</b></div></div></div></section><section class="home-stats reveal"><div class="stat-box"><div class="stat-icon">${icon}</div><b>${campaignProgress()}%</b><span>кампания</span></div><div class="stat-box"><div class="stat-icon">▤</div><b>${completedMissionCount()}/${CAMPAIGN.nodes.length}</b><span>миссий</span></div><div class="stat-box"><div class="stat-icon">▦</div><b>${state.unlocked.filter(id=>card(id)?.campaign===code).length}</b><span>карточек</span></div><div class="stat-box stat-action" onclick="openPackHub()"><div class="stat-icon">✦</div><b>${dailyPackStatusShort()}</b><span>пак дня</span></div></section><section class="daily-home-card reveal" onclick="openDaily()"><div class="daily-home-icon">◷</div><div><div class="eyebrow">Ежедневное обучение</div><h3>${dailyLearningCompleteToday()?'Сессия выполнена':`К повторению: ${dailyDueCards().length}`}</h3></div><button class="btn ${dailyLearningCompleteToday()?'secondary':''}">${dailyLearningCompleteToday()?'Открыть':'Начать'}</button></section>`);
};
const V24_render=render;render=function(){syncActiveCampaignRuntime();V24_render();};
