/* Codex v2.8.0 — Indus civilization campaign */
(()=>{
 const V='7.8.0'; window.CODEX_VERSION=V; V22_CAMPAIGN_CODES.INDUS='INDUS';
 const oldNoun=activeCampaignNoun; activeCampaignNoun=function(){return activeCampaignId()==='INDUS'?'ИНДСКАЯ ЦИВИЛИЗАЦИЯ':oldNoun();};
 const oldTitle=activeCampaignPackTitle; activeCampaignPackTitle=function(){return activeCampaignId()==='INDUS'?'Индский архивный пак':oldTitle();};
 const oldCover=activeCampaignPackCover; activeCampaignPackCover=function(){return activeCampaignId()==='INDUS'?'assets/packs/indus-pack.svg':oldCover();};
 const oldSync=syncActiveCampaignRuntime; syncActiveCampaignRuntime=function(){oldSync();if(activeCampaignId()==='INDUS'){const first=CAMPAIGN.nodes[0];(first?.cards||[]).forEach(id=>{if(!state.unlocked.includes(id))state.unlocked.push(id);});}};

 const oldPacks=packsScreen; packsScreen=function(){
   if(activeCampaignId()!=='INDUS')return oldPacks();
   const pools=unlockedPools(),available=packPool().filter(c=>!isUnlocked(c.id)).length,history=state.packHistory.slice(-6).reverse();
   return shell(`<section class="packs-page-head reveal"><div class="packs-title-block"><div class="eyebrow">Архив · Индская цивилизация</div><h2>Паки знаний</h2><div class="fragment-balance compact-fragment-balance"><span>◇</span><b>${state.fragments}</b><small>фрагментов</small></div></div></section><section class="packs-page-grid reveal"><article class="pack-page-card ${dailyPackReady()?'ready':''}"><img src="${packCover('DAILY')}" alt="Архивный пак дня"><div class="pack-page-copy"><small>ЕЖЕДНЕВНЫЙ · 3 КАРТЫ</small><h3>Архивный пак дня</h3>${packAction('DAILY')}</div></article><article class="pack-page-card campaign-pack ${campaignPackStatusClass()}"><img src="assets/packs/indus-pack.svg" alt="Индский архивный пак"><div class="pack-page-copy"><small>ИНДСКАЯ ЦИВИЛИЗАЦИЯ · 4 КАРТЫ</small><h3>Индский архивный пак</h3><p>${campaignPackDescription()}</p><div class="pack-page-meta">${campaignPackMeta()}</div>${campaignPackAction()}</div></article></section>${history.length?`<section class="section compact-card-section reveal"><div class="section-head"><h2>Последние открытия</h2><span>${history.length}</span></div><div class="pack-history-list">${history.map(h=>`<article><span>${h.kind==='DAILY'?'☀':'◇'}</span><div><b>${h.kind==='DAILY'?'Архивный пак дня':'Индский архивный пак'}</b><small>${new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(h.date))}</small></div><em>${h.drops.filter(d=>d.fresh).length} новых</em></article>`).join('')}</div></section>`:''}`);
 };

 const oldCampaign=campaign; campaign=function(){let html=oldCampaign();if(activeCampaignId()==='INDUS')html=html.replace(/РИМСКАЯ КАМПАНИЯ|МЕСОПОТАМСКАЯ КАМПАНИЯ|ЕГИПЕТСКАЯ КАМПАНИЯ|СРАВНИТЕЛЬНАЯ КАМПАНИЯ/g,'ИНДСКАЯ КАМПАНИЯ');return html;};
 const oldHome=home; home=function(){syncActiveCampaignRuntime();if(activeCampaignId()!=='INDUS')return oldHome();const m=currentMission(),chapter=CAMPAIGN.chapters.find(ch=>ch.id===state.campaignChapter)||CAMPAIGN.chapters[0];return shell(`<section class="home-hero home-hero-clean indus-home reveal"><div class="hero-layout"><div class="hero-content"><div class="eyebrow">Рождение цивилизаций · ${chapter.title}</div><h2>${m.title}</h2><div class="hero-actions"><button class="btn" onclick="openMission('${m.id}')">${m.emoji} Продолжить</button><button class="btn secondary" onclick="go('world')">◎ Сменить кампанию</button></div></div><div class="indus-home-symbol"><span>𒆠</span><i></i><span>◇</span></div></div></section><section class="home-stats reveal"><div class="stat-box"><div class="stat-icon">≋</div><b>${campaignProgress()}%</b><span>кампания</span></div><div class="stat-box"><div class="stat-icon">▤</div><b>${completedMissionCount()}/${CAMPAIGN.nodes.length}</b><span>уроков</span></div><div class="stat-box"><div class="stat-icon">▦</div><b>${state.unlocked.filter(id=>card(id)?.campaign==='INDUS').length}</b><span>карточек</span></div><div class="stat-box stat-action" onclick="openPackHub()"><div class="stat-icon">✦</div><b>${dailyPackStatusShort()}</b><span>пак дня</span></div></section><section class="daily-home-card reveal" onclick="openDaily()"><div class="daily-home-icon">◷</div><div><div class="eyebrow">Ежедневное обучение</div><h3>${dailyLearningCompleteToday()?'Сессия выполнена':`К повторению: ${dailyDueCards().length}`}</h3></div><button class="btn ${dailyLearningCompleteToday()?'secondary':''}">${dailyLearningCompleteToday()?'Открыть':'Начать'}</button></section>`);};
})();
