const CARDS = [
  {id:'PER_ROM_001', type:'PERSON', title:'Romulus', subtitle:'Legendary founder of Rome', era:'Early Rome', region:'Latium', date:'traditional 8th century BCE', rarity:'RARE', difficulty:2, summary:'Romulus is the legendary founder and first king of Rome in Roman tradition.', importance:'The story of Romulus shaped Roman identity, kingship myths and later ideas about Rome\'s destiny.', facts:['Roman tradition dated the foundation of Rome to 753 BCE.','Romulus and Remus were central figures in Rome\'s foundation myth.','The story belongs to mythic tradition, not secure documentary history.'], tags:['Rome','Myth','Foundation'], stats:{Influence:7,Complexity:3,Legacy:8,Military:3,Culture:9,Politics:5,Religion:5,Economy:1,Connections:7}, loc:{label:'Rome',x:55,y:49}},
  {id:'EVT_ROM_001', type:'EVENT', title:'Founding of Rome', subtitle:'Traditional beginning of the city', era:'Early Rome', region:'Latium', date:'traditionally 753 BCE', rarity:'EPIC', difficulty:2, summary:'The founding of Rome is traditionally placed in 753 BCE and tied to the Romulus and Remus legend.', importance:'It gives Rome a symbolic origin story and anchors later Roman memory.', facts:['753 BCE is the traditional date, not a secure archaeological event date.','The foundation myth connected Rome with divine ancestry and heroic violence.','Later Romans treated the foundation story as part of civic identity.'], tags:['Rome','Myth','Foundation'], stats:{Influence:8,Complexity:3,Legacy:9,Military:1,Culture:10,Politics:5,Religion:6,Economy:2,Connections:8}, loc:{label:'Rome',x:55,y:49}},
  {id:'STATE_ROM_001', type:'STATE', title:'Roman Kingdom', subtitle:'Rome before the Republic', era:'Early Rome', region:'Latium', date:'traditionally 753–509 BCE', rarity:'RARE', difficulty:3, summary:'The Roman Kingdom is the traditional monarchic phase of early Rome before the Republic.', importance:'It explains the later Roman hatred of kingship and the political memory behind the Republic.', facts:['The period is partly legendary and difficult to verify in detail.','Roman tradition lists seven kings before the Republic.','The expulsion of the last king became a core Republican memory.'], tags:['Rome','Monarchy','Early Rome'], stats:{Influence:6,Complexity:5,Legacy:7,Military:4,Culture:6,Politics:8,Religion:5,Economy:3,Connections:7}, loc:{label:'Rome',x:55,y:49}},
  {id:'EVT_ROM_002', type:'EVENT', title:'Expulsion of the Kings', subtitle:'Traditional birth of the Roman Republic', era:'Early Republic', region:'Latium', date:'traditionally 509 BCE', rarity:'EPIC', difficulty:3, summary:'Roman tradition says the monarchy ended after the expulsion of Tarquinius Superbus.', importance:'This event became the foundation story of Roman Republican politics.', facts:['509 BCE is the traditional date for the beginning of the Republic.','Roman memory linked kingship with tyranny.','The Republic replaced monarchy with annually elected magistrates.'], tags:['Rome','Republic','Politics'], stats:{Influence:9,Complexity:4,Legacy:9,Military:2,Culture:6,Politics:10,Religion:3,Economy:3,Connections:9}, loc:{label:'Rome',x:55,y:49}},
  {id:'STATE_ROM_002', type:'STATE', title:'Roman Republic', subtitle:'Rome\'s republican political system', era:'Roman Republic', region:'Mediterranean', date:'509–27 BCE', rarity:'LEGENDARY', difficulty:5, summary:'The Roman Republic was a political system built around magistrates, assemblies, elite competition and the Senate.', importance:'It created the military and political machine that conquered the Mediterranean, then collapsed into civil war.', facts:['The Republic was not a modern democracy.','The Senate held enormous influence, especially among the elite.','Military expansion and social conflict helped destabilize the system.'], tags:['Rome','Republic','Politics'], stats:{Influence:10,Complexity:8,Legacy:10,Military:9,Culture:8,Politics:10,Religion:4,Economy:8,Connections:10}, loc:{label:'Rome',x:55,y:49}},
  {id:'ORG_ROM_001', type:'FACTION', title:'Roman Senate', subtitle:'Elite council at the heart of Roman politics', era:'Roman Republic / Empire', region:'Rome', date:'ancient Rome', rarity:'EPIC', difficulty:5, summary:'The Roman Senate was a central political body dominated by Rome\'s elite families.', importance:'Understanding the Senate is necessary for understanding the Republic, Caesar and the birth of imperial rule.', facts:['The Senate was highly influential but changed across Roman history.','Senators came from Rome\'s political elite.','Conflict between commanders and senatorial authority was central to the late Republic.'], tags:['Rome','Senate','Politics'], stats:{Influence:10,Complexity:7,Legacy:9,Military:4,Culture:6,Politics:10,Religion:4,Economy:7,Connections:10}, loc:{label:'Rome',x:55,y:49}},
  {id:'PER_CAR_001', type:'PERSON', title:'Hannibal Barca', subtitle:'Carthaginian commander and Rome\'s great enemy', era:'Punic Wars', region:'Carthage', date:'c. 247–183 BCE', rarity:'LEGENDARY', difficulty:4, summary:'Hannibal Barca was the Carthaginian general who brought the Second Punic War into Italy.', importance:'His campaign forced Rome into one of its greatest military crises.', facts:['Hannibal crossed the Alps with an army during the Second Punic War.','He won a major victory at Cannae in 216 BCE.','He was defeated by Scipio Africanus at Zama in 202 BCE.'], tags:['Carthage','Rome','Punic Wars'], stats:{Influence:9,Complexity:5,Legacy:10,Military:10,Culture:7,Politics:6,Religion:1,Economy:4,Connections:9}, loc:{label:'Carthage',x:48,y:67}},
  {id:'WAR_ROM_001', type:'EVENT', title:'Second Punic War', subtitle:'Rome and Carthage fight for Mediterranean power', era:'Roman Republic', region:'Western Mediterranean', date:'218–201 BCE', rarity:'LEGENDARY', difficulty:5, summary:'The Second Punic War was the great conflict between Rome and Carthage led by figures like Hannibal and Scipio.', importance:'Rome\'s victory made it the dominant power in the western Mediterranean.', facts:['The war began in 218 BCE and ended in 201 BCE.','Hannibal fought in Italy for years after crossing the Alps.','Rome\'s victory weakened Carthage and expanded Roman dominance.'], tags:['Rome','Carthage','War'], stats:{Influence:10,Complexity:6,Legacy:10,Military:10,Culture:6,Politics:8,Religion:1,Economy:8,Connections:10}, loc:{label:'Western Mediterranean',x:50,y:58}},
  {id:'BAT_ROM_001', type:'BATTLE', title:'Battle of Cannae', subtitle:'Hannibal\'s crushing victory over Rome', era:'Second Punic War', region:'Italy', date:'216 BCE', rarity:'LEGENDARY', difficulty:4, summary:'At Cannae, Hannibal defeated a large Roman army in one of history\'s most studied battlefield victories.', importance:'Cannae became a classic example of encirclement and a symbol of Rome\'s crisis during the war.', facts:['The battle took place in 216 BCE during the Second Punic War.','Hannibal\'s army defeated a much larger Roman force according to ancient accounts.','Despite the disaster, Rome refused to surrender.'], tags:['Battle','Rome','Carthage'], stats:{Influence:9,Complexity:5,Legacy:10,Military:10,Culture:7,Politics:5,Religion:1,Economy:4,Connections:9}, loc:{label:'Cannae',x:60,y:55}},
  {id:'PER_ROM_002', type:'PERSON', title:'Scipio Africanus', subtitle:'Roman commander who defeated Hannibal', era:'Punic Wars', region:'Rome / North Africa', date:'c. 236–183 BCE', rarity:'EPIC', difficulty:4, summary:'Scipio Africanus was the Roman commander who defeated Hannibal at Zama.', importance:'His victory secured Rome\'s triumph in the Second Punic War.', facts:['Scipio carried the war into Africa.','He defeated Hannibal at the Battle of Zama in 202 BCE.','His victory earned him the agnomen Africanus.'], tags:['Rome','Commander','Zama'], stats:{Influence:9,Complexity:5,Legacy:8,Military:10,Culture:5,Politics:6,Religion:1,Economy:4,Connections:8}, loc:{label:'Rome',x:55,y:49}},
  {id:'BAT_ROM_002', type:'BATTLE', title:'Battle of Zama', subtitle:'Rome defeats Hannibal', era:'Second Punic War', region:'North Africa', date:'202 BCE', rarity:'EPIC', difficulty:4, summary:'The Battle of Zama ended with Scipio Africanus defeating Hannibal and forcing Carthage to accept defeat.', importance:'Zama ended the Second Punic War and confirmed Rome\'s rise over Carthage.', facts:['The battle took place in 202 BCE.','Scipio Africanus commanded the Roman side.','Carthage lost the war after Zama.'], tags:['Battle','Rome','Carthage'], stats:{Influence:9,Complexity:4,Legacy:8,Military:9,Culture:5,Politics:8,Religion:1,Economy:7,Connections:8}, loc:{label:'Zama',x:47,y:63}},
  {id:'PER_ROM_003', type:'PERSON', title:'Julius Caesar', subtitle:'General, dictator and destroyer of the Republican balance', era:'Late Roman Republic', region:'Rome', date:'100–44 BCE', rarity:'LEGENDARY', difficulty:6, summary:'Julius Caesar was a Roman general and politician whose rise helped end the Roman Republic.', importance:'His civil war, dictatorship and assassination opened the path to imperial rule.', facts:['Caesar conquered Gaul and gained enormous military prestige.','He crossed the Rubicon in 49 BCE, beginning civil war against Pompey and the Senate\'s forces.','He was assassinated in 44 BCE.'], tags:['Rome','Caesar','Civil War'], stats:{Influence:10,Complexity:7,Legacy:10,Military:9,Culture:8,Politics:10,Religion:3,Economy:6,Connections:10}, loc:{label:'Rome',x:55,y:49}},
  {id:'EVT_ROM_003', type:'EVENT', title:'Crossing of the Rubicon', subtitle:'Point of no return in Caesar\'s civil war', era:'Late Roman Republic', region:'Northern Italy', date:'49 BCE', rarity:'LEGENDARY', difficulty:4, summary:'Caesar\'s crossing of the Rubicon marked open defiance of senatorial authority and began civil war.', importance:'It became a lasting symbol of irreversible political action.', facts:['The event is traditionally dated to 49 BCE.','Crossing with an army broke political norms and challenged Rome\'s government.','The act led into Caesar\'s civil war.'], tags:['Rome','Caesar','Civil War'], stats:{Influence:10,Complexity:5,Legacy:10,Military:7,Culture:8,Politics:10,Religion:1,Economy:4,Connections:10}, loc:{label:'Rubicon',x:56,y:42}},
  {id:'PER_ROM_004', type:'PERSON', title:'Augustus', subtitle:'First Roman emperor', era:'Early Roman Empire', region:'Rome', date:'63 BCE–14 CE', rarity:'MYTHIC', difficulty:6, summary:'Augustus was Rome\'s first emperor and the creator of the Principate.', importance:'He transformed the broken Republic into a durable imperial system.', facts:['Augustus was born Gaius Octavius and was Caesar\'s adopted heir.','He defeated Antony and Cleopatra\'s forces after the Battle of Actium.','His reign began the Roman imperial system.'], tags:['Rome','Empire','Augustus'], stats:{Influence:10,Complexity:7,Legacy:10,Military:7,Culture:9,Politics:10,Religion:6,Economy:8,Connections:10}, loc:{label:'Rome',x:55,y:49}}
];

const RELATIONS = [
  ['PER_ROM_001','EVT_ROM_001','FOUNDED_BY','Romulus is linked to Rome\'s foundation myth.'],['EVT_ROM_001','STATE_ROM_001','CAUSE','The foundation myth introduces the monarchic phase.'],['STATE_ROM_001','EVT_ROM_002','PRECEDES','The Kingdom precedes the Republic.'],['EVT_ROM_002','STATE_ROM_002','CAUSE','The expulsion of kings begins the Republic.'],['STATE_ROM_002','ORG_ROM_001','PART_OF','The Senate is central to Republican politics.'],['PER_CAR_001','WAR_ROM_001','PART_OF','Hannibal is central to the Second Punic War.'],['WAR_ROM_001','BAT_ROM_001','PART_OF','Cannae is a major battle of the war.'],['PER_CAR_001','BAT_ROM_001','COMMANDER_IN','Hannibal commanded at Cannae.'],['PER_ROM_002','BAT_ROM_002','COMMANDER_IN','Scipio commanded at Zama.'],['BAT_ROM_002','WAR_ROM_001','CONSEQUENCE','Zama decided the war in Rome\'s favor.'],['PER_ROM_003','EVT_ROM_003','CAUSE','Caesar caused the Rubicon crisis.'],['EVT_ROM_003','STATE_ROM_002','CONSEQUENCE','The crisis accelerates the Republic\'s collapse.'],['PER_ROM_003','PER_ROM_004','INFLUENCED','Caesar\'s career opened the path for Augustus.'],['PER_ROM_004','STATE_ROM_002','CONSEQUENCE','Augustus ended the Republican balance.']
].map((r,i)=>({id:'REL_'+String(i+1).padStart(3,'0'), source:r[0], target:r[1], type:r[2], description:r[3]}));

const CAMPAIGN = {id:'CAM_ROM_001', title:'Rome: From City to Empire', nodes:[
  {id:'NODE_ROM_001', title:'Birth of Rome', type:'INTRO', cards:['PER_ROM_001','EVT_ROM_001','STATE_ROM_001'], quiz:'QUIZ_ROM_001', xp:120},
  {id:'NODE_ROM_002', title:'Republic Rises', type:'LESSON', cards:['EVT_ROM_002','STATE_ROM_002','ORG_ROM_001'], quiz:'QUIZ_ROM_002', xp:150},
  {id:'NODE_ROM_003', title:'Rome vs Carthage', type:'BATTLE_STUDY', cards:['PER_CAR_001','WAR_ROM_001','BAT_ROM_001','PER_ROM_002','BAT_ROM_002'], quiz:'QUIZ_ROM_003', xp:200},
  {id:'NODE_ROM_004', title:'Caesar\'s Point of No Return', type:'STORY_SCENE', cards:['PER_ROM_003','EVT_ROM_003'], quiz:'QUIZ_ROM_004', xp:180},
  {id:'NODE_ROM_005', title:'From Republic to Empire', type:'BOSS_QUIZ', cards:['PER_ROM_004'], quiz:'QUIZ_ROM_005', xp:300}
]};

const QUIZZES = {
  QUIZ_ROM_001:{title:'Birth of Rome', questions:[{text:'Какая дата традиционно считается датой основания Рима?',answers:['753 BCE','509 BCE','216 BCE','44 BCE'],correct:0,explanation:'753 BCE — традиционная дата основания Рима. Это традиция, не точная археологическая дата.'},{text:'История Ромула и Рема — это надёжно подтверждённый документальный факт?',answers:['Да','Нет'],correct:1,explanation:'Нет. Это мифо-историческая традиция, важная для римской идентичности.'}]},
  QUIZ_ROM_002:{title:'Republic Basics', questions:[{text:'Римская республика была современной демократией?',answers:['Да','Нет','Только при Цезаре','Только во время Империи'],correct:1,explanation:'Нет. В ней были выборы и собрания, но власть элиты и Сената была огромной.'},{text:'Какой орган был ключевым центром влияния римской элиты?',answers:['Сенат','Колизей','Акведук','Преторианская гвардия'],correct:0,explanation:'Сенат был одним из главных центров политического влияния.'}]},
  QUIZ_ROM_003:{title:'Rome vs Carthage', questions:[{text:'Кто был главным карфагенским командиром во Второй Пунической войне?',answers:['Ганнибал','Сципион','Цезарь','Август'],correct:0,explanation:'Ганнибал Барка — главный карфагенский командир войны.'},{text:'Какая битва завершила войну победой Рима?',answers:['Канны','Зама','Фарсал','Акций'],correct:1,explanation:'Зама в 202 BCE закрепила поражение Карфагена.'}]},
  QUIZ_ROM_004:{title:'Caesar\'s Civil War', questions:[{text:'Что символизирует переход Рубикона?',answers:['Торговый договор','Точку невозврата','Основание города','Религиозную реформу'],correct:1,explanation:'Переход Рубикона стал символом необратимого политического шага.'},{text:'В каком году был убит Юлий Цезарь?',answers:['49 BCE','44 BCE','27 BCE','14 CE'],correct:1,explanation:'Цезарь был убит в 44 BCE.'}]},
  QUIZ_ROM_005:{title:'From Republic to Empire', questions:[{text:'Кем был Август в римской истории?',answers:['Первым римским императором','Последним царём Рима','Карфагенским полководцем','Плебейским трибуном'],correct:0,explanation:'Август считается первым римским императором.'},{text:'Какая связь лучше описывает Цезаря и Августа?',answers:['Цезарь открыл путь к власти Августа','Август победил Цезаря при Каннах','Август основал Карфаген','Цезарь был учеником Ганнибала'],correct:0,explanation:'Цезарь был политическим предшественником и приёмным отцом-наследодателем Августа.'}]}
};

const STORAGE_KEY = 'codex_history_mvp_v01';
let state = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null') || {tab:'home', xp:0, level:1, unlocked:['PER_ROM_001','EVT_ROM_001','STATE_ROM_001'], read:[], quizDone:[], currentCard:'PER_ROM_001', currentQuiz:null, quizIndex:0, quizScore:0, selected:null, filter:'ALL', search:''};
function save(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function card(id){ return CARDS.find(c=>c.id===id); }
function unlocked(c){ return state.unlocked.includes(c.id); }
function unlock(ids){ ids.forEach(id=>{ if(!state.unlocked.includes(id)) state.unlocked.push(id); }); save(); }
function addXp(x){ state.xp += x; state.level = Math.floor(state.xp / 500) + 1; save(); }
function progress(){ return Math.round((state.unlocked.length / CARDS.length) * 100); }
function currentNode(){ return CAMPAIGN.nodes.find(n => !state.quizDone.includes(n.quiz)) || CAMPAIGN.nodes[CAMPAIGN.nodes.length-1]; }
function nextLockedAfterQuiz(quizId){ const idx = CAMPAIGN.nodes.findIndex(n=>n.quiz===quizId); const next = CAMPAIGN.nodes[idx+1]; return next ? next.cards : []; }
function icon(type){ return ({PERSON:'♟',EVENT:'✦',BATTLE:'⚔',STATE:'♜',FACTION:'◆'}[type]||'◈'); }
function go(tab){ state.tab=tab; state.selected=null; save(); render(); }
function openCard(id){ state.currentCard=id; state.tab='detail'; if(!state.read.includes(id)){ state.read.push(id); addXp(10); } save(); render(); }
function openQuiz(id){ state.currentQuiz=id; state.quizIndex=0; state.quizScore=0; state.selected=null; state.tab='quiz'; save(); render(); }
function answer(i){ if(state.selected!==null) return; state.selected=i; const q = QUIZZES[state.currentQuiz].questions[state.quizIndex]; if(i===q.correct) state.quizScore++; save(); render(); }
function nextQuestion(){ const quiz = QUIZZES[state.currentQuiz]; if(state.quizIndex < quiz.questions.length-1){ state.quizIndex++; state.selected=null; save(); render(); return; } const id = state.currentQuiz; if(!state.quizDone.includes(id)){ state.quizDone.push(id); const node = CAMPAIGN.nodes.find(n=>n.quiz===id); addXp(node?.xp || 100); unlock(nextLockedAfterQuiz(id)); } state.tab='campaign'; state.selected=null; save(); render(); }
function reset(){ localStorage.removeItem(STORAGE_KEY); location.reload(); }
function openPack(){ const locked = CARDS.filter(c=>!unlocked(c)); const take = locked.sort(()=>Math.random()-.5).slice(0,2).map(c=>c.id); unlock(take); addXp(25); state.currentCard = take[0] || state.currentCard; state.tab='detail'; save(); render(); }

function shell(inner){
  return `<div class="topbar"><div class="brand"><div><small>Codex MVP</small><h1>Codex of History</h1></div><div class="level-pill">LVL ${state.level} · ${state.xp} XP</div></div></div><main class="content">${inner}</main><nav class="tabs">${['home','campaign','collection','map','profile'].map(t=>`<button class="tab ${state.tab===t?'active':''}" onclick="go('${t}')"><span>${({home:'⌂',campaign:'⚑',collection:'▣',map:'◎',profile:'☰'}[t])}</span>${({home:'Home',campaign:'Quest',collection:'Cards',map:'Map',profile:'Me'}[t])}</button>`).join('')}</nav>`;
}

function home(){ const node=currentNode(); const featured = card(state.currentCard); return shell(`
  <div class="hero-card card" onclick="openCard('${featured.id}')">
    <div class="badges"><span class="badge gold">${featured.rarity}</span><span class="badge">${featured.type}</span><span class="badge">${featured.date}</span></div>
    <h2 class="card-title">${featured.title}</h2><p class="card-subtitle">${featured.subtitle}</p><p class="card-text">${featured.summary}</p>
  </div>
  <div class="section-title"><h2>Прогресс Codex</h2><span>${state.unlocked.length}/${CARDS.length} cards</span></div>
  <div class="card"><div class="row"><b>${progress()}%</b><span>${state.read.length} прочитано</span></div><div class="progress" style="margin-top:10px"><span style="width:${progress()}%"></span></div></div>
  <div class="section-title"><h2>Продолжить кампанию</h2><span>${node.type}</span></div>
  <div class="list"><div class="list-item" onclick="go('campaign')"><div class="icon">⚑</div><div class="item-main"><h3>${node.title}</h3><p>${node.cards.map(id=>card(id)?.title).filter(Boolean).join(' · ')}</p></div></div></div>
  <div class="grid" style="margin-top:12px"><button class="btn" onclick="openPack()">Открыть Daily Pack</button><button class="btn secondary" onclick="openQuiz('${node.quiz}')">Быстрый квиз</button></div>
`); }

function campaign(){ return shell(`
  <div class="section-title"><h2>${CAMPAIGN.title}</h2><span>${state.quizDone.length}/${CAMPAIGN.nodes.length}</span></div>
  <div class="card"><p class="card-text">Первый путь MVP: миф основания → Республика → Карфаген → Цезарь → Август.</p><div class="progress" style="margin-top:12px"><span style="width:${Math.round(state.quizDone.length/CAMPAIGN.nodes.length*100)}%"></span></div></div>
  <div class="section-title"><h2>Главы</h2><span>данные, не код</span></div>
  <div class="list">${CAMPAIGN.nodes.map((n,idx)=>{ const isOpen = idx===0 || state.quizDone.includes(CAMPAIGN.nodes[idx-1].quiz); const done=state.quizDone.includes(n.quiz); return `<div class="list-item ${isOpen?'':'lock'}"><div class="icon">${done?'✓':idx+1}</div><div class="item-main"><h3>${n.title}</h3><p>${n.cards.map(id=>card(id)?.title).filter(Boolean).join(' · ')}</p></div><button class="btn ghost" style="width:auto;padding:9px 10px" ${isOpen?`onclick="openQuiz('${n.quiz}')"`:'disabled'}>${done?'Повтор':'Квиз'}</button></div>`}).join('')}</div>
`); }

function collection(){ const types=['ALL',...new Set(CARDS.map(c=>c.type))]; const list = CARDS.filter(c=>(state.filter==='ALL'||c.type===state.filter) && (c.title.toLowerCase().includes(state.search.toLowerCase()) || c.tags.join(' ').toLowerCase().includes(state.search.toLowerCase()))); return shell(`
  <div class="search-row"><input placeholder="Поиск: Caesar, Rome..." value="${state.search}" oninput="state.search=this.value;save();render()"><select onchange="state.filter=this.value;save();render()">${types.map(t=>`<option ${state.filter===t?'selected':''}>${t}</option>`).join('')}</select></div>
  <div class="card-grid">${list.map(c=>`<div class="mini-card ${unlocked(c)?'':'lock'}" onclick="${unlocked(c)?`openCard('${c.id}')`:''}"><div class="rarity">${c.rarity}</div><h3>${icon(c.type)} ${unlocked(c)?c.title:'Locked Card'}</h3><p>${unlocked(c)?c.summary:'Открой через кампанию или пак.'}</p></div>`).join('')}</div>
`); }

function detail(){ const c=card(state.currentCard); if(!c) return home(); const outgoing=RELATIONS.filter(r=>r.source===c.id||r.target===c.id); return shell(`
  <div class="detail-cover"><div><div class="badges"><span class="badge gold">${c.rarity}</span><span class="badge">${c.type}</span><span class="badge">${c.date}</span></div><h2>${c.title}</h2><div class="detail-sub">${c.subtitle}</div></div></div>
  <div class="card"><p class="card-text"><b>Суть:</b> ${c.summary}</p><p class="card-text" style="margin-top:10px"><b>Почему важно:</b> ${c.importance}</p></div>
  <div class="section-title"><h2>3 факта</h2><span>${c.era}</span></div>${c.facts.map(f=>`<div class="fact">${f}</div>`).join('')}
  <div class="section-title"><h2>Статы</h2><span>учебные</span></div><div class="card stats-bars">${Object.entries(c.stats).map(([k,v])=>`<div class="bar-row"><span>${k}</span><div class="bar-bg"><div class="bar-fill" style="width:${v*10}%"></div></div><b>${v}</b></div>`).join('')}</div>
  <div class="section-title"><h2>Связи</h2><span>${outgoing.length}</span></div><div class="graph">${outgoing.map(r=>{const other=card(r.source===c.id?r.target:r.source); return `<div class="edge" onclick="openCard('${other.id}')"><b>${r.type}</b> → ${other.title}<br>${r.description}</div>`}).join('') || '<div class="empty">Связей пока нет.</div>'}</div>
`); }

function quiz(){ const quiz=QUIZZES[state.currentQuiz] || QUIZZES[currentNode().quiz]; const q=quiz.questions[state.quizIndex]; const picked=state.selected!==null; return shell(`
  <div class="section-title"><h2>${quiz.title}</h2><span>${state.quizIndex+1}/${quiz.questions.length}</span></div>
  <div class="card"><h2 style="margin:0 0 14px;font-size:20px">${q.text}</h2>${q.answers.map((a,i)=>`<button class="quiz-answer ${picked?(i===q.correct?'correct':(i===state.selected?'wrong':'')):''}" onclick="answer(${i})">${a}</button>`).join('')}${picked?`<div class="explain">${q.explanation}</div><button class="btn" onclick="nextQuestion()">${state.quizIndex<quiz.questions.length-1?'Дальше':'Завершить'}</button>`:''}</div>
`); }

function mapScreen(){ return shell(`
  <div class="section-title"><h2>Карта MVP</h2><span>упрощённо</span></div>
  <div class="map">${CARDS.filter(unlocked).map(c=>`<div class="pin" style="left:${c.loc.x}%;top:${c.loc.y}%" onclick="openCard('${c.id}')"><span>${c.loc.label}</span></div>`).join('')}</div>
  <div class="section-title"><h2>Открытые точки</h2><span>${state.unlocked.length}</span></div>
  <div class="list">${CARDS.filter(unlocked).slice(0,8).map(c=>`<div class="list-item" onclick="openCard('${c.id}')"><div class="icon">${icon(c.type)}</div><div class="item-main"><h3>${c.title}</h3><p>${c.region} · ${c.date}</p></div></div>`).join('')}</div>
`); }

function profile(){ return shell(`
  <div class="card hero-card"><div class="badges"><span class="badge gold">Keeper in progress</span><span class="badge">localStorage</span></div><h2 class="card-title">Твой Codex</h2><p class="card-text">Локальный профиль MVP. Прогресс хранится в браузере.</p></div>
  <div class="grid" style="margin-top:12px"><div class="stat-box"><b>${state.xp}</b><span>XP</span></div><div class="stat-box"><b>${state.level}</b><span>Level</span></div><div class="stat-box"><b>${state.unlocked.length}</b><span>Cards</span></div><div class="stat-box"><b>${state.quizDone.length}</b><span>Quizzes</span></div></div>
  <div class="section-title"><h2>Система</h2><span>MVP</span></div><button class="btn secondary" onclick="reset()">Сбросить прогресс</button>
`); }

function render(){
  const root=document.getElementById('app');
  root.innerHTML = ({home, campaign, collection, detail, quiz, map:mapScreen, profile}[state.tab] || home)();
}
render();
