#!/usr/bin/env python3
from __future__ import annotations
import json, html
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
VERSION='4.0.0'
CHECKED='2026-07-14'

S_ASSYRIA={'title':'The Metropolitan Museum of Art: Assyria, 1365–609 B.C.','url':'https://www.metmuseum.org/essays/assyria-1365-609-b-c','type':'museum'}
S_NIMRUD={'title':'The Metropolitan Museum of Art: Nimrud','url':'https://www.metmuseum.org/essays/nimrud','type':'museum'}
S_SCULPTURE={'title':'The Metropolitan Museum of Art: The Assyrian Sculpture Court','url':'https://www.metmuseum.org/essays/the-assyrian-sculpture-court','type':'museum'}
S_NINEVEH={'title':'The Metropolitan Museum of Art: Nineveh','url':'https://www.metmuseum.org/essays/nineveh','type':'museum'}
S_BM_NINEVEH={'title':'British Museum: Assyria — Nineveh','url':'https://www.britishmuseum.org/collection/galleries/assyria-nineveh','type':'museum'}
S_BM_RELIEFS={'title':'British Museum: Assyria — Lion hunts, Siege of Lachish and Khorsabad','url':'https://www.britishmuseum.org/collection/galleries/assyria-lion-hunts','type':'museum'}
S_LIBRARY={'title':'British Museum: What was Ashurbanipal’s Library?','url':'https://www.britishmuseum.org/research/projects/what-was-ashurbanipals-library','type':'museum'}
S_BABYLON={'title':'The Metropolitan Museum of Art: Babylon','url':'https://www.metmuseum.org/essays/babylon','type':'museum'}
S_TIMELINE={'title':'The Metropolitan Museum of Art: Mesopotamia, 1000 B.C.–1 A.D.','url':'https://www.metmuseum.org/toah/ht/04/wam.html','type':'museum'}

P={
 'ASSUR':([35.456,43.262],'Ашшур'),'KALHU':([36.099,43.329],'Кальху'),'DUR_SHARRUKIN':([36.510,43.229],'Дур-Шаррукин'),
 'NINEVEH':([36.359,43.152],'Ниневия'),'ARBELA':([36.191,44.009],'Арбела'),'HARRAN':([36.864,39.031],'Харран'),
 'BABYLON':([32.536,44.421],'Вавилон'),'BORSIPPA':([32.392,44.342],'Борсиппа'),'URUK':([31.324,45.637],'Урук'),
 'SIPPAR':([33.057,44.252],'Сиппар'),'LACHISH':([31.565,34.849],'Лахиш'),'JERUSALEM':([31.778,35.235],'Иерусалим'),
 'SAMARIA':([32.276,35.198],'Самария'),'DAMASCUS':([33.513,36.292],'Дамаск'),'CARCHEMISH':([36.829,38.015],'Каркемиш'),
 'MEMPHIS':([29.849,31.254],'Мемфис'),'THEBES':([25.718,32.658],'Фивы'),'SUSA':([32.189,48.257],'Сузы'),
 'TAYMA':([27.621,38.548],'Тайма'),'TUSHPA':([38.501,43.372],'Тушпа'),'ZAGROS':([35.5,46.0],'Загрос'),
 'LEVANT':([33.0,35.3],'Левант'),'MESOPOTAMIA':([34.0,43.8],'Месопотамия')
}

CHAPTERS=[
{
 'title':'Мир после бронзового кризиса','subtitle':'Ассирия сохранила государственную традицию, но долго оставалась одной из нескольких сил раннего железного века.',
 'description':'После кризиса XII века до н. э. политическая карта Передней Азии стала более дробной. Ассирия удержала ядро вокруг Ашшура, Вавилония переживала смену династий и внешнее давление, а арамейские и неохеттские государства заняли важные территории между ними и Средиземноморьем.','period':'ок. 1100–900 годы до н. э.','source':S_ASSYRIA,
 'chronology':[('XI век до н. э.','Ассирия сохраняет ядро вокруг Ашшура','textual'),('ок. 1050–950 до н. э.','Арамейские группы закрепляются в Сирии и Верхней Месопотамии','mixed'),('X–IX века до н. э.','Неохеттские царства развиваются в Анатолии и северной Сирии','archaeological'),('начало IX века до н. э.','Ассирийские походы вновь становятся регулярными','textual')],
 'locations':['ASSUR','HARRAN','CARCHEMISH'],'causes':['Сохранение ассирийских городских и храмовых институтов','Ослабление прежних имперских систем','Рост региональных царств и племенных союзов'],'consequences':['Дробная политическая карта раннего железного века','Конкуренция за пути Верхней Месопотамии','Постепенное восстановление ассирийской экспансии'],
 'story':[('Ранний железный век Месопотамии','Early Iron Age Mesopotamia','PERIOD','период региональной перестройки после бронзового кризиса','ок. 1100–900 годы до н. э.','MESOPOTAMIA'),('Ассирийское ядро','Assyrian heartland','REGION','территория вокруг Ашшура, Ниневии и Арбелы','XI–IX века до н. э.','ASSUR'),('Ашшур как город и бог','Ashur city and deity','CITY','политический и культовый центр ассирийской традиции','II–I тысячелетия до н. э.','ASSUR'),('Арамейские царства','Aramean kingdoms','STATE','региональные государства Сирии и Верхней Месопотамии','XI–VIII века до н. э.','HARRAN'),('Неохеттские государства','Syro-Hittite states','STATE','царства Анатолии и северной Сирии после падения Хатти','XII–VIII века до н. э.','CARCHEMISH'),('Вавилония раннего железного века','Babylonia in the Early Iron Age','REGION','южная Месопотамия с городами, храмами и меняющимися династиями','XI–IX века до н. э.','BABYLON'),('Ассирийская царская традиция','Assyrian kingship','SYSTEM','связь царя, бога Ашшура, армии и храмов','I тысячелетие до н. э.','ASSUR'),('Региональная политическая мозаика','Iron Age political mosaic','CONCEPT','сосуществование городов, царств и племенных объединений','XI–IX века до н. э.','MESOPOTAMIA')],
 'archive':[('Ассирийский царский список железного века','Assyrian King List','TEXT','последовательность царей, требующая сопоставления с иными источниками','I тысячелетие до н. э.','ASSUR'),('Арамейская стела','Aramaean stele','ARTIFACT','надпись регионального правителя раннего железного века','X–IX века до н. э.','DAMASCUS'),('Керамика раннего железного века Верхней Месопотамии','Upper Mesopotamian Iron Age pottery','SOURCE','археологический материал для региональной хронологии','XI–IX века до н. э.','HARRAN'),('Проблема непрерывности после коллапса','Continuity after collapse','CONCEPT','вопрос о том, какие институты сохранились после кризиса','современная историография','ASSUR')]
},
{
 'title':'Возрождение Ассирии','subtitle':'Цари IX века восстановили контроль над ядром и превратили ежегодные походы в постоянный механизм расширения.',
 'description':'Ашшур-дан II, Адад-нирари II, Тукульти-Нинурта II и Ашшурнацирапал II последовательно возвращали земли, собирали дань и укрепляли военную инфраструктуру. Царские анналы описывают этот процесс как непрерывную победу, поэтому их нужно читать вместе с картой и археологией.','period':'ок. 935–859 годы до н. э.','source':S_ASSYRIA,
 'chronology':[('934–912 до н. э.','Правление Ашшур-дана II','textual'),('911–891 до н. э.','Адад-нирари II расширяет влияние Ассирии','textual'),('890–884 до н. э.','Тукульти-Нинурта II проводит походы на запад и север','textual'),('883–859 до н. э.','Ашшурнацирапал II создаёт новую столицу в Кальху','textual')],
 'locations':['ASSUR','KALHU','HARRAN'],'causes':['Восстановление сельского хозяйства и налоговой базы','Контроль путей к Сирии и Анатолии','Регулярные походы и система дани'],'consequences':['Рост территории и ресурсов царства','Перенос столицы в Кальху','Формирование модели новоассирийской экспансии'],
 'story':[('Ашшур-дан II','Ashur-dan II','PERSON','царь, начавший восстановление ассирийской территории','934–912 годы до н. э.','ASSUR'),('Адад-нирари II','Adad-nirari II','PERSON','царь ранней новоассирийской экспансии','911–891 годы до н. э.','ASSUR'),('Тукульти-Нинурта II','Tukulti-Ninurta II','PERSON','царь и военный организатор начала IX века','890–884 годы до н. э.','ASSUR'),('Ашшурнацирапал II','Ashurnasirpal II','PERSON','царь, расширивший державу и основавший столицу в Кальху','883–859 годы до н. э.','KALHU'),('Ежегодный царский поход','Annual royal campaign','SYSTEM','военная и политическая практика поддержания власти','IX–VII века до н. э.','ASSUR'),('Дань новоассирийскому царю','Neo-Assyrian tribute','SYSTEM','платёж зависимых правителей ресурсами и изделиями','IX–VII века до н. э.','HARRAN'),('Царские анналы Ассирии','Assyrian royal annals','TEXT','официальные записи походов и побед','IX–VII века до н. э.','ASSUR'),('Возвращение Верхней Месопотамии','Assyrian reconquest of Upper Mesopotamia','EVENT','серия походов и аннексий ранних новоассирийских царей','X–IX века до н. э.','HARRAN')],
 'archive':[('Стела Ашшурнацирапала II','Ashurnasirpal II stele','ARTIFACT','царское изображение с надписью о власти и походах','IX век до н. э.','KALHU'),('Монолит Курха','Kurkh Monoliths','ARTIFACT','аннальная надпись о походах ассирийских царей','IX век до н. э.','ASSUR'),('Список дани западных царств','Western tribute list','TEXT','идеологизированная запись поступлений от зависимых правителей','IX век до н. э.','HARRAN'),('Маршрут ранних ассирийских походов','Early Neo-Assyrian campaign route','ROUTE','реконструкция движения армии через Верхнюю Месопотамию','IX век до н. э.','HARRAN')]
},
{
 'title':'Кальху и дворец Ашшурнацирапала II','subtitle':'Новая столица стала административным центром, строительной площадкой и сценой царской идеологии.',
 'description':'Ашшурнацирапал II перестроил Кальху, современный Нимруд, и возвёл Северо-западный дворец. Рельефы, крылатые быки, надписи и пир при открытии столицы показывали власть царя, но одновременно дают данные о ремесле, одежде, растениях и покорённых регионах.','period':'IX век до н. э.','source':S_NIMRUD,
 'chronology':[('883 до н. э.','Начало правления Ашшурнацирапала II','textual'),('IX век до н. э.','Масштабная перестройка Кальху','archaeological'),('ок. 879 до н. э.','Пир по случаю завершения новой столицы','textual'),('IX–VIII века до н. э.','Кальху остаётся важным дворцовым и административным центром','archaeological')],
 'locations':['KALHU','ASSUR','NINEVEH'],'causes':['Потребность в новом административном центре','Демонстрация ресурсов расширяющейся державы','Концентрация чиновников, ремесленников и войск'],'consequences':['Возникновение монументального дворцового комплекса','Развитие ассирийского дворцового рельефа','Перемещение людей и ресурсов в новую столицу'],
 'story':[('Кальху','Kalhu','CITY','новоассирийская столица, известная как Нимруд','IX–VIII века до н. э.','KALHU'),('Северо-западный дворец','Northwest Palace of Ashurnasirpal II','BUILDING','дворец Ашшурнацирапала II в Кальху','IX век до н. э.','KALHU'),('Кальхуский пир','Banquet Stele of Ashurnasirpal II','EVENT','массовое торжество при открытии новой столицы','ок. 879 год до н. э.','KALHU'),('Ассирийский дворцовый рельеф','Assyrian palace relief','ARTIFACT','каменная панель с ритуальными и военными сценами','IX–VII века до н. э.','KALHU'),('Ламассу Кальху','Lamassu from Nimrud','ARTIFACT','крылатый человекобык — защитник дворцового входа','IX век до н. э.','KALHU'),('Священное дерево в ассирийском искусстве','Sacred tree in Assyrian art','RELIGION','ритуальный образ дворцовых рельефов','IX–VII века до н. э.','KALHU'),('Дворцовые мастерские Кальху','Nimrud palace workshops','SYSTEM','производство и хранение предметов при царском дворе','IX–VIII века до н. э.','KALHU'),('Столичная политика переселения','Capital resettlement policy','SYSTEM','перемещение работников и специалистов в новую столицу','IX век до н. э.','KALHU')],
 'archive':[('Стандартная надпись Ашшурнацирапала II','Standard Inscription of Ashurnasirpal II','TEXT','повторяющаяся царская надпись на дворцовых рельефах','IX век до н. э.','KALHU'),('Нимрудские слоновые кости','Nimrud ivories','ARTIFACT','изделия разных художественных традиций из дворцовых хранилищ','IX–VIII века до н. э.','KALHU'),('Кальхуские царские гробницы','Queens’ Tombs at Nimrud','SITE','погребения ассирийских цариц с богатыми находками','VIII век до н. э.','KALHU'),('Археологический контекст Нимруда','Archaeological context of Nimrud','SOURCE','слои дворцов, храмов и позднейшего разрушения','IX–VII века до н. э.','KALHU')]
},
{
 'title':'Имперская машина','subtitle':'Провинции, дороги, чиновники, налоги и депортации связывали огромную территорию с царским двором.',
 'description':'Новоассирийская держава управлялась не только армией. Провинциальные наместники, царские посланцы, дорожные станции, архивы и системы поставок превращали завоевания в устойчивый контроль. Массовые депортации были инструментом наказания, заселения и перераспределения труда.','period':'IX–VII века до н. э.','source':S_ASSYRIA,
 'chronology':[('IX век до н. э.','Расширение провинциальной системы','textual'),('VIII век до н. э.','Рост сети царских дорог и станций','interpretive'),('744–727 до н. э.','Реформы Тиглатпаласара III усиливают прямое управление','textual'),('VII век до н. э.','Имперская переписка связывает столицы и провинции','textual')],
 'locations':['NINEVEH','DAMASCUS','SAMARIA'],'causes':['Необходимость удерживать покорённые территории','Потребность снабжать армию и столицы','Стремление уменьшить самостоятельность вассалов'],'consequences':['Рост числа провинций и чиновников','Перемещение сотен тысяч людей в течение истории империи','Распространение арамейского языка и смешение населения'],
 'story':[('Новоассирийская провинция','Neo-Assyrian province','SYSTEM','территория под управлением назначенного наместника','IX–VII века до н. э.','NINEVEH'),('Ассирийский наместник','Neo-Assyrian governor','OFFICE','царский чиновник, отвечавший за налоги, войска и порядок','IX–VII века до н. э.','NINEVEH'),('Царская дорога Ассирии','Neo-Assyrian royal road','ROUTE','сеть путей между столицами, провинциями и фронтирами','VIII–VII века до н. э.','MESOPOTAMIA'),('Каллу — царский гонец','Assyrian royal messenger','OFFICE','служащий системы быстрой доставки приказов','VIII–VII века до н. э.','NINEVEH'),('Ассирийская депортация','Neo-Assyrian deportation','SYSTEM','принудительное переселение населения внутри империи','IX–VII века до н. э.','SAMARIA'),('Имперская переписка','Neo-Assyrian state correspondence','TEXT','письма чиновников, военных и разведчиков царю','VIII–VII века до н. э.','NINEVEH'),('Провинциальный налог','Assyrian provincial taxation','SYSTEM','регулярные поставки людей, скота, зерна и материалов','IX–VII века до н. э.','DAMASCUS'),('Арамейский язык империи','Aramaic in the Neo-Assyrian Empire','TEXT','широко используемый язык управления и общения','VIII–VII века до н. э.','LEVANT')],
 'archive':[('Письмо наместника царю','Letter from an Assyrian governor','TEXT','оперативный отчёт о провинции и угрозах','VIII–VII века до н. э.','NINEVEH'),('Список депортированных общин','Assyrian deportation list','TEXT','административная запись перемещённых групп','VIII–VII века до н. э.','SAMARIA'),('Дорожная станция империи','Assyrian road station','SITE','пункт снабжения и смены животных на маршруте','VIII–VII века до н. э.','HARRAN'),('Печать ассирийского чиновника','Neo-Assyrian official seal','ARTIFACT','средство удостоверения документа и статуса','VIII–VII века до н. э.','NINEVEH')]
},
{
 'title':'Армия, осады и страх','subtitle':'Ассирийское превосходство создавали организация, логистика, инженерия и разнообразные войска, а не один металл.',
 'description':'Армия включала пехоту, лучников, пращников, колесницы, конницу, сапёров и вспомогательные контингенты. Рельефы подробно показывают осады, но созданы как царская пропаганда. Железное оружие было важно, однако само по себе не объясняет успех империи.','period':'IX–VII века до н. э.','source':S_BM_RELIEFS,
 'chronology':[('IX век до н. э.','Конница становится самостоятельным родом войск','iconographic'),('VIII век до н. э.','Развиваются постоянные части и инженерные подразделения','interpretive'),('701 до н. э.','Осада Лахиша войсками Синаххериба','textual'),('VII век до н. э.','Дворцовые рельефы фиксируют стандартный образ победы','iconographic')],
 'locations':['LACHISH','NINEVEH','ZAGROS'],'causes':['Сложная система снабжения и мобилизации','Использование специалистов и вспомогательных войск','Развитие осадной инженерии и разведки'],'consequences':['Высокая мобильность армии','Захват укреплённых городов','Создание репутации неизбежного наказания'],
 'story':[('Новоассирийская армия','Neo-Assyrian army','WAR','многочастная военная организация империи','IX–VII века до н. э.','NINEVEH'),('Ассирийская конница','Neo-Assyrian cavalry','WAR','род войск, развившийся из парных всадников в самостоятельные части','IX–VII века до н. э.','NINEVEH'),('Осадный таран Ассирии','Assyrian battering ram','ARTIFACT','машина для разрушения ворот и стен','IX–VII века до н. э.','LACHISH'),('Ассирийские сапёры','Assyrian military engineers','OFFICE','специалисты по подкопам, насыпям и переправам','IX–VII века до н. э.','LACHISH'),('Осада Лахиша','Siege of Lachish','BATTLE','захват иудейского города армией Синаххериба','701 год до н. э.','LACHISH'),('Лахишские рельефы','Lachish reliefs','ARTIFACT','дворцовый цикл изображений осады и депортации','ок. 700–692 годы до н. э.','NINEVEH'),('Военная пропаганда Ассирии','Neo-Assyrian military propaganda','SYSTEM','публичный образ царской победы и наказания врагов','IX–VII века до н. э.','NINEVEH'),('Миф о железном превосходстве','Iron weapon superiority myth','CONCEPT','упрощённое объяснение ассирийских побед только металлом','современная историография','MESOPOTAMIA')],
 'archive':[('Рельеф ассирийского лучника и пращника','Assyrian archer and slinger relief','ARTIFACT','изображение взаимодействия разных видов пехоты','VII век до н. э.','NINEVEH'),('Сцена наведения понтонного моста','Assyrian pontoon bridge scene','ARTIFACT','изображение инженерного обеспечения похода','VII век до н. э.','MESOPOTAMIA'),('Железный наконечник ассирийского копья','Neo-Assyrian iron spearhead','ARTIFACT','предмет вооружения, не объясняющий организацию армии целиком','IX–VII века до н. э.','NINEVEH'),('Царский отчёт об осаде','Assyrian siege account','TEXT','аннальная версия военной кампании','VIII–VII века до н. э.','LACHISH')]
},
{
 'title':'Тиглатпаласар III и Саргон II','subtitle':'Реформы VIII века превратили зависимые царства в провинции и резко расширили прямое управление.',
 'description':'Тиглатпаласар III перестроил армию и администрацию, аннексировал территории в Сирии и Леванте и вмешивался в Вавилонию. Саргон II продолжил расширение, закрепил власть после падения Самарии и построил новую столицу Дур-Шаррукин.','period':'744–705 годы до н. э.','source':S_BM_RELIEFS,
 'chronology':[('744–727 до н. э.','Правление Тиглатпаласара III','textual'),('732 до н. э.','Дамаск превращён в ассирийскую провинцию','textual'),('722–705 до н. э.','Правление Саргона II','textual'),('конец VIII века до н. э.','Строительство Дур-Шаррукина','archaeological')],
 'locations':['DAMASCUS','SAMARIA','DUR_SHARRUKIN'],'causes':['Стремление заменить ненадёжных вассалов прямым управлением','Военная конкуренция в Сирии, Урарту и Вавилонии','Потребность в более постоянной армии'],'consequences':['Расширение провинциальной системы','Падение Дамаска и Самарии','Создание новой столицы Дур-Шаррукин'],
 'story':[('Тиглатпаласар III','Tiglath-Pileser III','PERSON','царь-реформатор новоассирийской державы','744–727 годы до н. э.','NINEVEH'),('Реформы Тиглатпаласара III','Reforms of Tiglath-Pileser III','EVENT','перестройка армии и провинциального управления','VIII век до н. э.','NINEVEH'),('Аннексия Дамаска','Assyrian annexation of Damascus','EVENT','ликвидация арамейского царства и создание провинции','732 год до н. э.','DAMASCUS'),('Падение Самарии','Fall of Samaria','EVENT','конец Северного Израильского царства под ассирийским давлением','722/720 годы до н. э.','SAMARIA'),('Саргон II','Sargon II','PERSON','ассирийский царь и основатель Дур-Шаррукина','722–705 годы до н. э.','DUR_SHARRUKIN'),('Дур-Шаррукин','Dur-Sharrukin','CITY','новая столица Саргона II, современный Хорсабад','конец VIII века до н. э.','DUR_SHARRUKIN'),('Саргонова династия','Sargonid dynasty','DYNASTY','правящая линия последних великих ассирийских царей','722–609 годы до н. э.','NINEVEH'),('Ассирия и Урарту','Assyria–Urartu rivalry','WAR','борьба за северные пути и влияние','IX–VIII века до н. э.','TUSHPA')],
 'archive':[('Призма Тиглатпаласара III','Tiglath-Pileser III inscriptions','TEXT','царская надпись о реформах и походах','VIII век до н. э.','NINEVEH'),('Ламассу Дур-Шаррукина','Khorsabad lamassu','ARTIFACT','монументальный защитник дворцовых ворот Саргона II','VIII век до н. э.','DUR_SHARRUKIN'),('Рельеф похода Саргона II','Sargon II campaign relief','ARTIFACT','дворцовое изображение военной победы','VIII век до н. э.','DUR_SHARRUKIN'),('Проблема датировки падения Самарии','Dating the fall of Samaria','CONCEPT','различие между завоеванием, подавлением восстания и царскими версиями','722–720 годы до н. э.','SAMARIA')]
},
{
 'title':'Синаххериб и Ниневия','subtitle':'Новая столица, каналы и дворцы соседствовали с войнами в Леванте и жестоким конфликтом вокруг Вавилона.',
 'description':'Синаххериб перенёс главный царский центр в Ниневию, расширил город и создал сложную систему водоснабжения. Его поход 701 года до н. э. известен по ассирийским текстам, Лахишским рельефам и другим традициям. В 689 году до н. э. ассирийцы разрушили Вавилон.','period':'704–681 годы до н. э.','source':S_NINEVEH,
 'chronology':[('704–681 до н. э.','Правление Синаххериба','textual'),('701 до н. э.','Поход в Левант и осада Лахиша','textual'),('конец VIII – начало VII века до н. э.','Расширение Ниневии и строительство каналов','archaeological'),('689 до н. э.','Разрушение Вавилона войсками Синаххериба','textual')],
 'locations':['NINEVEH','LACHISH','BABYLON'],'causes':['Стремление создать новую имперскую столицу','Восстания в Леванте и Вавилонии','Контроль воды и сельскохозяйственного окружения Ниневии'],'consequences':['Рост Ниневии до крупнейшего центра державы','Создание дворцового цикла Лахишских рельефов','Глубокий политический и религиозный кризис вокруг Вавилона'],
 'story':[('Синаххериб','Sennacherib','PERSON','ассирийский царь, строитель Ниневии и участник крупных войн','704–681 годы до н. э.','NINEVEH'),('Ниневия Синаххериба','Sennacherib’s Nineveh','CITY','перестроенная столица поздней Ассирии','VII век до н. э.','NINEVEH'),('Дворец без соперника','Southwest Palace of Sennacherib','BUILDING','главный дворец Синаххериба в Ниневии','VII век до н. э.','NINEVEH'),('Каналы Ниневии','Sennacherib’s aqueducts and canals','BUILDING','система доставки воды к столице и садам','VII век до н. э.','NINEVEH'),('Поход Синаххериба в Левант','Sennacherib’s Levant campaign','EVENT','кампания против восставших царств в 701 году','701 год до н. э.','LACHISH'),('Осада Иерусалима 701 года','Siege of Jerusalem by Sennacherib','EVENT','ассирийское давление на Иудею при царе Езекии','701 год до н. э.','JERUSALEM'),('Разрушение Вавилона Синаххерибом','Destruction of Babylon by Sennacherib','EVENT','разрушение города после длительного сопротивления','689 год до н. э.','BABYLON'),('Призма Синаххериба','Sennacherib’s Prism','TEXT','царская надпись о походах и дани','начало VII века до н. э.','NINEVEH')],
 'archive':[('Акведук Джерван','Jerwan Aqueduct','BUILDING','каменное сооружение системы водоснабжения Ниневии','VII век до н. э.','NINEVEH'),('Рельеф садов Ниневии','Nineveh garden relief','ARTIFACT','изображение царского сада и водных сооружений','VII век до н. э.','NINEVEH'),('Тейлорова призма','Taylor Prism','ARTIFACT','копия анналов Синаххериба о походе 701 года','VII век до н. э.','NINEVEH'),('Сопоставление источников о 701 годе','Sources for Sennacherib’s campaign of 701 BCE','CONCEPT','сравнение ассирийских надписей, рельефов и иных традиций','современная историография','JERUSALEM')]
},
{
 'title':'Асархаддон и Ашшурбанипал','subtitle':'Поздняя империя достигла огромного масштаба, но зависела от сложной династической политики и постоянных войн.',
 'description':'Асархаддон восстановил Вавилон и завоевал Мемфис. Ашшурбанипал правил из Ниневии, воевал в Египте и Эламе, подавил восстание брата Шамаш-шум-укина и собрал огромный корпус текстов, известный как его библиотека.','period':'681–ок. 631 годы до н. э.','source':S_LIBRARY,
 'chronology':[('681–669 до н. э.','Правление Асархаддона','textual'),('671 до н. э.','Ассирийцы захватывают Мемфис','textual'),('669–ок. 631 до н. э.','Правление Ашшурбанипала','textual'),('652–648 до н. э.','Гражданская война с Шамаш-шум-укином','textual')],
 'locations':['NINEVEH','MEMPHIS','SUSA'],'causes':['Стремление контролировать Египет и Элам','Необходимость управлять двумя царскими центрами — Ассирией и Вавилонией','Борьба за престол и лояльность элит'],'consequences':['Кратковременное расширение в Египет','Разрушение Суз и ослабление Элама','Гражданская война и рост нагрузки на империю'],
 'story':[('Асархаддон','Esarhaddon','PERSON','ассирийский царь, восстановивший Вавилон и завоевавший Мемфис','681–669 годы до н. э.','NINEVEH'),('Завоевание Мемфиса Асархаддоном','Assyrian conquest of Memphis','EVENT','ассирийская победа в Египте','671 год до н. э.','MEMPHIS'),('Договоры о престолонаследии Асархаддона','Succession Treaties of Esarhaddon','LAW','клятвенные документы в поддержку наследника','672 год до н. э.','NINEVEH'),('Ашшурбанипал','Ashurbanipal','PERSON','последний великий царь новоассирийской державы','669–ок. 631 годы до н. э.','NINEVEH'),('Библиотека Ашшурбанипала','Library of Ashurbanipal','TEXT','десятки тысяч табличек и фрагментов из Ниневии','VII век до н. э.','NINEVEH'),('Царская охота на львов','Lion Hunt of Ashurbanipal','RITUAL','дворцовый образ царя, побеждающего хаос','VII век до н. э.','NINEVEH'),('Шамаш-шум-укин','Shamash-shum-ukin','PERSON','брат Ашшурбанипала и царь Вавилона','668–648 годы до н. э.','BABYLON'),('Разрушение Суз Ашшурбанипалом','Destruction of Susa by Ashurbanipal','EVENT','ассирийский поход против Элама','647 год до н. э.','SUSA')],
 'archive':[('Табличка эпоса о Гильгамеше из Ниневии','Gilgamesh tablet from Nineveh','TEXT','копия литературного текста из библиотечного корпуса','VII век до н. э.','NINEVEH'),('Медицинская серия Ниневии','Nineveh Medical Encyclopaedia','TEXT','систематизированный корпус медицинских текстов','VII век до н. э.','NINEVEH'),('Рельеф битвы при Тиль-Тубе','Battle of Til-Tuba relief','ARTIFACT','изображение ассирийской победы над Эламом','VII век до н. э.','NINEVEH'),('Письмо учёного Ашшурбанипалу','Scholar’s letter to Ashurbanipal','TEXT','переписка специалистов двора с царём','VII век до н. э.','NINEVEH')]
},
{
 'title':'Падение Ассирии','subtitle':'После смерти Ашшурбанипала династический кризис совпал с восстанием Вавилонии и наступлением мидян.',
 'description':'Империя не рухнула от одного удара. Гражданские конфликты, восстание Набопаласара, потеря провинций и совместные действия вавилонян и мидян привели к падению Ашшура в 614 году и Ниневии в 612 году до н. э. Ассирийский двор сопротивлялся до поражения при Харране.','period':'ок. 631–609 годы до н. э.','source':S_ASSYRIA,
 'chronology':[('626 до н. э.','Набопаласар утверждается в Вавилоне','textual'),('614 до н. э.','Мидяне захватывают Ашшур','textual'),('612 до н. э.','Падение Ниневии','textual'),('609 до н. э.','Поражение последнего ассирийского центра при Харране','textual')],
 'locations':['ASSUR','NINEVEH','HARRAN'],'causes':['Династические конфликты после Ашшурбанипала','Потеря контроля над Вавилонией и западными провинциями','Союз Набопаласара с мидийскими силами'],'consequences':['Разрушение ассирийских столиц','Исчезновение имперского центра','Возвышение Нововавилонского царства'],
 'story':[('Син-шар-ишкун','Sinsharishkun','PERSON','один из последних царей Ассирии','ок. 627–612 годы до н. э.','NINEVEH'),('Набопаласар','Nabopolassar','PERSON','основатель Нововавилонского царства','626–605 годы до н. э.','BABYLON'),('Мидийско-вавилонский союз','Medo-Babylonian alliance','SYSTEM','военное сотрудничество против Ассирии','конец VII века до н. э.','ZAGROS'),('Падение Ашшура','Fall of Assur','EVENT','захват древнего ассирийского центра мидянами','614 год до н. э.','ASSUR'),('Падение Ниневии','Fall of Nineveh','EVENT','разрушение столицы объединёнными силами противников','612 год до н. э.','NINEVEH'),('Харранский последний рубеж','Assyrian stand at Harran','EVENT','последняя попытка сохранить ассирийскую власть','610–609 годы до н. э.','HARRAN'),('Вавилонская хроника падения Ниневии','Fall of Nineveh Chronicle','TEXT','поздневавилонская запись событий войны','VII век до н. э.','BABYLON'),('Конец новоассирийской державы','End of the Neo-Assyrian Empire','EVENT','переход гегемонии к новым региональным силам','609 год до н. э.','HARRAN')],
 'archive':[('Хроника Набопаласара','Nabopolassar Chronicle','TEXT','клинописная запись войн против Ассирии','VII век до н. э.','BABYLON'),('Слой разрушения Ниневии','Destruction layer of Nineveh','SOURCE','археологические следы финальной осады и пожара','612 год до н. э.','NINEVEH'),('Последний ассирийский царь Ашшур-убаллит II','Ashur-uballit II','PERSON','правитель ассирийского сопротивления в Харране','611–609 годы до н. э.','HARRAN'),('Проблема причин падения Ассирии','Causes of Assyria’s fall','CONCEPT','многофакторная реконструкция конца империи','современная историография','NINEVEH')]
},
{
 'title':'Нововавилонское царство','subtitle':'Вавилон стал столицей новой державы, объединившей южную Месопотамию и значительную часть Леванта.',
 'description':'Набопаласар и Навуходоносор II создали государство на наследии вавилонских городов и победе над Ассирией. Строительство в Вавилоне, войны в Леванте, депортации и храмовая экономика были частью одной политической системы. В 539 году до н. э. город перешёл под власть Кира II.','period':'626–539 годы до н. э.','source':S_BABYLON,
 'chronology':[('605 до н. э.','Победа Навуходоносора II при Каркемише','textual'),('604–562 до н. э.','Правление Навуходоносора II','textual'),('597 и 586 до н. э.','Завоевания Иерусалима и депортации','textual'),('539 до н. э.','Вавилон переходит под власть Кира II','textual')],
 'locations':['BABYLON','CARCHEMISH','JERUSALEM'],'causes':['Победа над остатками Ассирии и Египтом','Сильная городская и храмовая база Вавилонии','Контроль путей через Сирию и Левант'],'consequences':['Монументальная перестройка Вавилона','Депортации из Иудеи и других регионов','Включение Вавилонии в державу Ахеменидов'],
 'story':[('Нововавилонское царство','Neo-Babylonian Empire','STATE','держава халдейской династии со столицей в Вавилоне','626–539 годы до н. э.','BABYLON'),('Навуходоносор II','Nebuchadnezzar II','PERSON','главный царь Нововавилонской державы и строитель Вавилона','604–562 годы до н. э.','BABYLON'),('Битва при Каркемише','Battle of Carchemish','BATTLE','победа вавилонян над египетской армией','605 год до н. э.','CARCHEMISH'),('Ворота Иштар','Ishtar Gate','BUILDING','монументальные ворота процессуальной дороги Вавилона','VI век до н. э.','BABYLON'),('Этеменанки','Etemenanki','BUILDING','главный зиккурат Вавилона, связанный с храмом Мардука','I тысячелетие до н. э.','BABYLON'),('Вавилонское завоевание Иерусалима','Babylonian conquest of Jerusalem','EVENT','кампании 597 и 586 годов до н. э.','VI век до н. э.','JERUSALEM'),('Вавилонское переселение иудеев','Babylonian captivity','EVENT','депортация части населения Иудеи в Вавилонию','VI век до н. э.','BABYLON'),('Падение Вавилона в 539 году','Fall of Babylon in 539 BCE','EVENT','переход города под власть Кира II','539 год до н. э.','BABYLON')],
 'archive':[('Цилиндр Навуходоносора II','Nebuchadnezzar II cylinder','TEXT','строительная надпись нововавилонского царя','VI век до н. э.','BABYLON'),('Процессуальная дорога Вавилона','Processional Way of Babylon','BUILDING','ритуальный маршрут через монументальный центр города','VI век до н. э.','BABYLON'),('Набонид','Nabonidus','PERSON','последний нововавилонский царь, долго находившийся в Тайме','556–539 годы до н. э.','TAYMA'),('Цилиндр Кира','Cyrus Cylinder','TEXT','ахеменидская царская надпись после завоевания Вавилона','539 год до н. э.','BABYLON')]
}
]

TYPE_LABEL={'PERSON':'личность','CITY':'город','STATE':'государство','EVENT':'событие','DYNASTY':'династия','BUILDING':'сооружение','OFFICE':'должность','PERIOD':'период','SYSTEM':'система','TEXT':'текст','REGION':'регион','RESOURCE':'ресурс','ROUTE':'маршрут','PEOPLE':'народ','WAR':'военное дело','SITE':'место','RELIGION':'религия','CULTURE':'культура','BATTLE':'битва','CONCEPT':'понятие','ARTIFACT':'артефакт','LAW':'правовой текст','RIVER':'река','RITUAL':'ритуал','SOURCE':'источник'}

def dump(path,obj):
 p=ROOT/path;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

def svg_card(path,title,subtitle,chapter,index,kind):
 p=ROOT/path;p.parent.mkdir(parents=True,exist_ok=True)
 title=html.escape(title);subtitle=html.escape(subtitle);marks=['𒀭','⚒','⌂','▦','⚔','♜','◇','▥','◆','𒆳'];acc=['#a88b63','#9a7555','#b49561','#7f8c78','#a66e55','#8e795c','#786c52','#856857','#a36f58','#b58d53'][chapter-1]
 p.write_text(f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 720 900" role="img" aria-label="{title}"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="#050606"/><stop offset=".58" stop-color="#25221d"/><stop offset="1" stop-color="#0b0806"/></linearGradient><radialGradient id="r"><stop stop-color="{acc}" stop-opacity=".54"/><stop offset="1" stop-color="{acc}" stop-opacity="0"/></radialGradient></defs><rect width="720" height="900" fill="url(#g)"/><circle cx="535" cy="205" r="300" fill="url(#r)"/><path d="M0 700 C145 625 275 735 430 655 S625 620 720 666 V900 H0Z" fill="#030405" opacity=".94"/><path d="M62 112 H658 M62 790 H658" stroke="{acc}" stroke-width="2" opacity=".85"/><text x="62" y="82" fill="{acc}" font-size="20" font-family="Arial" letter-spacing="4">IRON AGE · ASSYRIA &amp; BABYLON · {chapter:02d}</text><text x="550" y="370" text-anchor="middle" fill="{acc}" font-size="156" font-family="serif" opacity=".9">{marks[chapter-1]}</text><path d="M80 485 L170 405 L255 475 L350 390 L465 480 L585 392 L650 465" fill="none" stroke="{acc}" stroke-width="7" opacity=".3"/><text x="62" y="654" fill="#fff8e9" font-size="40" font-family="Georgia">{title[:31]}</text><text x="62" y="710" fill="#d8d0c2" font-size="22" font-family="Arial">{subtitle[:54]}</text><text x="62" y="832" fill="{acc}" font-size="18" font-family="Arial" letter-spacing="3">{kind.upper()} · CODEX OF HISTORY · {index:02d}</text></svg>''',encoding='utf-8')

def pack_svg():
 p=ROOT/'assets/packs/assyria-babylon-pack.svg';p.parent.mkdir(parents=True,exist_ok=True)
 p.write_text('''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 720 960"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="#080909"/><stop offset=".58" stop-color="#33291f"/><stop offset="1" stop-color="#100807"/></linearGradient><radialGradient id="r"><stop stop-color="#c49b62" stop-opacity=".62"/><stop offset="1" stop-color="#c49b62" stop-opacity="0"/></radialGradient></defs><rect width="720" height="960" rx="58" fill="url(#g)"/><circle cx="500" cy="250" r="360" fill="url(#r)"/><path d="M115 555 L215 455 L310 555 L405 425 L515 555 L620 460" fill="none" stroke="#c49b62" stroke-width="13" opacity=".58"/><text x="80" y="120" fill="#c49b62" font-size="22" font-family="Arial" letter-spacing="5">ЖЕЛЕЗНЫЙ ВЕК</text><text x="80" y="720" fill="#fff7e4" font-size="58" font-family="Georgia">Архив империй</text><text x="80" y="790" fill="#d9cbb5" font-size="28" font-family="Arial">Ассирия и Нововавилонское царство</text><text x="80" y="885" fill="#c49b62" font-size="21" font-family="Arial" letter-spacing="4">4 КАРТЫ · ОТКРЫТЫЕ ГЛАВЫ</text></svg>''',encoding='utf-8')

story_r=['COMMON','COMMON','UNCOMMON','COMMON','UNCOMMON','RARE','RARE','EPIC']
archive_r=[['UNCOMMON','RARE','EPIC','MYTHIC' if i in (2,4,7,9) else 'LEGENDARY'] for i in range(10)]
story_cards=[];archive_cards=[];nodes=[];lessons={};quizzes={};pools=[];acquisition={};stories={};relations=[];card_points={};map_chapters={};rel_i=1

for ci,ch in enumerate(CHAPTERS,1):
 ch_id=f'ASB_CHAPTER_{ci:02d}';story_ids=[];arch_ids=[]
 for ti,t in enumerate(ch['story'],1):
  cid=f'ASB_S_{ci:02d}_{ti:02d}';story_ids.append(cid);title,original,typ,subtitle,date,point=t;coord,label=P[point]
  card={'id':cid,'type':typ,'title':title,'original':original,'subtitle':subtitle,'era':'Железный век','region':'Месопотамия, Анатолия и Левант','date':date,'rarity':story_r[ti-1],'difficulty':7+min(2,ci//4),'summary':f'{title} — {subtitle}.','importance':f'Карточка раскрывает главу «{ch["title"]}» и показывает устройство ассирийской или нововавилонской власти без сведения истории к одной войне или одному царю.','facts':[f'Датировка: {date}.',f'Основной смысл: {subtitle}.','Вывод проверяется по царским текстам, административным документам, археологии и региональному сравнению.'],'tags':['железный век','Ассирия и Вавилон',ch['title'],typ.lower()],'stats':{'influence':6+(ci+ti)%4,'complexity':6+(ti%4),'legacy':6+(ci%4),'military':3+((ci+ti*2)%7),'culture':4+((ci+ti)%6),'politics':5+((ci*2+ti)%5),'religion':2+((ci+ti)%6),'economy':4+((ci+ti)%6),'connections':7+((ci+ti)%3)},'loc':{'label':label,'lat':coord[0],'lon':coord[1]},'image':{'local':f'assets/cards/assyria-babylon/chapter-{ci:02d}/{cid.lower()}.svg','caption':f'Локальная учебная обложка: {title}','credit':'Codex of History · локальная учебная обложка','source_url':ch['source']['url'],'license':'Project asset','focus':'50% 50%','file':f'{cid.lower()}.svg','kind':'project-cover'},'source':ch['source'],'acquisition':'STORY','campaign':'ASSYRIA_BABYLON','chapter':ch_id}
  story_cards.append(card);card_points[cid]=point;svg_card(Path(card['image']['local']),title,subtitle,ci,ti,'story')
 for ti,t in enumerate(ch['archive'],1):
  cid=f'ASB_A_{ci:02d}_{ti:02d}';arch_ids.append(cid);title,original,typ,subtitle,date,point=t;coord,label=P[point]
  card={'id':cid,'type':typ,'title':title,'original':original,'subtitle':subtitle,'era':'Железный век','region':'Месопотамия, Анатолия и Левант','date':date,'rarity':archive_r[ci-1][ti-1],'difficulty':7+min(2,ci//4),'summary':f'{title} — {subtitle}.','importance':f'Архивная карточка дополняет главу «{ch["title"]}» отдельным документом, памятником или историографической проблемой.','facts':[f'Датировка: {date}.',f'Связь с темой: {subtitle}.','Надёжность вывода зависит от происхождения, жанра, археологического контекста и сопоставления с другими свидетельствами.'],'tags':['железный век','архив Ассирии и Вавилона',ch['title'],typ.lower()],'stats':{'influence':5+(ci+ti)%5,'complexity':7+(ti%3),'legacy':6+(ci%4),'military':3+((ci+ti)%6),'culture':4+((ci+ti*2)%6),'politics':4+((ci*2+ti)%6),'religion':2+((ci+ti)%5),'economy':4+((ci+ti)%6),'connections':7+((ci+ti)%3)},'loc':{'label':label,'lat':coord[0],'lon':coord[1]},'image':{'local':f'assets/cards/assyria-babylon/chapter-{ci:02d}/{cid.lower()}.svg','caption':f'Локальная учебная обложка: {title}','credit':'Codex of History · локальная учебная обложка','source_url':ch['source']['url'],'license':'Project asset','focus':'50% 50%','file':f'{cid.lower()}.svg','kind':'project-cover'},'source':ch['source'],'acquisition':'ARCHIVE','campaign':'ASSYRIA_BABYLON','chapter':ch_id}
  archive_cards.append(card);card_points[cid]=point;svg_card(Path(card['image']['local']),title,subtitle,ci,ti,'archive');acquisition[cid]={'kind':'ARCHIVE','pool':f'ASB_POOL_{ci:02d}','campaign':'ASSYRIA_BABYLON'}
 pools.append({'id':f'ASB_POOL_{ci:02d}','campaign':'ASSYRIA_BABYLON','title':ch['title'],'unlockMission':f'ASB_{ci:02d}_02','cardIds':arch_ids})
 stories[f'STORY_ASB_{ci:02d}']={'id':f'STORY_ASB_{ci:02d}','cardId':arch_ids[-1],'title':f'Архивное дело: {ch["archive"][-1][0]}','subtitle':ch['title'],'rewardXp':145+ci*5,'rewardFragments':16+ci,'steps':[{'type':'SCENE','title':'Материал архива','text':f'Материал «{ch["archive"][-1][0]}» изучается отдельно. Нужно определить происхождение, дату, жанр, политическую задачу и пределы вывода.'},{'type':'QUESTION','title':'Проверка источника','question':'Какой шаг должен быть первым?','options':['Определить происхождение, датировку, жанр и адресата','Принять царскую надпись за нейтральный отчёт','Свести устройство империи к жестокости','Игнорировать археологический контекст'],'correct':0,'explanation':'Источник становится полезным после проверки контекста и цели.'},{'type':'QUESTION','title':'Граница вывода','question':'Как оформить итог?','options':['Разделить прямое свидетельство, реконструкцию и степень уверенности','Назвать спорную версию доказанным фактом','Не сравнивать документы разных сторон','Считать изображение полной фотографией события'],'correct':0,'explanation':'Корректная реконструкция показывает, где заканчивается наблюдение и начинается интерпретация.'}]}
 for i in range(7):
  relations.append({'id':f'REL_ASB_{rel_i:04d}','source':story_ids[i],'target':story_ids[i+1],'type':'СВЯЗАНО_В_ГЛАВЕ','description':f'{ch["story"][i][0]} связан с темой «{ch["story"][i+1][0]}» внутри главы «{ch["title"]}».','strength':7});rel_i+=1
 for i,a in enumerate(arch_ids):
  relations.append({'id':f'REL_ASB_{rel_i:04d}','source':a,'target':story_ids[min(i*2,7)],'type':'АРХИВНЫЙ_КОНТЕКСТ','description':f'{ch["archive"][i][0]} дополняет сюжетную тему «{ch["story"][min(i*2,7)][0]}».','strength':6});rel_i+=1
 mission_titles=[f'Рассказ: {ch["title"]}',f'Хронология: {ch["period"]}',f'Источник: {ch["archive"][0][0]}',f'Карта: {P[ch["locations"][0]][1]}, {P[ch["locations"][1]][1]} и {P[ch["locations"][2]][1]}','Разбор: власть, ресурсы и последствия',('Экзамен: Ассирия и Нововавилонское царство' if ci==10 else f'Итог главы: {ch["title"]}')]
 mtypes=['LESSON','TIMELINE','SOURCE','MAP','CAUSE_EFFECT','FINAL'];emojis=['▤','◷','▥','⌖','◆','◎'];card_plan=[[0,1,2],[2,3,4],[3,4,5],[1,5,6],[0,6,7],[7,0,3]];unlock_plan=[[0,1],[2],[3,4],[5],[6],[7]]
 for mi in range(1,7):
  mid=f'ASB_{ci:02d}_{mi:02d}';topic=ch['story'][min(mi-1,7)];node={'id':mid,'type':mtypes[mi-1],'title':mission_titles[mi-1],'description':f'{ch["description"]} Фокус миссии: {mission_titles[mi-1]}.','cards':[story_ids[x] for x in card_plan[mi-1]],'unlockCards':[story_ids[x] for x in unlock_plan[mi-1]],'xp':200+ci*7+mi*5,'emoji':emojis[mi-1],'chapterId':ch_id,'lessonId':mid}
  if mi==2:node['timeline']=[{'id':f't{x}','date':d,'title':t} for x,(d,t,_) in enumerate(ch['chronology'])]
  if mi==4:node['mapTargets']=[{'key':key.lower(),'label':P[key][1],'point':key,'zoom':6 if key in ('MESOPOTAMIA','LEVANT','ZAGROS') else 8,'radius':80000} for key in ch['locations']]
  if mi==6:
   node['quiz']=f'QUIZ_ASB_CH{ci}'
   if ci==10:node['campaignExamModules']=[{'id':'QUIZ_ASB_EXAM_MAP','title':'Карта столиц, провинций и войн','icon':'⌖'},{'id':'QUIZ_ASB_EXAM_TIME','title':'Хронология 1100–539 годов','icon':'◷'},{'id':'QUIZ_ASB_EXAM_STATE','title':'Имперская машина и армия','icon':'♜'},{'id':'QUIZ_ASB_EXAM_SOURCE','title':'Анналы, рельефы и архивы','icon':'▥'}]
  nodes.append(node)
  activity={'type':'choice','prompt':f'Какой вывод точнее описывает миссию «{mission_titles[mi-1]}»?','options':[ch['subtitle'],'Ассирия победила только из-за железа','Царские рельефы являются нейтральной хроникой','Все завоёванные общества исчезали'],'correct':0,'explanation':ch['description']}
  if mi==2:activity={'type':'timeline'}
  if mi==3:activity={'type':'source','prompt':f'Как нужно работать с материалом «{ch["archive"][0][0]}»?','options':['Проверить происхождение, дату, жанр, адресата и политическую задачу','Считать царский текст полной хроникой','Игнорировать археологию','Перенести один эпизод на всю империю'],'correct':0,'explanation':'Ассирийские и вавилонские источники создавались в конкретных административных и идеологических условиях.'}
  if mi==4:activity={'type':'map'}
  if mi==5:activity={'type':'cause-effect'}
  if mi==6:activity={'type':'quiz','quizId':f'QUIZ_ASB_CH{ci}'}
  paras=[
   f'Глава «{ch["title"]}» рассматривает государство как систему, в которой военная сила зависела от дорог, налогов, чиновников, городов и письменного управления. {ch["description"]} Тема «{topic[0]}» привязывается к конкретному месту, диапазону дат и типу источника.',
   f'Основной материал миссии — {topic[0].lower()}: {topic[3]}. Царские анналы перечисляют походы и дань, но строят идеальный образ правителя. Административные письма показывают тревоги, задержки, нехватку людей и локальные конфликты. Археология фиксирует здания, разрушения и предметы, но не всегда раскрывает мотивы решений.',
   f'Хронология главы включает {ch["chronology"][0][0]}, {ch["chronology"][1][0]}, {ch["chronology"][2][0]} и {ch["chronology"][3][0]}. Даты царствований и крупных войн часто известны хорошо благодаря спискам эпонимов и хроникам, однако отдельные эпизоды могут иметь конкурирующие версии или разную последовательность в источниках.',
   f'География включает {P[ch["locations"][0]][1]}, {P[ch["locations"][1]][1]} и {P[ch["locations"][2]][1]}. Расстояние между столицей, провинцией и фронтиром влияло на скорость приказов, снабжение армии и риск восстания. Контроль дороги не равен полному контролю всего населения вокруг неё.',
   f'Причины главы: {ch["causes"][0].lower()}, {ch["causes"][1].lower()} и {ch["causes"][2].lower()}. Следствия: {ch["consequences"][0].lower()}, {ch["consequences"][1].lower()} и {ch["consequences"][2].lower()}. Империя росла через сочетание прямой аннексии, вассальных отношений, дани и принудительного переселения.',
   'Ассирийская жестокость хорошо представлена в царской риторике и рельефах. Эти свидетельства нельзя отрицать, но их задача состояла и в устрашении. Реальное управление включало переговоры, договоры, назначение местных элит, строительные проекты и интеграцию специалистов из покорённых регионов.',
   'Депортация не была простым уничтожением населения. Людей переселяли группами, распределяли по провинциям и использовали как земледельцев, ремесленников, военных и чиновников. Это насильственная политика с тяжёлыми последствиями, одновременно служившая экономике и контролю империи.',
   f'Итог миссии опирается на источник «{ch["source"]["title"]}». Ответ должен разделять то, что прямо сказано или показано, и то, что реконструируется через сравнение. Отдельно указываются политическая задача источника, археологический контекст и возможные альтернативные объяснения.'
  ]
  lessons[mid]={'id':mid,'title':mission_titles[mi-1],'duration':13,'objectives':[f'объяснить роль темы «{topic[0]}» в главе «{ch["title"]}»','различить царскую идеологию, административный документ и археологический контекст','связать управление, военную силу, ресурсы и региональные последствия'],'story':[{'title':ch['title'],'text':ch['description']},{'title':'Фокус миссии','text':f'{mission_titles[mi-1]}. Главный материал: {topic[0]} — {topic[3]}.'},{'title':'Граница знания','text':'Царская надпись, дворцовый рельеф и археологический слой отвечают на разные вопросы и не заменяют друг друга.'}],'chronology':[{'date':d,'title':t,'note':f'{t}. Связь с миссией проверяется по месту, датировке, жанру и политической задаче источника.','certainty':c} for d,t,c in ch['chronology']],'concepts':[{'term':x[0],'definition':x[3]} for x in ch['story'][:3]],'causeEffect':{'causes':ch['causes'],'consequences':ch['consequences']},'activity':activity,'sources':[ch['source']],'theory':{'title':mission_titles[mi-1],'readingMinutes':9,'lead':f'{ch["description"]} Основной вопрос миссии — {topic[0].lower()}.','paragraphs':paras,'historicityNotes':['Царские анналы создают идеальный образ непрерывной победы.','Дворцовый рельеф является источником и политическим высказыванием одновременно.','Депортация известна по царским текстам и административным данным, но точные масштабы обсуждаются.','Падение Ассирии было процессом нескольких войн и внутренних кризисов, а не одним событием.'],'sources':[ch['source']],'license':'Авторский учебный текст Codex of History.','checkedAt':CHECKED}}
 map_chapters[ch_id]={'title':ch['title'],'center':P[ch['locations'][0]][0],'zoom':5}
 qs=[]
 for qi in range(4):
  correct=ch['story'][qi][0];distr=[ch['story'][(qi+j+1)%8][0] for j in range(3)];pos=(ci+qi)%4;opts=distr[:];opts.insert(pos,correct);qs.append({'text':f'Какой термин соответствует описанию: «{ch["story"][qi][3]}»?','options':opts,'correct':pos,'explanation':f'{correct}: {ch["story"][qi][3]}.'})
 pos=(ci+4)%4;opts=['Принять царскую надпись за полный отчёт','Объяснить расширение только железным оружием','Игнорировать провинциальные документы'];opts.insert(pos,'Сопоставить царские тексты, административные записи, карту и археологию');qs.append({'text':f'Какой метод нужен в главе «{ch["title"]}»?','options':opts,'correct':pos,'explanation':'История империи восстанавливается через несколько независимых типов данных.'})
 pos=(ci+5)%4;opts=['Все регионы управлялись одинаково','Империя держалась только на страхе','Каждая депортация уничтожала весь народ'];opts.insert(pos,ch['subtitle']);qs.append({'text':f'Какой итог главы «{ch["title"]}» наиболее точен?','options':opts,'correct':pos,'explanation':ch['description']})
 quizzes[f'QUIZ_ASB_CH{ci}']={'id':f'QUIZ_ASB_CH{ci}','title':f'Глава {ci}: {ch["title"]}','passPercent':70,'questions':qs}

chapters=[{'id':f'ASB_CHAPTER_{i:02d}','number':i,'title':ch['title'],'subtitle':ch['subtitle'],'description':ch['description'],'missionIds':[f'ASB_{i:02d}_{x:02d}' for x in range(1,7)]} for i,ch in enumerate(CHAPTERS,1)]
for source,target,desc in [
 ('COL_S_09_02','ASB_S_01_01','Ассирийская устойчивость после бронзового кризиса открывает кампанию железного века.'),
 ('BAB_S_07_01','ASB_S_01_03','Город Ашшур связывает староассирийскую торговую традицию с поздней империей.'),
 ('COL_S_10_08','ASB_S_01_08','Региональная перестройка после 1200 года продолжается политической мозаикой железного века.'),
 ('BRZ_S_08_02','ASB_S_04_01','Сравнение дворцовых систем продолжается провинциальной машиной Ассирии.'),
 ('BRZ_S_05_03','ASB_S_05_08','Общий экзамен бронзового века предупреждает против технологического упрощения войн.'),
 ('HIT_S_10_05','ASB_S_06_08','Урарту и постхеттская Анатолия становятся северным фронтиром Ассирии.'),
 ('BRZ_S_07_06','ASB_S_09_08','Переход от бронзового кризиса к железному веку завершается падением новой империи.'),
 ('BAB_S_04_01','ASB_S_10_01','Старовавилонская традиция соединена с Нововавилонским царством через город и культ.')]:
 relations.append({'id':f'REL_ASB_{rel_i:04d}','source':source,'target':target,'type':'МЕЖКАМПАНИЙНАЯ_СВЯЗЬ','description':desc,'strength':9});rel_i+=1

exam_specs={
'QUIZ_ASB_EXAM_MAP':('Карта столиц, провинций и войн',[
 ('Какой город стал столицей Ашшурнацирапала II?',['Кальху','Вавилон','Лахиш','Тайма'],0,'Кальху, современный Нимруд, был новой столицей IX века.'),('Где Саргон II построил новую столицу?',['Ниневия','Дур-Шаррукин','Ашшур','Харран'],1,'Дур-Шаррукин был столицей Саргона II.'),('Какой город захватил Синаххериб в Иудее?',['Самария','Дамаск','Лахиш','Сузы'],2,'Осада Лахиша показана на рельефах Ниневии.'),('Какой город пал в 612 году до н. э.?',['Каркемиш','Тайма','Мемфис','Ниневия'],3,'Падение Ниневии стало главным этапом конца Ассирии.'),('Где находилась столица Нововавилонского царства?',['Вавилон','Арбела','Тушпа','Кальху'],0,'Столицей был Вавилон.')]),
'QUIZ_ASB_EXAM_TIME':('Хронология 1100–539 годов',[
 ('Что произошло раньше?',['Возрождение Ассирии в IX веке до н. э.','Падение Ниневии','Завоевание Вавилона Киром','Правление Навуходоносора II'],0,'Ранняя новоассирийская экспансия началась раньше.'),('Что относится к 701 году до н. э.?',['Падение Самарии','Поход Синаххериба и осада Лахиша','Падение Ниневии','Битва при Каркемише'],1,'Поход 701 года известен по нескольким типам источников.'),('Когда пала Ниневия?',['722 до н. э.','539 до н. э.','612 до н. э.','879 до н. э.'],2,'Ниневия была захвачена в 612 году до н. э.'),('Что завершает кампанию?',['Перестройка Кальху','Завоевание Мемфиса','Разрушение Суз','Переход Вавилона под власть Кира II'],3,'В 539 году до н. э. Вавилон вошёл в державу Ахеменидов.'),('Какой порядок верен?',['Кальху → реформы Тиглатпаласара III → Ниневия Синаххериба → падение Ассирии → Нововавилонское царство','Нововавилонское царство → Кальху → бронзовый век → Ниневия','Падение Ниневии → Ашшурнацирапал II → Саргон II → Вавилон','Кир II → Синаххериб → Ашшур-дан II → Набопаласар'],0,'Это общий хронологический маршрут кампании.')]),
'QUIZ_ASB_EXAM_STATE':('Имперская машина и армия',[
 ('Что превращало завоевание в устойчивый контроль?',['Провинции, налоги, дороги и чиновники','Только дворцовые рельефы','Только железные мечи','Один ежегодный праздник'],0,'Административная система удерживала территорию.'),('Какова была одна из задач депортаций?',['Отказ от земледелия','Перераспределение населения и специалистов внутри империи','Уничтожение всех городов','Отмена налогов'],1,'Переселение было насильственным инструментом контроля и экономики.'),('Что важнее для объяснения военных успехов?',['Один металл','Число царских титулов','Организация, логистика, инженерия и разные войска','Только конница'],2,'Технология работала внутри системы снабжения и управления.'),('Как различались вассал и провинция?',['Никак','Вассал всегда жил в Ниневии','Провинция не платила налогов','Вассальный правитель сохранял часть власти, провинцией управлял царский чиновник'],3,'Это разные уровни имперского контроля.'),('Почему арамейский язык распространился в империи?',['Он использовался в коммуникации многоязычного государства','Ассирийцы запретили клинопись сразу','На нём писали только римляне','Он был единственным храмовым языком Вавилона'],0,'Арамейский был удобен для широкого общения и письма.')]),
'QUIZ_ASB_EXAM_SOURCE':('Анналы, рельефы и архивы',[
 ('Как читать царские анналы?',['Как политический текст, сопоставляя с иными данными','Как полную нейтральную хронику','Как современную статистику','Как археологический слой'],0,'Анналы отбирают события и прославляют царя.'),('Что показывает Лахишский рельеф?',['Только карту налогов','Царскую визуальную версию осады и депортации','Полный состав населения Иудеи','Дату всех войн Синаххериба'],1,'Рельеф ценен, но имеет идеологическую задачу.'),('Чем важна библиотека Ашшурбанипала?',['В ней нет клинописи','Она состояла только из царских писем','Она сохранила большой корпус литературных, научных и ритуальных текстов','Она была построена Киром II'],2,'Библиотечный корпус содержит десятки тысяч табличек и фрагментов.'),('Что нельзя вывести только из слоя разрушения Ниневии?',['Что город пережил насилие','Примерную фазу разрушения','Археологический контекст','Единственную полную причину падения империи'],3,'Падение объясняется через сочетание войн и внутренних процессов.'),('Какой подход корректнее?',['Разделять прямое свидетельство, жанр и реконструкцию','Верить только победителю','Считать рельеф фотографией','Игнорировать документы чиновников'],0,'Исторический метод требует сравнения типов источников.')])}
for qid,(title,raw) in exam_specs.items():quizzes[qid]={'id':qid,'title':title,'passPercent':70,'questions':[{'text':a,'options':b,'correct':c,'explanation':d} for a,b,c,d in raw]}

campaign={'id':'ASSYRIA_BABYLON','title':'Ассирия и Нововавилонское царство','description':'От восстановления Ассирии после бронзового кризиса до новоассирийской империи, её падения и власти Нововавилонского царства.','difficulty':9,'chapters':chapters,'nodes':nodes,'eraLayer':{'period':'ок. 1100–539 годы до н. э.','summary':'Кампания открывает железный век через государственную машину Ассирии, её столицы, армию, архивы и переход к Нововавилонской державе.','phases':[{'id':'RECOVERY','title':'Восстановление и расширение','date':'ок. 1100–859 до н. э.','chapters':[1,2]},{'id':'EMPIRE','title':'Имперская машина','date':'IX–VIII века до н. э.','chapters':[3,4,5,6]},{'id':'LATE','title':'Столица и поздняя держава','date':'704–ок. 631 до н. э.','chapters':[7,8]},{'id':'SUCCESSION','title':'Падение и новый Вавилон','date':'626–539 до н. э.','chapters':[9,10]}]}}
pools_payload={'campaignId':'ASSYRIA_BABYLON','campaigns':{'ASSYRIA_BABYLON':{'id':'ASSYRIA_BABYLON','title':'Ассирия и Нововавилонское царство','active':True,'status':'STARTED'}},'pools':pools,'acquisition':acquisition}
map_payload={'points':{k:v[0] for k,v in P.items()},'regions':{},'cardPoints':card_points,'chapters':map_chapters,'missionCenter':[34.5,42.5],'missionZoom':5}

dump(Path('data/cards/assyria-babylon/story.json'),story_cards);dump(Path('data/cards/assyria-babylon/archive.json'),archive_cards);dump(Path('data/campaigns/assyria-babylon/campaign.json'),campaign);dump(Path('data/campaigns/assyria-babylon/pools.json'),pools_payload);dump(Path('data/lessons/assyria-babylon/campaign.json'),lessons);dump(Path('data/quizzes/assyria-babylon/campaign.json'),quizzes);dump(Path('data/stories/assyria-babylon/personal.json'),stories);dump(Path('data/maps/assyria-babylon.json'),map_payload);dump(Path('data/core/relations-v40-assyria.json'),relations);pack_svg()
print(f'generated {len(story_cards)+len(archive_cards)} cards, {len(nodes)} missions, {len(lessons)} lessons, {len(quizzes)} quizzes, {len(relations)} relations')
