#!/usr/bin/env python3
from __future__ import annotations
import json, html
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
VERSION='4.3.0'
CHECKED='2026-07-14'

S_ARCHAIC={'title':'The Metropolitan Museum of Art: Greek Art in the Archaic Period','url':'https://www.metmuseum.org/essays/greek-art-in-the-archaic-period','type':'museum'}
S_COLONIES={'title':'The Metropolitan Museum of Art: Ancient Greek Colonization and Trade','url':'https://www.metmuseum.org/essays/ancient-greek-colonization-and-trade-and-their-influence-on-greek-art','type':'museum'}
S_GEOMETRIC={'title':'The Metropolitan Museum of Art: Geometric Art in Ancient Greece','url':'https://www.metmuseum.org/essays/geometric-art-in-ancient-greece','type':'museum'}
S_ARCH={'title':'The Metropolitan Museum of Art: Architecture in Ancient Greece','url':'https://www.metmuseum.org/essays/architecture-in-ancient-greece','type':'museum'}
S_SPARTA={'title':'The Metropolitan Museum of Art: Art and Craft in Archaic Sparta','url':'https://www.metmuseum.org/essays/art-and-craft-in-archaic-sparta','type':'museum'}
S_VASE={'title':'The Metropolitan Museum of Art: Athenian Vase Painting','url':'https://www.metmuseum.org/essays/athenian-vase-painting-black-and-red-figure-techniques','type':'museum'}
S_RELIGION={'title':'The Metropolitan Museum of Art: Greek Gods and Religious Practices','url':'https://www.metmuseum.org/essays/greek-gods-and-religious-practices','type':'museum'}

P={
 'GREECE':([38.35,23.6],'Греческий мир'),'ATHENS':([37.9838,23.7275],'Афины'),'SPARTA':([37.0755,22.4297],'Спарта'),
 'CORINTH':([37.9056,22.8772],'Коринф'),'ARGOS':([37.6314,22.9422],'Аргос'),'THEBES':([38.325,23.318],'Фивы'),
 'DELPHI':([38.4824,22.5010],'Дельфы'),'OLYMPIA':([37.6386,21.6298],'Олимпия'),'ERETRIA':([38.3976,23.7939],'Эретрия'),
 'CHALCIS':([38.4635,23.6028],'Халкида'),'MILETUS':([37.5308,27.2784],'Милет'),'EPHESUS':([37.939,27.341],'Эфес'),
 'SAMOS':([37.7548,26.9778],'Самос'),'LESBOS':([39.1667,26.3333],'Лесбос'),'NAXOS':([37.1036,25.3764],'Наксос'),
 'AEGINA':([37.7467,23.4275],'Эгина'),'CORCYRA':([39.6243,19.9217],'Керкира'),'SYRACUSE':([37.0755,15.2866],'Сиракузы'),
 'CUMAE':([40.848,14.052],'Кумы'),'MASSALIA':([43.2965,5.3698],'Массалия'),'CYRENE':([32.824,21.858],'Кирена'),
 'NAUCRATIS':([30.9,30.6],'Навкратис'),'BYZANTION':([41.0082,28.9784],'Византий'),'OLBIA':([46.692,31.9],'Ольвия'),
 'SARDIS':([38.488,28.04],'Сарды'),'IONIA':([37.8,27.4],'Иония'),'MAGNA':([38.5,15.5],'Великая Греция')
}

CHAPTERS=[
{
 'title':'После микенских дворцов','subtitle':'Новые общины выросли из долгого перехода, а не из мгновенного «возрождения» Греции.','description':'После распада микенских дворцовых систем население и поселения изменились. В протогеометрический и геометрический периоды формировались новые центры, сети обмена и способы коллективной памяти.','period':'ок. 1100–800 годы до н. э.','source':S_GEOMETRIC,
 'chronology':[('ок. 1100 до н. э.','Исчезновение дворцовой администрации и линейного письма Б','archaeological'),('X–IX века до н. э.','Протогеометрическая керамика и восстановление дальних контактов','archaeological'),('IX–VIII века до н. э.','Рост поселений и региональных элит','archaeological'),('ок. 800 до н. э.','Начало устойчивой письменной и полисной среды','mixed')],
 'locations':['ATHENS','ERETRIA','ARGOS'],'causes':['Распад дворцовой экономики','Перемещение населения и изменение торговых сетей','Рост локальных общин и элит'],'consequences':['Новые формы поселений и погребений','Возобновление дальнего обмена','Подготовка среды для полисов и алфавита'],
 'story':[('Ранний железный век Греции','Early Iron Age Greece','PERIOD','переход от постдворцового мира к устойчивым общинам','ок. 1100–800 годы до н. э.','GREECE'),('Протогеометрический период','Protogeometric period','PERIOD','этап новых керамических стилей и восстановления контактов','ок. 1050–900 годы до н. э.','ATHENS'),('Геометрический период','Geometric period','PERIOD','время роста поселений, святилищ и новых институтов','ок. 900–700 годы до н. э.','ATHENS'),('Лефканди','Lefkandi','SITE','богатый центр Эвбеи с дальними связями','X–IX века до н. э.','ERETRIA'),('Дипилонская керамика','Dipylon pottery','ARTIFACT','монументальные сосуды с геометрическим декором','VIII век до н. э.','ATHENS'),('Железные орудия и оружие','Iron tools and weapons in Greece','TECHNOLOGY','распространение железа в хозяйстве и войне','XI–VIII века до н. э.','ARGOS'),('Ойкос ранней Греции','Oikos in early Greece','SYSTEM','домохозяйство как основа производства и статуса','ранний железный век','GREECE'),('Проблема «тёмных веков»','Greek Dark Ages debate','CONCEPT','спор о разрыве, преемственности и региональных различиях','современная историография','GREECE')],
 'archive':[('Геройон Лефканди','Lefkandi Heroon','BUILDING','монументальное сооружение и богатое погребение','X век до н. э.','ERETRIA'),('Дипилонская амфора','Dipylon Amphora','ARTIFACT','погребальный сосуд с многофигурной сценой','VIII век до н. э.','ATHENS'),('Протогеометрическая амфора','Protogeometric amphora','ARTIFACT','сосуд с циркульным орнаментом','X век до н. э.','ATHENS'),('Модель полного культурного разрыва','Greek Dark Age discontinuity model','CONCEPT','историографическая гипотеза о масштабах упадка','XX–XXI века','GREECE')]
},
{
 'title':'Полис и гражданская община','subtitle':'Полис был не только городом, а политическим сообществом с собственной территорией, культами и правилами.','description':'В VIII–VII веках до н. э. во многих регионах укреплялись автономные общины. Полис включал городской центр, сельскую округу, святилища, собрания и конкурирующие группы граждан.','period':'VIII–VI века до н. э.','source':S_ARCHAIC,
 'chronology':[('VIII век до н. э.','Укрепление автономных общин и городских центров','mixed'),('VII век до н. э.','Формирование публичных пространств и законов','mixed'),('VI век до н. э.','Развитие гражданских институтов и межполисной конкуренции','textual'),('ок. 500 до н. э.','Полис становится главной политической формой греческого мира','interpretive')],
 'locations':['ATHENS','CORINTH','ARGOS'],'causes':['Рост поселений и обмена','Необходимость коллективной обороны и регулирования земли','Конкуренция родовой знати и новых групп'],'consequences':['Развитие гражданской идентичности','Создание публичных институтов','Постоянные конфликты между полисами и внутри них'],
 'story':[('Полис','Polis','SYSTEM','автономная гражданская община и её территория','VIII–IV века до н. э.','GREECE'),('Агора','Agora','PLACE','пространство торговли, собраний и публичной жизни','архаическая эпоха','ATHENS'),('Акрополь','Acropolis','PLACE','укреплённый и культовый центр полиса','архаическая эпоха','ATHENS'),('Хора','Chora of a polis','REGION','сельская территория, зависевшая от городского центра','архаическая эпоха','CORINTH'),('Гражданин полиса','Citizen of a Greek polis','SOCIAL','член политического сообщества с правами и обязанностями','архаическая эпоха','GREECE'),('Народное собрание','Assembly in archaic Greece','INSTITUTION','форма коллективного обсуждения и решения','VIII–VI века до н. э.','GREECE'),('Совет знати','Aristocratic council','INSTITUTION','орган управления, связанный с влиятельными родами','архаическая эпоха','ARGOS'),('Разнообразие полисов','Diversity of Greek poleis','CONCEPT','полисы отличались институтами, масштабом и социальной структурой','современная историография','GREECE')],
 'archive':[('План архаической агоры','Archaic agora plan','SOURCE','археологическая реконструкция публичного пространства','VII–VI века до н. э.','ATHENS'),('Городская стена Коринфа','Archaic Corinth fortifications','BUILDING','укрепления крупного торгового полиса','VI век до н. э.','CORINTH'),('Посвящения гражданских общин','Civic dedications in Greek sanctuaries','SOURCE','надписи и дары от полисов и групп граждан','VII–VI века до н. э.','DELPHI'),('Проблема определения полиса','Polis definition debate','CONCEPT','спор о границах города, государства и общины','современная историография','GREECE')]
},
{
 'title':'Алфавит, Гомер и устная традиция','subtitle':'Письмо изменило способы фиксации речи, но эпос продолжал жить в исполнении и переработке.','description':'Греческий алфавит возник под сильным влиянием финикийского письма. В VIII–VII веках до н. э. он использовался в коротких надписях, а эпические поэмы связывались с длительной устной традицией.','period':'VIII–VI века до н. э.','source':S_COLONIES,
 'chronology':[('VIII век до н. э.','Ранние греческие алфавитные надписи','textual'),('конец VIII века до н. э.','Кубок Нестора и Дипилонская надпись','textual'),('VII–VI века до н. э.','Распространение региональных алфавитов','textual'),('VI век до н. э.','Фиксация и редакция эпических традиций','traditional')],
 'locations':['ATHENS','EUBOEA' if False else 'ERETRIA','LESBOS'],'causes':['Контакты с финикийскими торговцами','Потребность в записи имён, посвящений и правил','Развитие публичной поэзии и соревнований'],'consequences':['Появление региональных алфавитов','Расширение письменной коммуникации','Новая фиксация эпоса, законов и памяти'],
 'story':[('Греческий алфавит','Greek alphabet','WRITING','система письма на основе финикийского алфавита с обозначением гласных','VIII век до н. э.','ERETRIA'),('Региональные алфавиты','Epichoric alphabets','WRITING','местные варианты букв и звуковых значений','VIII–VI века до н. э.','GREECE'),('Гомерическая традиция','Homeric tradition','LITERATURE','устная и письменная среда Илиады и Одиссеи','VIII–VI века до н. э.','GREECE'),('Илиада','Iliad','TEXT','эпическая поэма о гневе Ахилла и войне у Трои','архаическая редакция','GREECE'),('Одиссея','Odyssey','TEXT','эпическая поэма о возвращении Одиссея','архаическая редакция','GREECE'),('Рапсоды','Rhapsodes','SOCIAL','исполнители эпической поэзии на праздниках','архаическая эпоха','ATHENS'),('Сапфо','Sappho','PERSON','поэтесса Лесбоса и представительница архаической лирики','конец VII–начало VI века до н. э.','LESBOS'),('Архилох','Archilochus','PERSON','поэт Пароса, связанный с ямбической и элегической традицией','VII век до н. э.','GREECE')],
 'archive':[('Кубок Нестора','Nestor Cup inscription','TEXT','ранняя стихотворная надпись на сосуде','VIII век до н. э.','MAGNA'),('Дипилонская надпись','Dipylon inscription','TEXT','одна из ранних алфавитных надписей Аттики','ок. 740 до н. э.','ATHENS'),('Финикийский алфавит','Phoenician alphabet','WRITING','система письма, повлиявшая на греческий алфавит','IX–VIII века до н. э.','GREECE'),('Гомеровский вопрос','Homeric Question','CONCEPT','спор об авторстве, устной традиции и редакции эпоса','современная историография','GREECE')]
},
{
 'title':'Святилища и общегреческие связи','subtitle':'Олимпия и Дельфы объединяли конкурирующие полисы через ритуалы, игры и публичные дары.','description':'Панэллинские святилища создавали пространство встречи разных общин. Здесь проходили состязания, работали оракулы и выставлялись дары, отражавшие богатство и соперничество полисов.','period':'VIII–VI века до н. э.','source':S_RELIGION,
 'chronology':[('традиционно 776 до н. э.','Первая датированная Олимпиада в поздней хронографии','traditional'),('VIII–VII века до н. э.','Рост святилищ Олимпии и Дельф','archaeological'),('VI век до н. э.','Расширение Пифийских игр и сокровищниц','mixed'),('конец VI века до н. э.','Святилища становятся архивом межполисной конкуренции','interpretive')],
 'locations':['OLYMPIA','DELPHI','NAXOS'],'causes':['Общие культовые традиции','Потребность в нейтральных местах встречи','Соперничество элит и полисов за престиж'],'consequences':['Формирование панэллинской идентичности','Развитие игр и оракульных центров','Создание богатых комплексов посвящений'],
 'story':[('Олимпия','Olympia','SANCTUARY','панэллинское святилище Зевса и место игр','VIII век до н. э.–IV век н. э.','OLYMPIA'),('Дельфы','Delphi','SANCTUARY','святилище Аполлона и оракульный центр','VIII век до н. э.–поздняя античность','DELPHI'),('Олимпийские игры','Ancient Olympic Games','EVENT','регулярные состязания при святилище Зевса','архаическая эпоха','OLYMPIA'),('Пифийские игры','Pythian Games','EVENT','состязания при святилище Аполлона','VI век до н. э.','DELPHI'),('Оракул Дельф','Delphic oracle','INSTITUTION','ритуальная практика получения ответов Аполлона','архаическая эпоха','DELPHI'),('Сокровищницы полисов','Treasuries at Greek sanctuaries','BUILDING','небольшие здания для даров общин','VI век до н. э.','DELPHI'),('Панэллинизм','Panhellenism','CONCEPT','общность языка, культов и состязаний без единого государства','архаическая эпоха','GREECE'),('Посвятительные дары','Greek votive offerings','ARTIFACT','предметы, статуи и оружие, переданные божеству','архаическая эпоха','OLYMPIA')],
 'archive':[('Треножники Олимпии','Olympian bronze tripods','ARTIFACT','богатые бронзовые посвящения раннего святилища','IX–VII века до н. э.','OLYMPIA'),('Сокровищница сифносцев','Siphnian Treasury','BUILDING','ионийская сокровищница с рельефами','ок. 525 до н. э.','DELPHI'),('Наксосский сфинкс','Sphinx of Naxos','ARTIFACT','монументальное посвящение островной общины','ок. 560 до н. э.','DELPHI'),('Традиционная дата 776 года','Traditional date of first Olympiad','CONCEPT','поздняя хронографическая точка отсчёта','традиционно 776 до н. э.','OLYMPIA')]
},
{
 'title':'Колонизация и средиземноморские сети','subtitle':'Новые поселения возникали через договоры, конфликты и смешение с местными обществами.','description':'С VIII века до н. э. греческие общины основали поселения в Южной Италии, Сицилии, Причерноморье, Северной Африке и западном Средиземноморье. Это не была единая государственная программа.','period':'VIII–VI века до н. э.','source':S_COLONIES,
 'chronology':[('VIII век до н. э.','Основание ранних поселений в Южной Италии и Сицилии','mixed'),('VII век до н. э.','Расширение сетей в Чёрном море и Северной Африке','mixed'),('ок. 600 до н. э.','Основание Массалии','traditional'),('VI век до н. э.','Рост торговли между колониями, метрополиями и местными обществами','archaeological')],
 'locations':['SYRACUSE','MASSALIA','OLBIA'],'causes':['Поиск земли и торговых возможностей','Политические конфликты внутри полисов','Контроль морских маршрутов и ресурсов'],'consequences':['Расширение греческой языковой среды','Смешение ремесленных и культовых практик','Рост межрегиональной торговли и конфликтов'],
 'story':[('Греческая колонизация','Greek colonization','PROCESS','основание самостоятельных поселений за пределами Эгейского мира','VIII–VI века до н. э.','MAGNA'),('Метрополия и апойкия','Metropolis and apoikia','SYSTEM','отношения города-основателя и нового самостоятельного полиса','архаическая эпоха','CORINTH'),('Ойкист','Oikist','SOCIAL','руководитель основания колонии и культовая фигура памяти','архаическая эпоха','SYRACUSE'),('Сиракузы','Syracuse','CITY','коринфское поселение, ставшее крупным полисом Сицилии','основаны традиционно в 734/733 до н. э.','SYRACUSE'),('Кумы','Cumae','CITY','один из ранних греческих центров Италии','VIII век до н. э.','CUMAE'),('Массалия','Massalia','CITY','фокейский центр на западном Средиземноморье','традиционно ок. 600 до н. э.','MASSALIA'),('Кирена','Cyrene','CITY','греческий полис Северной Африки','VII век до н. э.','CYRENE'),('Ольвия Понтийская','Olbia Pontica','CITY','полис на северном побережье Чёрного моря','VI век до н. э.','OLBIA')],
 'archive':[('Питекуссы','Pithekoussai','SITE','ранний торгово-поселенческий центр на Искье','VIII век до н. э.','CUMAE'),('Навкратис','Naucratis','CITY','греческий торговый центр в дельте Нила','VII–VI века до н. э.','NAUCRATIS'),('Керамика греков и местных обществ','Greek and indigenous pottery exchange','SOURCE','материал для изучения смешанных контактов','VIII–VI века до н. э.','MAGNA'),('Модель «Великой колонизации»','Great Greek Colonization debate','CONCEPT','спор о масштабах, терминах и участии местных обществ','современная историография','GREECE')]
},
{
 'title':'Аристократия, законы и тираны','subtitle':'Полисы искали разные способы ограничить насилие элит и перераспределить политическое влияние.','description':'В VII–VI веках до н. э. долговые конфликты, борьба родов и военная мобилизация усилили давление на старые порядки. Письменные законы и тирании были разными ответами на кризисы.','period':'VII–VI века до н. э.','source':S_ARCHAIC,
 'chronology':[('VII век до н. э.','Появление ранних письменных законов','textual'),('VII–VI века до н. э.','Тирании в Коринфе, Сикионе и других полисах','textual'),('621/620 до н. э.','Традиционная дата законов Драконта','traditional'),('VI век до н. э.','Расширение публичного регулирования и культовых программ','mixed')],
 'locations':['CORINTH','ATHENS','THEBES'],'causes':['Конкуренция аристократических родов','Долговые и земельные конфликты','Рост вооружённых и торговых групп вне старой знати'],'consequences':['Появление письменных законов','Временное усиление единоличных правителей','Перестройка публичных пространств и культов'],
 'story':[('Аристократия архаической Греции','Archaic Greek aristocracy','SOCIAL','влиятельные роды, связывавшие статус с землёй, войной и происхождением','VII–VI века до н. э.','GREECE'),('Тирания','Greek tyranny','SYSTEM','единоличная власть вне обычного порядка элитной конкуренции','VII–VI века до н. э.','CORINTH'),('Кипсел','Cypselus','PERSON','основатель тирании Кипселидов в Коринфе','VII век до н. э.','CORINTH'),('Периандр','Periander','PERSON','коринфский тиран и фигура поздней политической памяти','конец VII–начало VI века до н. э.','CORINTH'),('Законодатель','Greek lawgiver','SOCIAL','автор или символ публичного свода правил','VII–VI века до н. э.','GREECE'),('Письменный закон','Written law in archaic Greece','TEXT','публичная фиксация норм и наказаний','VII–VI века до н. э.','GREECE'),('Драконт','Draco','PERSON','афинский законодатель, связанный с суровыми наказаниями','конец VII века до н. э.','ATHENS'),('Симпосий','Greek symposium','SOCIAL','аристократическое пиршество, поэзия и политическое общение','VII–VI века до н. э.','GREECE')],
 'archive':[('Законы Дрероса','Dreros law code','TEXT','одна из ранних публичных греческих надписей','VII век до н. э.','GREECE'),('Кипселов ларец','Chest of Cypselus tradition','ARTIFACT','описанный поздними авторами памятник власти Кипселидов','традиционная датировка VII–VI века','CORINTH'),('Аристократическая лирика','Archaic aristocratic lyric poetry','TEXT','поэзия соперничества, пира и статуса','VII–VI века до н. э.','LESBOS'),('Проблема термина «тиран»','Greek tyrant terminology debate','CONCEPT','изменение значения слова от правителя к отрицательному образу','современная историография','GREECE')]
},
{
 'title':'Гоплиты и война полисов','subtitle':'Тяжёлая пехота была важна, но простая схема «фаланга создала демократию» остаётся спорной.','description':'В архаическую эпоху распространились круглые щиты, копья, шлемы и плотные построения тяжёлой пехоты. Однако изменения шли постепенно и не одинаково во всех полисах.','period':'VIII–VI века до н. э.','source':S_ARCHAIC,
 'chronology':[('VIII–VII века до н. э.','Распространение комплектов тяжёлого вооружения','archaeological'),('VII век до н. э.','Изображения плотных рядов воинов на керамике','iconographic'),('VI век до н. э.','Гоплиты становятся важной частью войск полисов','mixed'),('конец VI века до н. э.','Разные модели гражданской мобилизации сосуществуют','interpretive')],
 'locations':['ARGOS','CORINTH','SPARTA'],'causes':['Рост ресурсов землевладельцев','Необходимость обороны территории полиса','Развитие коллективной военной дисциплины'],'consequences':['Усиление тяжёлой пехоты','Новая символика гражданина-воина','Дискуссия о связи армии и политических прав'],
 'story':[('Гоплит','Hoplite','MILITARY','тяжеловооружённый пехотинец греческого полиса','VII–IV века до н. э.','ARGOS'),('Гоплон','Aspis shield','ARTIFACT','круглый щит с центральным и краевым захватом','архаическая эпоха','ARGOS'),('Коринфский шлем','Corinthian helmet','ARTIFACT','бронзовый шлем с закрытой лицевой частью','VII–VI века до н. э.','CORINTH'),('Дори','Dory spear','ARTIFACT','основное копьё тяжёлого пехотинца','архаическая эпоха','GREECE'),('Фаланга','Hoplite phalanx','MILITARY','плотное построение тяжёлой пехоты','архаическая эпоха','GREECE'),('Гражданин-воин','Citizen-soldier','CONCEPT','связь военной службы и принадлежности к полису','архаическая эпоха','GREECE'),('Аргосская военная традиция','Archaic Argive warfare','MILITARY','военная культура одного из сильных полисов Пелопоннеса','VII–VI века до н. э.','ARGOS'),('Гоплитская революция','Hoplite revolution debate','CONCEPT','спор о скорости военных перемен и их политических последствиях','современная историография','GREECE')],
 'archive':[('Ваза Киджи','Chigi Vase','ARTIFACT','раннее изображение ряда вооружённых воинов','VII век до н. э.','CORINTH'),('Аргосские панцири','Argive bronze armour','ARTIFACT','бронзовые элементы тяжёлого вооружения','VIII–VII века до н. э.','ARGOS'),('Щиты из Олимпии','Shields from Olympia','ARTIFACT','военные посвящения в святилище','VII–VI века до н. э.','OLYMPIA'),('Модель гоплитской революции','Hoplite revolution model','CONCEPT','историографическая схема связи фаланги и политических перемен','XX век','GREECE')]
},
{
 'title':'Спарта и Лакония','subtitle':'Архаическая Спарта была не только военным лагерем: она имела ремесло, поэзию, культы и сложную систему зависимости.','description':'Спарта подчинила Лаконию и Мессению, построила гражданскую общину спартиатов и систему эксплуатации илотов. Поздний образ неизменной «спартанской системы» требует проверки.','period':'VIII–VI века до н. э.','source':S_SPARTA,
 'chronology':[('VIII–VII века до н. э.','Расширение спартанского контроля в Лаконии','mixed'),('VII век до н. э.','Войны за Мессению в поздней традиции','traditional'),('VII–VI века до н. э.','Расцвет лаконских мастерских и поэзии','archaeological'),('VI век до н. э.','Спарта формирует сеть союзов Пелопоннеса','textual')],
 'locations':['SPARTA','OLYMPIA','ARGOS'],'causes':['Завоевание соседних земель','Создание гражданской военной общины','Контроль зависимого населения'],'consequences':['Формирование системы спартиатов, периэков и илотов','Сильное влияние в Пелопоннесе','Создание позднего идеализированного образа Спарты'],
 'story':[('Спарта архаической эпохи','Archaic Sparta','CITY','полис Лаконии с особой социальной системой','VIII–VI века до н. э.','SPARTA'),('Спартиаты','Spartiates','SOCIAL','полноправные граждане спартанской общины','архаическая и классическая эпохи','SPARTA'),('Периэки','Perioikoi','SOCIAL','свободные жители зависимых общин Лаконии','архаическая эпоха','SPARTA'),('Илоты','Helots','SOCIAL','зависимое население, обеспечивавшее хозяйственную основу Спарты','архаическая эпоха','SPARTA'),('Герусия','Gerousia','INSTITUTION','совет старейшин спартанского полиса','архаическая эпоха','SPARTA'),('Эфоры','Ephors','INSTITUTION','ежегодные должностные лица Спарты','архаическая эпоха','SPARTA'),('Тиртей','Tyrtaeus','PERSON','поэт, связываемый с войной и гражданской дисциплиной','VII век до н. э.','SPARTA'),('Пелопоннесский союз','Peloponnesian League','FACTION','сеть союзов вокруг Спарты','VI век до н. э.','SPARTA')],
 'archive':[('Лаконская чаша','Laconian cup','ARTIFACT','расписная керамика спартанских мастерских','VI век до н. э.','SPARTA'),('Свинцовые фигурки Орфии','Lead votives from Artemis Orthia','ARTIFACT','массовые посвящения в спартанском святилище','VII–VI века до н. э.','SPARTA'),('Большая ретра','Great Rhetra tradition','TEXT','поздняя традиция о спартанском устройстве','традиционно архаическая эпоха','SPARTA'),('Спартанский мираж','Spartan mirage','CONCEPT','идеализированный образ Спарты в поздних источниках','современная историография','SPARTA')]
},
{
 'title':'Афины: от Драконта к Клисфену','subtitle':'Афинские реформы были цепью конфликтов и компромиссов, а не прямой дорогой к готовой демократии.','description':'Долговой кризис, соперничество знати и рост Аттики привели к законам Драконта, реформам Солона, тирании Писистратидов и преобразованиям Клисфена.','period':'конец VII–конец VI века до н. э.','source':S_ARCHAIC,
 'chronology':[('621/620 до н. э.','Традиционная дата законодательства Драконта','traditional'),('594/593 до н. э.','Традиционная дата архонтства и реформ Солона','traditional'),('ок. 546–510 до н. э.','Укрепление и падение тирании Писистратидов','textual'),('508/507 до н. э.','Реформы Клисфена и новая организация граждан','textual')],
 'locations':['ATHENS','DELPHI','ERETRIA'],'causes':['Долговая зависимость и земельные конфликты','Соперничество аристократических групп','Рост населения и политической мобилизации Аттики'],'consequences':['Отмена части долговых форм зависимости','Расширение политического участия','Новая территориальная организация граждан'],
 'story':[('Солон','Solon','PERSON','афинский законодатель и поэт','начало VI века до н. э.','ATHENS'),('Сисахфия','Seisachtheia','REFORM','комплекс мер против долгового рабства граждан','традиционно 594/593 до н. э.','ATHENS'),('Имущественные разряды Солона','Solonian property classes','SYSTEM','политическая классификация по доходу','VI век до н. э.','ATHENS'),('Писистрат','Peisistratos','PERSON','афинский тиран, укрепивший власть в VI веке','ум. 527 до н. э.','ATHENS'),('Писистратиды','Peisistratids','DYNASTY','династия афинских тиранов','ок. 546–510 до н. э.','ATHENS'),('Гиппий','Hippias of Athens','PERSON','последний афинский тиран','VI век до н. э.','ATHENS'),('Клисфен','Cleisthenes','PERSON','инициатор реформ 508/507 года до н. э.','конец VI века до н. э.','ATHENS'),('Демы и филы Клисфена','Cleisthenic demes and tribes','SYSTEM','территориальная перестройка гражданской общины','508/507 до н. э.','ATHENS')],
 'archive':[('Афинская полития Аристотеля','Aristotle Constitution of the Athenians','TEXT','поздний источник о ранних афинских реформах','IV век до н. э.','ATHENS'),('Законы Солона','Solonian laws tradition','TEXT','фрагментарно сохранённая законодательная традиция','VI век до н. э.','ATHENS'),('Чёрнофигурная керамика Писистратидов','Peisistratid black-figure pottery','ARTIFACT','визуальная культура Афин VI века','VI век до н. э.','ATHENS'),('Спор о рождении демократии','Origins of Athenian democracy debate','CONCEPT','оценка роли Солона, тирании и Клисфена','современная историография','ATHENS')]
},
{
 'title':'Архаическое искусство и граница классической эпохи','subtitle':'Куросы, коры, храмы и вазопись показывают общий язык форм при сильных региональных различиях.','description':'В VII–VI веках до н. э. греческие мастера перерабатывали египетские и ближневосточные влияния. Дорический и ионический ордера, монументальная скульптура и вазопись стали важными средствами полисного и культового представления.','period':'VII–480 год до н. э.','source':S_ARCHAIC,
 'chronology':[('VII век до н. э.','Ориентализирующие мотивы и крупная каменная скульптура','art-historical'),('начало VI века до н. э.','Утверждение дорического и ионического ордеров','art-historical'),('VI век до н. э.','Расцвет куросов, кор и чёрнофигурной вазописи','art-historical'),('ок. 480 до н. э.','Переход к раннеклассическим формам','art-historical')],
 'locations':['NAXOS','SAMOS','ATHENS'],'causes':['Контакты с Египтом и Ближним Востоком','Соперничество полисов и элит в посвящениях','Рост храмового строительства и мастерских'],'consequences':['Формирование региональных художественных школ','Закрепление архитектурных ордеров','Новый визуальный язык тела, мифа и гражданской памяти'],
 'story':[('Курос','Kouros','ARTIFACT','стоящая статуя обнажённого юноши','VII–VI века до н. э.','NAXOS'),('Кора','Kore statue','ARTIFACT','стоящая статуя одетой девушки','VI век до н. э.','ATHENS'),('Архаическая улыбка','Archaic smile','CONCEPT','условный приём изображения лица в скульптуре','VI век до н. э.','GREECE'),('Дорический ордер','Doric order','ARCHITECTURE','архитектурная система материковой Греции и Запада','VI век до н. э.','CORINTH'),('Ионический ордер','Ionic order','ARCHITECTURE','архитектурная система Восточной Греции и островов','VI век до н. э.','SAMOS'),('Чёрнофигурная вазопись','Black-figure pottery','ART','техника силуэтных фигур с процарапанными деталями','VII–VI века до н. э.','ATHENS'),('Краснофигурная вазопись','Red-figure pottery','ART','техника, появившаяся в Афинах около 530 года','конец VI века до н. э.','ATHENS'),('Ионийские города и Персия','Ionian Greeks under Persian rule','PROCESS','включение городов Малой Азии в державу Ахеменидов','VI век до н. э.','IONIA')],
 'archive':[('Курос Метрополитен-музея','Metropolitan Museum Kouros','ARTIFACT','ранняя монументальная статуя с египетским влиянием','ок. 590–580 до н. э.','GREECE'),('Герайон Самоса','Heraion of Samos','SANCTUARY','ионийское святилище с крупными храмами','VI век до н. э.','SAMOS'),('Храм Аполлона в Коринфе','Temple of Apollo at Corinth','BUILDING','ранний пример дорической архитектуры','ок. 540 до н. э.','CORINTH'),('Граница 480 года','Archaic-Classical transition','CONCEPT','условная граница между архаической и классической эпохами','ок. 480 до н. э.','GREECE')]
}
]


def dump(path,obj):
 p=ROOT/path;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

def svg_card(path,title,subtitle,chapter,index,kind):
 p=ROOT/path;p.parent.mkdir(parents=True,exist_ok=True);title=html.escape(title);subtitle=html.escape(subtitle)
 marks=['◇','Π','Α','✦','≋','⚖','⚔','Λ','ΑΘ','Κ'];acc=['#b68a55','#8f7655','#c0a066','#7a8d7a','#7890a3','#ad7458','#9f6b51','#877455','#b59b67','#8c745a'][chapter-1]
 p.write_text(f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 720 900" role="img" aria-label="{title}"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="#080909"/><stop offset=".58" stop-color="#20201c"/><stop offset="1" stop-color="#080706"/></linearGradient><radialGradient id="r"><stop stop-color="{acc}" stop-opacity=".58"/><stop offset="1" stop-color="{acc}" stop-opacity="0"/></radialGradient></defs><rect width="720" height="900" fill="url(#g)"/><circle cx="530" cy="210" r="310" fill="url(#r)"/><path d="M0 635 C140 575 245 690 370 615 S590 565 720 655 V900 H0Z" fill="#050605" opacity=".96"/><path d="M62 112 H658 M62 790 H658" stroke="{acc}" stroke-width="2"/><path d="M225 560 H500 M270 560 V430 H455 V560 M250 430 H475" fill="none" stroke="{acc}" stroke-width="9" opacity=".3"/><text x="565" y="370" text-anchor="middle" fill="{acc}" font-size="128" font-family="serif">{marks[chapter-1]}</text><text x="62" y="82" fill="{acc}" font-size="19" font-family="Arial" letter-spacing="4">IRON AGE · ARCHAIC GREECE · {chapter:02d}</text><text x="62" y="654" fill="#fff8e9" font-size="39" font-family="Georgia">{title[:31]}</text><text x="62" y="710" fill="#d8d0c2" font-size="22" font-family="Arial">{subtitle[:54]}</text><text x="62" y="832" fill="{acc}" font-size="18" font-family="Arial" letter-spacing="3">{kind.upper()} · CODEX OF HISTORY · {index:02d}</text></svg>''',encoding='utf-8')

def pack_svg():
 p=ROOT/'assets/packs/archaic-greece-pack.svg';p.parent.mkdir(parents=True,exist_ok=True)
 p.write_text('''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 720 960"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="#080908"/><stop offset=".58" stop-color="#29271f"/><stop offset="1" stop-color="#080706"/></linearGradient><radialGradient id="r"><stop stop-color="#c3a16a" stop-opacity=".62"/><stop offset="1" stop-color="#c3a16a" stop-opacity="0"/></radialGradient></defs><rect width="720" height="960" rx="58" fill="url(#g)"/><circle cx="500" cy="250" r="360" fill="url(#r)"/><path d="M180 590 H540 M235 590 V365 H485 V590 M205 365 H515" fill="none" stroke="#c3a16a" stroke-width="15" opacity=".72"/><path d="M120 690 H600" stroke="#778b86" stroke-width="10" opacity=".55"/><text x="80" y="120" fill="#c3a16a" font-size="22" font-family="Arial" letter-spacing="5">ЖЕЛЕЗНЫЙ ВЕК</text><text x="80" y="760" fill="#fff7e4" font-size="55" font-family="Georgia">Архив полисов</text><text x="80" y="825" fill="#d9cbb5" font-size="27" font-family="Arial">Архаическая Греция и Средиземноморье</text><text x="80" y="905" fill="#c3a16a" font-size="21" font-family="Arial" letter-spacing="4">4 КАРТЫ · ОТКРЫТЫЕ ГЛАВЫ</text></svg>''',encoding='utf-8')

story_r=['COMMON','COMMON','UNCOMMON','COMMON','UNCOMMON','RARE','RARE','EPIC']
archive_r=[['UNCOMMON','RARE','EPIC','MYTHIC' if i in (0,3,4,8) else 'LEGENDARY'] for i in range(10)]
story_cards=[];archive_cards=[];nodes=[];lessons={};quizzes={};pools=[];acquisition={};stories={};relations=[];card_points={};map_chapters={};rel_i=1

for ci,ch in enumerate(CHAPTERS,1):
 ch_id=f'ARC_CHAPTER_{ci:02d}';story_ids=[];arch_ids=[]
 for ti,t in enumerate(ch['story'],1):
  cid=f'ARC_S_{ci:02d}_{ti:02d}';story_ids.append(cid);title,original,typ,subtitle,date,point=t;coord,label=P[point]
  c={'id':cid,'type':typ,'title':title,'original':original,'subtitle':subtitle,'era':'Железный век','region':'Греческий мир','date':date,'rarity':story_r[ti-1],'difficulty':7+min(2,ci//4),'summary':f'{title} — {subtitle}.','importance':f'Карточка раскрывает главу «{ch["title"]}» и показывает политическую, социальную, военную или культурную сторону архаической Греции.','facts':[f'Датировка: {date}.',f'Основной смысл: {subtitle}.','Вывод проверяется по археологии, надписям, изображениям и поздней письменной традиции.'],'tags':['железный век','архаическая Греция',ch['title'],typ.lower()],'stats':{'influence':6+(ci+ti)%4,'complexity':5+(ti%5),'legacy':6+(ci%4),'military':3+((ci+ti)%6),'culture':6+((ci+ti)%4),'politics':5+((ci*2+ti)%5),'religion':3+((ci+ti)%6),'economy':4+((ci+ti)%5),'connections':8+((ci+ti)%2)},'loc':{'label':label,'lat':coord[0],'lon':coord[1]},'image':{'local':f'assets/cards/archaic-greece/chapter-{ci:02d}/{cid.lower()}.svg','caption':f'Локальная учебная обложка: {title}','credit':'Codex of History · локальная учебная обложка','source_url':ch['source']['url'],'license':'Project asset','focus':'50% 50%','file':f'{cid.lower()}.svg','kind':'project-cover'},'source':ch['source'],'acquisition':'STORY','campaign':'GREECE_ARCHAIC','chapter':ch_id}
  story_cards.append(c);card_points[cid]=point;svg_card(Path(c['image']['local']),title,subtitle,ci,ti,'story')
 for ti,t in enumerate(ch['archive'],1):
  cid=f'ARC_A_{ci:02d}_{ti:02d}';arch_ids.append(cid);title,original,typ,subtitle,date,point=t;coord,label=P[point]
  c={'id':cid,'type':typ,'title':title,'original':original,'subtitle':subtitle,'era':'Железный век','region':'Греческий мир','date':date,'rarity':archive_r[ci-1][ti-1],'difficulty':7+min(2,ci//4),'summary':f'{title} — {subtitle}.','importance':f'Архивная карточка дополняет главу «{ch["title"]}» отдельным памятником, текстом или спором историков.','facts':[f'Датировка: {date}.',f'Связь с темой: {subtitle}.','Надёжность вывода зависит от происхождения, слоя, жанра, сохранности и сопоставления с другими источниками.'],'tags':['железный век','архив полисов',ch['title'],typ.lower()],'stats':{'influence':5+(ci+ti)%5,'complexity':7+(ti%3),'legacy':6+(ci%4),'military':2+((ci+ti)%6),'culture':6+((ci+ti*2)%4),'politics':4+((ci*2+ti)%6),'religion':4+((ci+ti)%5),'economy':4+((ci+ti)%5),'connections':7+((ci+ti)%3)},'loc':{'label':label,'lat':coord[0],'lon':coord[1]},'image':{'local':f'assets/cards/archaic-greece/chapter-{ci:02d}/{cid.lower()}.svg','caption':f'Локальная учебная обложка: {title}','credit':'Codex of History · локальная учебная обложка','source_url':ch['source']['url'],'license':'Project asset','focus':'50% 50%','file':f'{cid.lower()}.svg','kind':'project-cover'},'source':ch['source'],'acquisition':'ARCHIVE','campaign':'GREECE_ARCHAIC','chapter':ch_id}
  archive_cards.append(c);card_points[cid]=point;svg_card(Path(c['image']['local']),title,subtitle,ci,ti,'archive');acquisition[cid]={'kind':'ARCHIVE','pool':f'ARC_POOL_{ci:02d}','campaign':'GREECE_ARCHAIC'}
 pools.append({'id':f'ARC_POOL_{ci:02d}','campaign':'GREECE_ARCHAIC','title':ch['title'],'unlockMission':f'ARC_{ci:02d}_02','cardIds':arch_ids})
 stories[f'STORY_ARC_{ci:02d}']={'id':f'STORY_ARC_{ci:02d}','cardId':arch_ids[-1],'title':f'Архивное дело: {ch["archive"][-1][0]}','subtitle':ch['title'],'rewardXp':145+ci*5,'rewardFragments':16+ci,'steps':[{'type':'SCENE','title':'Материал архива','text':f'Материал «{ch["archive"][-1][0]}» требует проверки происхождения, даты, жанра и степени сохранности.'},{'type':'QUESTION','title':'Проверка источника','question':'Какой шаг должен быть первым?','options':['Определить происхождение, датировку, жанр и археологический контекст','Принять позднюю литературную традицию как точную стенограмму','Выбрать только красивое изображение','Игнорировать региональные различия'],'correct':0,'explanation':'Источники архаической Греции относятся к разным регионам и периодам.'},{'type':'QUESTION','title':'Граница вывода','question':'Как оформить итог?','options':['Разделить прямое свидетельство, реконструкцию и степень уверенности','Свести всю Грецию к Афинам','Объявить любую традиционную дату точной','Не показывать научные споры'],'correct':0,'explanation':'Корректный вывод показывает, что известно прямо, а что восстановлено.'}]}
 for i in range(7):
  relations.append({'id':f'REL_ARC_{rel_i:04d}','source':story_ids[i],'target':story_ids[i+1],'type':'СВЯЗАНО_В_ГЛАВЕ','description':f'{ch["story"][i][0]} связан с темой «{ch["story"][i+1][0]}» внутри главы «{ch["title"]}».','strength':7});rel_i+=1
 for i,a in enumerate(arch_ids):
  relations.append({'id':f'REL_ARC_{rel_i:04d}','source':a,'target':story_ids[min(i*2,7)],'type':'АРХИВНЫЙ_КОНТЕКСТ','description':f'{ch["archive"][i][0]} дополняет сюжетную тему «{ch["story"][min(i*2,7)][0]}».','strength':6});rel_i+=1
 mission_titles=[f'Рассказ: {ch["title"]}',f'Хронология: {ch["period"]}',f'Источник: {ch["archive"][0][0]}',f'Карта: {P[ch["locations"][0]][1]}, {P[ch["locations"][1]][1]} и {P[ch["locations"][2]][1]}','Разбор: общество, институты и последствия',('Экзамен: Архаическая Греция' if ci==10 else f'Итог главы: {ch["title"]}')]
 mtypes=['LESSON','TIMELINE','SOURCE','MAP','CAUSE_EFFECT','FINAL'];emojis=['▤','◷','▥','⌖','◆','◎'];card_plan=[[0,1,2],[2,3,4],[3,4,5],[1,5,6],[0,6,7],[7,0,3]];unlock_plan=[[0,1],[2],[3,4],[5],[6],[7]]
 for mi in range(1,7):
  mid=f'ARC_{ci:02d}_{mi:02d}';topic=ch['story'][min(mi-1,7)]
  node={'id':mid,'type':mtypes[mi-1],'title':mission_titles[mi-1],'description':f'{ch["description"]} Фокус миссии: {mission_titles[mi-1]}.','cards':[story_ids[x] for x in card_plan[mi-1]],'unlockCards':[story_ids[x] for x in unlock_plan[mi-1]],'xp':200+ci*7+mi*5,'emoji':emojis[mi-1],'chapterId':ch_id,'lessonId':mid}
  if mi==2:node['timeline']=[{'id':f't{x}','date':d,'title':t} for x,(d,t,_) in enumerate(ch['chronology'])]
  if mi==4:node['mapTargets']=[{'key':key.lower(),'label':P[key][1],'point':key,'zoom':7 if key in ('GREECE','MAGNA','IONIA') else 9,'radius':70000} for key in ch['locations']]
  if mi==6:
   node['quiz']=f'QUIZ_ARC_CH{ci}'
   if ci==10:node['campaignExamModules']=[{'id':'QUIZ_ARC_EXAM_MAP','title':'Карта полисов и колоний','icon':'⌖'},{'id':'QUIZ_ARC_EXAM_TIME','title':'Хронология 1100–480 годов','icon':'◷'},{'id':'QUIZ_ARC_EXAM_STATE','title':'Полисы, реформы и общество','icon':'Π'},{'id':'QUIZ_ARC_EXAM_SOURCE','title':'Археология, надписи и традиция','icon':'▥'}]
  nodes.append(node)
  activity={'type':'choice','prompt':f'Какой вывод точнее описывает миссию «{mission_titles[mi-1]}»?','options':[ch['subtitle'],'Все греческие полисы имели одинаковое устройство','Поздний автор полностью заменяет археологию','Архаическая Греция была единым государством'],'correct':0,'explanation':ch['description']}
  if mi==2:activity={'type':'timeline'}
  if mi==3:activity={'type':'source','prompt':f'Как нужно работать с материалом «{ch["archive"][0][0]}»?','options':['Проверить происхождение, дату, функцию, жанр и региональный контекст','Считать вазопись фотографией события','Игнорировать археологический слой','Переносить афинские институты на все полисы'],'correct':0,'explanation':'История архаической Греции восстанавливается через сопоставление археологии, надписей, изображений и поздних текстов.'}
  if mi==4:activity={'type':'map'}
  if mi==5:activity={'type':'cause-effect'}
  if mi==6:activity={'type':'quiz','quizId':f'QUIZ_ARC_CH{ci}'}
  paras=[
   f'Глава «{ch["title"]}» рассматривает греческий мир как сеть самостоятельных общин. {ch["description"]} Тема «{topic[0]}» связывается с конкретной местностью, диапазоном дат и набором источников.',
   f'Основной материал миссии — {topic[0].lower()}: {topic[3]}. Археологический предмет показывает технологию, ритуал или обмен, но не всегда сообщает точное политическое значение.',
   f'Хронология главы включает {ch["chronology"][0][0]}, {ch["chronology"][1][0]}, {ch["chronology"][2][0]} и {ch["chronology"][3][0]}. Традиционные даты и поздние биографии отмечаются отдельно от археологической датировки.',
   f'География включает {P[ch["locations"][0]][1]}, {P[ch["locations"][1]][1]} и {P[ch["locations"][2]][1]}. Горы, острова и морские маршруты усиливали региональное разнообразие и контакты между общинами.',
   f'Причины главы: {ch["causes"][0].lower()}, {ch["causes"][1].lower()} и {ch["causes"][2].lower()}. Следствия: {ch["consequences"][0].lower()}, {ch["consequences"][1].lower()} и {ch["consequences"][2].lower()}.',
   'Греческая литературная традиция часто записана позже описываемых событий. Она важна для памяти и политических моделей, но требует сопоставления с надписями, керамикой, архитектурой и погребениями.',
   'Полис не был единым стандартом. Афины, Спарта, Коринф, островные и западные общины развивали разные институты, а права граждан не включали всё население.',
   f'Итог миссии опирается на источник «{ch["source"]["title"]}». Ответ должен разделять археологический факт, древнее утверждение, позднюю традицию и современную интерпретацию.',
   'Социальная структура архаической эпохи не сводилась к гражданам и правителям. В полисах жили женщины, зависимые работники, рабы, переселенцы и жители сельской округи, чьи права и обязанности различались. Даже внутри группы граждан богатство, происхождение и военная роль создавали сильное неравенство. Поэтому политическую реформу нельзя автоматически считать изменением положения всего населения.',
   'Региональные различия важны для любой реконструкции. Археологический материал Аттики нельзя без проверки переносить на Спарту, Ионию, острова или западные поселения. Общий язык, культы и состязания связывали грекоязычные общины, но не создавали единого государства. Исторический вывод должен сохранять одновременно общие процессы и локальные варианты их развития.'
  ]
  lessons[mid]={'id':mid,'title':mission_titles[mi-1],'duration':13,'objectives':[f'объяснить роль темы «{topic[0]}» в главе «{ch["title"]}»','различить археологический материал, надпись, изображение и литературную традицию','связать полисы, святилища, колонии и социальные группы'],'story':[{'title':ch['title'],'text':ch['description']},{'title':'Фокус миссии','text':f'{mission_titles[mi-1]}. Главный материал: {topic[0]} — {topic[3]}.'},{'title':'Граница знания','text':'Археология, надписи, изображения и поздняя литература отвечают на разные вопросы.'}],'chronology':[{'date':d,'title':t,'note':f'{t}. Связь с миссией проверяется по месту, датировке и типу свидетельства.','certainty':c} for d,t,c in ch['chronology']],'concepts':[{'term':x[0],'definition':x[3]} for x in ch['story'][:3]],'causeEffect':{'causes':ch['causes'],'consequences':ch['consequences']},'activity':activity,'sources':[ch['source']],'theory':{'title':mission_titles[mi-1],'readingMinutes':9,'lead':f'{ch["description"]} Основной вопрос миссии — {topic[0].lower()}.','paragraphs':paras,'historicityNotes':['Поздние авторы не являются прямыми очевидцами ранней архаической эпохи.','Материальная культура и политическая идентичность не совпадают автоматически.','Традиционные даты законодателей и основателей требуют отдельной маркировки.','Афинская и спартанская модели не описывают весь греческий мир.'],'sources':[ch['source']],'license':'Авторский учебный текст Codex of History.','checkedAt':CHECKED}}
 map_chapters[ch_id]={'title':ch['title'],'center':P[ch['locations'][0]][0],'zoom':7}
 qs=[]
 for qi in range(4):
  correct=ch['story'][qi][0];distr=[ch['story'][(qi+j+1)%8][0] for j in range(3)];pos=(ci+qi)%4;opts=distr[:];opts.insert(pos,correct);qs.append({'text':f'Какой термин соответствует описанию: «{ch["story"][qi][3]}»?','options':opts,'correct':pos,'explanation':f'{correct}: {ch["story"][qi][3]}.'})
 pos=(ci+4)%4;opts=['Перенести афинские институты на все полисы','Считать поздний текст прямой стенограммой','Определять общину только по одному сосуду'];opts.insert(pos,'Сопоставить археологию, надписи, изображения и литературную традицию');qs.append({'text':f'Какой метод нужен в главе «{ch["title"]}»?','options':opts,'correct':pos,'explanation':'Разные источники дают независимые и частично противоречивые данные.'})
 pos=(ci+5)%4;opts=['Все полисы были единым государством','Археология полностью подтверждает каждую традиционную дату','Гражданами автоматически были все жители'];opts.insert(pos,ch['subtitle']);qs.append({'text':f'Какой итог главы «{ch["title"]}» наиболее точен?','options':opts,'correct':pos,'explanation':ch['description']})
 quizzes[f'QUIZ_ARC_CH{ci}']={'id':f'QUIZ_ARC_CH{ci}','title':f'Глава {ci}: {ch["title"]}','passPercent':70,'questions':qs}

chapters=[{'id':f'ARC_CHAPTER_{i:02d}','number':i,'title':ch['title'],'subtitle':ch['subtitle'],'description':ch['description'],'missionIds':[f'ARC_{i:02d}_{x:02d}' for x in range(1,7)]} for i,ch in enumerate(CHAPTERS,1)]
for source,target,desc in [
 ('AEG_S_10_07','ARC_S_01_01','Кризис микенских дворцов переходит в ранний железный век Греции.'),
 ('PHO_S_02_07','ARC_S_03_01','Финикийское письмо стало основой греческого алфавита.'),
 ('PHO_S_05_01','ARC_S_05_01','Финикийские и греческие морские сети развивались в одном Средиземноморье.'),
 ('COL_S_10_06','ARC_S_01_02','Постбронзовый переход связывает Эгеиду с ранним железным веком.'),
 ('PHO_A_08_01','ARC_A_05_02','Западные торговые центры связывали греческие и финикийские поселения.'),
 ('ASB_S_08_04','ARC_S_10_08','Персидская держава изменила положение ионийских городов.'),
 ('AEG_A_06_01','ARC_A_03_04','Линейное письмо Б и греческий алфавит принадлежат разным письменным системам.'),
 ('BRZ_S_08_06','ARC_S_04_07','Общие святилища заменили дворцовые центры новым форматом межрегиональных встреч.')]:
 relations.append({'id':f'REL_ARC_{rel_i:04d}','source':source,'target':target,'type':'МЕЖКАМПАНИЙНАЯ_СВЯЗЬ','description':desc,'strength':9});rel_i+=1

exam_specs={
'QUIZ_ARC_EXAM_MAP':('Карта полисов и колоний',[
 ('Где находилась Олимпия?',['В Пелопоннесе','В Малой Азии','На Сицилии','В дельте Нила'],0,'Олимпия находилась в Элиде на Пелопоннесе.'),('Какой полис основал Сиракузы?',['Афины','Коринф','Спарта','Фивы'],1,'Сиракузы связывались с коринфскими переселенцами.'),('Где находилась Массалия?',['В Ионии','В Лаконии','На юге современной Франции','На Кипре'],2,'Массалия располагалась на западном Средиземноморье.'),('Какой центр был главным оракульным святилищем Аполлона?',['Олимпия','Спарта','Сарды','Дельфы'],3,'Дельфы были главным святилищем Аполлона.'),('Где располагалась Иония?',['На западном побережье Малой Азии','В Сицилии','В Египте','В Южной Италии'],0,'Ионийские города находились на побережье Малой Азии и островах.')]),
'QUIZ_ARC_EXAM_TIME':('Хронология 1100–480 годов',[
 ('Что относится к самому раннему этапу?',['Протогеометрический период','Реформы Клисфена','Основание Массалии','Падение Писистратидов'],0,'Протогеометрический период начинается после 1050 года до н. э.'),('Когда распространяются ранние алфавитные надписи?',['XII век до н. э.','VIII век до н. э.','IV век н. э.','III век до н. э.'],1,'Ранние греческие алфавитные надписи относятся к VIII веку.'),('Когда традиционно датируют реформы Солона?',['776 год до н. э.','508 год до н. э.','594/593 год до н. э.','480 год до н. э.'],2,'Архонтство Солона традиционно относят к 594/593 году.'),('Когда прошли реформы Клисфена?',['621 год до н. э.','734 год до н. э.','1100 год до н. э.','508/507 год до н. э.'],3,'Реформы Клисфена относятся к концу VI века.'),('Какой порядок верен?',['Протогеометрический период → алфавит → колонизация → Солон → Клисфен','Солон → микенские дворцы → Клисфен → алфавит','Клисфен → Дипилон → Писистрат → Лефканди','Колонизация → бронзовый век → Гомер → Солон'],0,'Это общий маршрут кампании.')]),
'QUIZ_ARC_EXAM_STATE':('Полисы, реформы и общество',[
 ('Что точнее описывает полис?',['Автономная гражданская община с территорией и институтами','Единая греческая империя','Только крепость на холме','Колония Персии'],0,'Полис объединял людей, институты и территорию.'),('Какая группа была зависимой основой спартанского хозяйства?',['Эфоры','Илоты','Рапсоды','Ойкисты'],1,'Илоты обрабатывали землю и были зависимым населением.'),('Что сделала сисахфия?',['Создала фалангу','Учредила Олимпийские игры','Ограничила долговую зависимость граждан','Отменила все полисы'],2,'Сисахфия связывается с отменой долгового рабства афинян.'),('Почему тирании возникали в разных полисах?',['Из-за приказа единого царя','Только из-за Персии','Из-за отсутствия торговли','Из-за конфликтов элит, долгов и мобилизации новых групп'],3,'Тирании были одним из ответов на внутренние кризисы.'),('Как понимать колонии?',['Как самостоятельные полисы с особыми связями с метрополией','Как провинции единой Греции','Как чисто военные лагеря','Как поселения без местных контактов'],0,'Апойкии обычно становились самостоятельными общинами.')]),
'QUIZ_ARC_EXAM_SOURCE':('Археология, надписи и традиция',[
 ('Что надёжнее всего показывает вазопись?',['Визуальные сюжеты, техники и социальные представления','Точную фотографию битвы','Полный текст закона','Численность населения'],0,'Изображение требует анализа жанра и функции сосуда.'),('Как читать поздний рассказ о Ликурге или Солоне?',['Как нейтральную стенограмму','Как традицию, которую нужно сравнить с ранними данными','Как археологический слой','Как карту колоний'],1,'Поздние авторы сохраняют память, но пишут через категории своего времени.'),('Что нельзя доказать одним типом керамики?',['Датировку слоя','Направление обмена','Этническую идентичность каждого жителя','Технику производства'],2,'Материальная культура не равна простой этнической метке.'),('Почему гоплитская революция остаётся спорной?',['Нет оружия','Нет полисов','Все источники полностью согласны','Военные и политические изменения шли постепенно и неравномерно'],3,'Прямая универсальная схема не объясняет региональные различия.'),('Какой итог корректнее?',['Разделять факт, древнее утверждение, традицию и современную реконструкцию','Выбирать только афинские источники','Считать спор признаком отсутствия истории','Скрывать степень уверенности'],0,'Исторический метод показывает границы каждого вывода.')])}
for qid,(title,raw) in exam_specs.items():quizzes[qid]={'id':qid,'title':title,'passPercent':70,'questions':[{'text':a,'options':b,'correct':c,'explanation':d} for a,b,c,d in raw]}

campaign={'id':'GREECE_ARCHAIC','title':'Архаическая Греция','description':'От раннего железного века и полисов до колонизации, Спарты, Афин, реформ и искусства архаической эпохи.','difficulty':9,'chapters':chapters,'nodes':nodes,'eraLayer':{'period':'ок. 1100–480 годы до н. э.','summary':'Кампания показывает греческий мир как сеть разных полисов, святилищ и поселений, а позднюю традицию отделяет от археологии и ранних надписей.','phases':[{'id':'RECOVERY','title':'После дворцов','date':'ок. 1100–800 до н. э.','chapters':[1,2]},{'id':'NETWORKS','title':'Письмо, святилища и колонии','date':'VIII–VI века до н. э.','chapters':[3,4,5]},{'id':'CONFLICT','title':'Законы, война и тирании','date':'VII–VI века до н. э.','chapters':[6,7]},{'id':'POLEIS','title':'Спарта, Афины и переход','date':'VI–480 до н. э.','chapters':[8,9,10]}]}}
pools_payload={'campaignId':'GREECE_ARCHAIC','campaigns':{'GREECE_ARCHAIC':{'id':'GREECE_ARCHAIC','title':'Архаическая Греция','active':True,'status':'STARTED'}},'pools':pools,'acquisition':acquisition}
map_payload={'points':{k:v[0] for k,v in P.items()},'regions':{},'cardPoints':card_points,'chapters':map_chapters,'missionCenter':[38.0,23.8],'missionZoom':5}

dump(Path('data/cards/archaic-greece/story.json'),story_cards);dump(Path('data/cards/archaic-greece/archive.json'),archive_cards);dump(Path('data/campaigns/archaic-greece/campaign.json'),campaign);dump(Path('data/campaigns/archaic-greece/pools.json'),pools_payload);dump(Path('data/lessons/archaic-greece/campaign.json'),lessons);dump(Path('data/quizzes/archaic-greece/campaign.json'),quizzes);dump(Path('data/stories/archaic-greece/personal.json'),stories);dump(Path('data/maps/archaic-greece.json'),map_payload);dump(Path('data/core/relations-v43-archaic-greece.json'),relations);pack_svg()
print(f'generated {len(story_cards)+len(archive_cards)} cards, {len(nodes)} missions, {len(lessons)} lessons, {len(quizzes)} quizzes, {len(relations)} relations')
