#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import process from 'node:process';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const manifest=read('data/content-manifest.json'),d=manifest.datasets;
const cards=d.cards.flatMap(read),relations=read(d.relations),campaign=read(d.campaign),pools=read(d.pools),quizzes=read(d.quizzes),stories=read(d.stories);
const app={innerHTML:''},local=new Map();
const document={documentElement:{dataset:{},style:{setProperty(){}},classList:{add(){},remove(){}}},querySelector(){return null},getElementById(id){return id==='app'?app:null},addEventListener(){},createElement(){return{className:'',style:{setProperty(){}},remove(){},classList:{add(){}},innerHTML:''}},body:{appendChild(){}}};
const localStorage={getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,v),removeItem:k=>local.delete(k)};
const context={console,Date,Math,JSON,Intl,Map,Set,CustomEvent:class{constructor(type,init){this.type=type;this.detail=init?.detail}},localStorage,confirm:()=>true,setTimeout:()=>0,clearTimeout(){},requestAnimationFrame(){},window:{scrollTo(){},dispatchEvent(){},matchMedia:()=>({matches:true})},document,location:{protocol:'http:'},IntersectionObserver:class{},L:undefined};
context.window.window=context.window;context.window.document=document;context.window.localStorage=localStorage;context.globalThis=context;
Object.assign(context,{CODEX_MANIFEST:manifest,CODEX_CONFIG:{mastery:read(d.mastery),packs:read(d.packs),collection:read(d.collection),maps:read(d.maps),daily:read(d.daily)},CARDS:cards,RELATIONS:relations,CAMPAIGN:campaign,V09_CONTENT:pools,QUIZZES:quizzes,PERSONAL_STORIES:stories});
context.CODEX_REGISTRY={cardsById:new Map(cards.map(x=>[x.id,x])),relationsByCard:new Map(cards.map(c=>[c.id,relations.filter(r=>r.source===c.id||r.target===c.id)])),missionsById:new Map(campaign.nodes.map(x=>[x.id,x])),poolsById:new Map(pools.pools.map(x=>[x.id,x]))};
const ctx=vm.createContext(context);
for(const script of manifest.scripts)vm.runInContext(fs.readFileSync(path.join(root,script),'utf8'),ctx,{filename:script});
const assert=(v,m)=>{if(!v)throw new Error(m)};
assert(app.innerHTML.includes('Ежедневное обучение'),'Главная не содержит daily-блок');
vm.runInContext("state.read=['PER_ROM_001','PER_ROM_005','EVT_ROM_001'];state.unlocked=['PER_ROM_001','PER_ROM_005','EVT_ROM_001'];state.tab='daily';dailySyncSchedule();render();",ctx);
assert(app.innerHTML.includes('Очередь памяти'),'Не отрендерен экран Сегодня');
vm.runInContext('startDailySession(false)',ctx);
assert(app.innerHTML.includes('Ежедневная сессия'),'Сессия не стартовала');
const total=vm.runInContext('state.dailySession.tasks.length',ctx);
for(let i=0;i<total;i++)vm.runInContext('answerDaily(dailyCurrentTask().correct);nextDailyTask();',ctx);
assert(vm.runInContext('dailyLearningCompleteToday()',ctx),'Сессия не завершилась');
assert(vm.runInContext('dailyPackReady()',ctx),'Пак не разблокировался');
assert(vm.runInContext('state.dailySession.reward.xp>0&&state.dailySession.reward.fragments>0',ctx),'Награда не начислена');
console.log(`✓ Daily smoke: ${total} заданий, награда и пак работают`);
