#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const manifest=read('data/content-manifest.json'),d=manifest.datasets;
const bundle=spec=>Array.isArray(spec)?Object.assign({},...spec.map(read)):read(spec);
const cards=d.cards.flatMap(read),relations=read(d.relations),campaign=read(d.campaign),pools=read(d.pools),quizzes=bundle(d.quizzes),stories=read(d.stories);
const app={innerHTML:''},local=new Map();
const document={documentElement:{dataset:{},style:{},classList:{add(){},remove(){}}},querySelector(){return null},getElementById(id){return id==='app'?app:null},addEventListener(){},body:{appendChild(){},classList:{add(){},remove(){},toggle(){}}}};
const context={console,Date,Math,JSON,Intl,Map,Set,URL,Blob,Promise,CustomEvent:class{},localStorage:{getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,v),removeItem:k=>local.delete(k)},sessionStorage:{getItem(){return null},setItem(){},removeItem(){}},confirm:()=>true,setTimeout:fn=>0,clearTimeout(){},requestAnimationFrame(){},window:{scrollTo(){},dispatchEvent(){},matchMedia:()=>({matches:true})},document,location:{protocol:'http:',href:'https://example.test/',replace(){},reload(){}},IntersectionObserver:class{},L:undefined,navigator:{}};
context.window.window=context.window;context.window.document=document;context.globalThis=context;
Object.assign(context,{CODEX_MANIFEST:manifest,CODEX_CONFIG:{mastery:read(d.mastery),packs:read(d.packs),collection:read(d.collection),maps:read(d.maps),daily:read(d.daily)},CARDS:cards,RELATIONS:relations,CAMPAIGN:campaign,V09_CONTENT:pools,QUIZZES:quizzes,PERSONAL_STORIES:stories});
context.CODEX_REGISTRY={cardsById:new Map(cards.map(x=>[x.id,x])),relationsByCard:new Map(cards.map(c=>[c.id,relations.filter(r=>r.source===c.id||r.target===c.id)])),missionsById:new Map(campaign.nodes.map(x=>[x.id,x])),poolsById:new Map(pools.pools.map(x=>[x.id,x]))};
const ctx=vm.createContext(context);
for(const script of manifest.scripts)vm.runInContext(fs.readFileSync(path.join(root,script),'utf8'),ctx,{filename:script});
const assert=(v,m)=>{if(!v)throw new Error(m)};
assert(manifest.version==='1.7.0','Версия не обновлена до 1.7.0');
assert(cards.every(c=>c.source?.type==='wikipedia'&&c.source.url),'Не у всех карточек есть Wikipedia source');
vm.runInContext("state.tab='home';render();",ctx);
assert(!app.innerHTML.includes('title="Принудительно обновить"'),'Кнопка обновления осталась сверху');
assert(app.innerHTML.includes('mobile-drawer'),'Боковая навигация отсутствует');
assert(app.innerHTML.includes('Паки'),'Вкладка паков отсутствует');
vm.runInContext("state.tab='detail';state.currentCard='PER_ROM_001';render();",ctx);
assert(app.innerHTML.includes('detail-back-button'),'Нет кнопки назад на карточке');
assert(app.innerHTML.includes('Открыть в Википедии'),'Источник не заменён на Wikipedia');
assert(!app.innerHTML.includes('Источник изображения'),'Старый источник изображения остался');
assert(app.innerHTML.includes('compact-fact-list'),'Факты не уплотнены');
vm.runInContext("state.tab='campaign';render();",ctx);
assert(!app.innerHTML.includes('Архивные пулы кампании'),'Блок архивных пулов остался');
vm.runInContext("state.tab='map';render();",ctx);
assert(app.innerHTML.includes('Карта кампании'),'Контекст карты главы отсутствует');
assert(!app.innerHTML.includes('Этрурия')&&!app.innerHTML.includes('Сабинская область'),'Старые области карты остались в UI');
assert(app.innerHTML.includes('map-filter-row'),'Нет фильтров маркеров карты');
vm.runInContext("state.tab='packs';render();",ctx);
assert(app.innerHTML.includes('pack-daily.svg')&&app.innerHTML.includes('pack-rome.svg'),'Нет собственных обложек паков');
assert(!app.innerHTML.includes('Выпадают только карточки'),'Старое описание паков осталось');
vm.runInContext("state.tab='profile';render();",ctx);
assert(!app.innerHTML.includes('profile-compact-hero'),'Старый блок профиля с настройками остался');
assert(app.innerHTML.includes('profile-danger-zone'),'Сброс прогресса отсутствует внизу');
vm.runInContext("state.tab='settings';render();",ctx);
assert(app.innerHTML.includes('Тёмная тема'),'Тема не переименована');
assert(app.innerHTML.includes('Принудительно обновить'),'Обновление не перенесено в настройки');
assert(!app.innerHTML.includes('Плотность мобильного интерфейса')&&!app.innerHTML.includes('Размер текста')&&!app.innerHTML.includes('Анимации'),'Лишние настройки остались');
console.log('✓ UI v1.7 compatibility smoke: card, map, packs, profile and settings work');
