#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const manifest=read('data/content-manifest.json'),d=manifest.datasets;
const bundle=spec=>Array.isArray(spec)?Object.assign({},...spec.map(read)):read(spec);
const cards=d.cards.flatMap(read),relations=read(d.relations),campaign=read(d.campaign),pools=read(d.pools),quizzes=bundle(d.quizzes),stories=read(d.stories);
const app={innerHTML:''},local=new Map();
const document={documentElement:{dataset:{},style:{},classList:{add(){},remove(){}}},querySelector(){return null},getElementById(id){return id==='app'?app:null},addEventListener(){},body:{appendChild(){},classList:{add(){},remove(){},toggle(){}}}};
const context={console,Date,Math,JSON,Intl,Map,Set,URL,Blob,Promise,CustomEvent:class{},localStorage:{getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,v),removeItem:k=>local.delete(k)},sessionStorage:{getItem(){return null},setItem(){},removeItem(){}},confirm:()=>true,setTimeout:fn=>0,clearTimeout(){},requestAnimationFrame(){},window:{scrollTo(){},dispatchEvent(){},matchMedia:()=>({matches:true})},document,location:{protocol:'http:',href:'https://example.test/',replace(){},reload(){}},IntersectionObserver:class{},L:undefined,navigator:{}};
context.window.window=context.window;context.window.document=document;context.globalThis=context;
Object.assign(context,{CODEX_MANIFEST:manifest,CODEX_CONFIG:{mastery:read(d.mastery),packs:read(d.packs),collection:read(d.collection),maps:read(d.maps),daily:read(d.daily)},CARDS:cards,RELATIONS:relations,CAMPAIGN:campaign,V09_CONTENT:pools,QUIZZES:quizzes,PERSONAL_STORIES:stories});
context.CODEX_REGISTRY={cardsById:new Map(cards.map(x=>[x.id,x])),relationsByCard:new Map(cards.map(c=>[c.id,relations.filter(r=>r.source===c.id||r.target===c.id)])),missionsById:new Map(campaign.nodes.map(x=>[x.id,x])),poolsById:new Map(pools.pools.map(x=>[x.id,x]))};
const ctx=vm.createContext(context);
for(const script of manifest.scripts)vm.runInContext(fs.readFileSync(path.join(root,script),'utf8'),ctx,{filename:script});
const assert=(v,m)=>{if(!v)throw new Error(m)};
vm.runInContext("state.tab='collection';state.collectionView='ARCHIVE';render();",ctx);
assert(app.innerHTML.includes('library-mini-switch'),'Нет компактного переключателя Архив/Коллекция');
assert(!app.innerHTML.includes('Только полученные карточки'),'Старый заголовок архива не удалён');
assert(!app.innerHTML.includes('mastery-overview'),'Большой блок освоения остался в архиве');
assert(app.innerHTML.includes('compact-filter-row'),'Фильтры не заменены компактной строкой');
vm.runInContext("state.collectionView='CATALOG';render();",ctx);
assert(app.innerHTML.includes('Полный каталог'),'Коллекция не открывается');
assert(!app.innerHTML.includes('catalog-summary'),'Большой блок статистики коллекции не удалён');
vm.runInContext("state.tab='map';render();",ctx);
assert(app.innerHTML.includes('id="atlas-map"'),'Карта отсутствует');
assert(!app.innerHTML.includes('Интерактивная карта'),'Старый блок интерактивной карты не удалён');
vm.runInContext("state.tab='profile';render();",ctx);
assert(!app.innerHTML.includes('Личная хроника'),'Старый блок профиля не удалён');
assert(!app.innerHTML.includes('onclick="openPackHub()"'),'Кнопка паков осталась в профиле');
assert(app.innerHTML.includes('profile-danger-zone'),'Сброс прогресса не перенесён вниз');
vm.runInContext('openPackHub()',ctx);
assert(app.innerHTML.includes('compact-pack-row'),'Паки не собраны в компактную линию');
assert(app.innerHTML.includes('pack-cover'),'Изображения паков отсутствуют');
assert(!app.innerHTML.includes('Выпадают только карточки из уже открытых этапов'),'Старое описание паков не удалено');
assert(app.innerHTML.includes('mobile-drawer'),'Боковая мобильная навигация отсутствует');
assert(manifest.version==='1.4.0','Версия не обновлена до 1.4.0');
console.log('✓ UI v1.4 smoke: compact library, drawer, map, profile and packs work');
