#!/usr/bin/env node
import fs from 'node:fs/promises';import path from 'node:path';import process from 'node:process';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const read=async p=>JSON.parse(await fs.readFile(path.join(root,p),'utf8'));const errors=[];const warnings=[];const req=(x,m)=>x||errors.push(m);
const manifest=await read('data/content-manifest.json'),d=manifest.datasets;const cards=(await Promise.all(d.cards.map(read))).flat();const relations=await read(d.relations);const campaigns=await Promise.all((d.campaigns||[d.campaign]).map(read));const poolSets=await Promise.all((Array.isArray(d.pools)?d.pools:[d.pools]).map(read));const pools={pools:poolSets.flatMap(x=>x.pools||[]),acquisition:Object.assign({},...poolSets.map(x=>x.acquisition||{}))};const bundle=async spec=>Object.assign({},...(await Promise.all((Array.isArray(spec)?spec:[spec]).map(read))));const quizzes=await bundle(d.quizzes),stories=await bundle(d.stories),lessons=await bundle(d.lessons),daily=await read(d.daily);const ids=new Set();
for(const c of cards){req(c?.id,`Карточка без id`);req(!ids.has(c.id),`Дубликат card id: ${c.id}`);ids.add(c.id);for(const k of ['type','title','subtitle','era','region','date','rarity','summary','importance','facts','tags','stats','image','source'])req(c[k]!==undefined,`${c.id}: нет ${k}`);req(c.facts?.length>=3,`${c.id}: меньше 3 фактов`);req(c.source?.url,`${c.id}: нет источника`);if(c.image?.local)req(await fs.access(path.join(root,c.image.local)).then(()=>true).catch(()=>false),`${c.id}: нет локального изображения ${c.image.local}`);}
for(const r of relations){req(ids.has(r.source),`${r.id}: нет source ${r.source}`);req(ids.has(r.target),`${r.id}: нет target ${r.target}`);}
const allMissionIds=new Set(campaigns.flatMap(c=>c.nodes.map(n=>n.id)));for(const c of campaigns){req(c.chapters?.length>0,`${c.id}: нет глав`);for(const m of c.nodes){for(const id of [...(m.cards||[]),...(m.unlockCards||[])])req(ids.has(id),`${m.id}: нет карты ${id}`);req(lessons[m.id],`${m.id}: нет урока`);if(m.quiz)req(quizzes[m.quiz],`${m.id}: нет квиза ${m.quiz}`);const l=lessons[m.id];if(l){req(l.story?.length>=2,`${m.id}: слабый рассказ`);req(l.chronology?.length>=3,`${m.id}: нет хронологии`);req(l.concepts?.length>=3,`${m.id}: нет понятий`);req(l.theory?.paragraphs?.length>=5,`${m.id}: теория короткая`);req((l.theory?.paragraphs||[]).join(' ').split(/\s+/).length>=250,`${m.id}: теория меньше 250 слов`);req(l.activity?.type,`${m.id}: нет практики`);}}}
for(const p of pools.pools){for(const id of p.cardIds)req(ids.has(id),`${p.id}: нет карты ${id}`);if(!String(p.unlockMission).includes('_CHAPTER_'))req(allMissionIds.has(p.unlockMission),`${p.id}: нет миссии ${p.unlockMission}`);}
for(const [id,a] of Object.entries(pools.acquisition)){req(ids.has(id),`Acquisition: нет карты ${id}`);if(a.pool)req(pools.pools.some(p=>p.id===a.pool),`${id}: нет пула ${a.pool}`);}
for(const [id,s] of Object.entries(stories)){req(ids.has(s.cardId),`${id}: нет карты ${s.cardId}`);req(s.steps?.length>0,`${id}: нет шагов`);}
const eras=await read(d.eras),catalog=await read(d.campaignCatalog),timeline=await read(d.worldTimeline);const catIds=new Set(catalog.map(x=>x.id));for(const e of eras)for(const id of e.campaignIds)req(catIds.has(id),`${e.id}: нет кампании ${id}`);for(const c of catalog){req(c.chapterCount===c.chapters.length,`${c.id}: chapterCount`);req(c.releasedChapters<=c.chapterCount,`${c.id}: releasedChapters`);}for(const t of timeline)req(catIds.has(t.campaignId),`Timeline: нет ${t.campaignId}`);
const rarities=['COMMON','UNCOMMON','RARE','EPIC','LEGENDARY','MYTHIC'];const rc=Object.fromEntries(rarities.map(r=>[r,cards.filter(c=>c.rarity===r).length]));req(rc.COMMON>rc.UNCOMMON&&rc.UNCOMMON>rc.RARE&&rc.RARE>rc.EPIC&&rc.EPIC>rc.LEGENDARY&&rc.LEGENDARY>rc.MYTHIC,`Нарушена пирамида ${JSON.stringify(rc)}`);req(daily.interval_days?.length>0,'Daily: нет интервалов');
const egypt=campaigns.find(c=>c.id==='EGYPT_EARLY');req(egypt?.chapters.length===10,'Египет: ожидалось 10 глав');req(egypt?.nodes.length===60,'Египет: ожидалось 60 миссий');req(cards.filter(c=>c.campaign==='EGYPT').length===160,'Египет: ожидалось 160 карточек');

const cmp=campaigns.find(c=>c.id==='DAWN_PARALLEL');req(cmp?.chapters.length===6,'Сравнение: ожидалось 6 глав');req(cmp?.nodes.length===24,'Сравнение: ожидалось 24 миссии');req(cards.filter(c=>c.campaign==='COMPARISON').length===36,'Сравнение: ожидалось 36 карточек');
const meso=campaigns.find(c=>c.id==='MESOPOTAMIA_DAWN');req(meso?.chapters.length===10,'Месопотамия: ожидалось 10 глав');req(meso?.nodes.length===60,'Месопотамия: ожидалось 60 миссий');req(cards.filter(c=>c.campaign==='MESOPOTAMIA').length>=155,'Месопотамия: мало карточек');
console.log(`Codex Validator v${manifest.version}`);console.log(`Карточки ${cards.length}; кампании ${campaigns.length}; миссии ${campaigns.reduce((n,c)=>n+c.nodes.length,0)}; уроки ${Object.keys(lessons).length}; пулы ${pools.pools.length}; редкость ${rarities.map(r=>rc[r]).join('/')}`);if(warnings.length)warnings.forEach(x=>console.log('WARN',x));if(errors.length){errors.forEach(x=>console.error('ERROR',x));process.exit(1);}console.log('✓ Контент валиден');
