#!/usr/bin/env node
import fs from 'node:fs/promises';import path from 'node:path';import process from 'node:process';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const read=async p=>JSON.parse(await fs.readFile(path.join(root,p),'utf8'));const errors=[];const warnings=[];const req=(x,m)=>x||errors.push(m);
const manifest=await read('data/content-manifest.json'),d=manifest.datasets;const cards=(await Promise.all(d.cards.map(read))).flat();const relations=await read(d.relations);const campaigns=await Promise.all((d.campaigns||[d.campaign]).map(read));const poolSets=await Promise.all((Array.isArray(d.pools)?d.pools:[d.pools]).map(read));const pools={pools:poolSets.flatMap(x=>x.pools||[]),acquisition:Object.assign({},...poolSets.map(x=>x.acquisition||{}))};const bundle=async spec=>Object.assign({},...(await Promise.all((Array.isArray(spec)?spec:[spec]).map(read))));const quizzes=await bundle(d.quizzes),stories=await bundle(d.stories),lessons=await bundle(d.lessons),daily=await read(d.daily);const ids=new Set();
const imagePaths=new Map();
for(const c of cards){
 req(c?.id,`Карточка без id`);req(!ids.has(c.id),`Дубликат card id: ${c.id}`);ids.add(c.id);
 for(const k of ['type','title','subtitle','era','region','date','rarity','summary','importance','facts','tags','stats','image','source'])req(c[k]!==undefined,`${c.id}: нет ${k}`);
 req(c.facts?.length>=3,`${c.id}: меньше 3 фактов`);req(c.source?.url,`${c.id}: нет источника`);
 req(c.image?.local,`${c.id}: нет локального fallback-изображения`);req(['historical-image','project-cover'].includes(c.image?.kind),`${c.id}: не указан image.kind`);if(c.image?.prefer_remote){req(c.image?.file,`${c.id}: remote image без file`);req(/^https:\/\/commons\.wikimedia\.org\/wiki\/File:/.test(c.image?.source_url||''),`${c.id}: неверный Commons source_url`);}req(c.image?.caption,`${c.id}: нет image.caption`);req(c.image?.credit,`${c.id}: нет image.credit`);req(c.image?.source_url,`${c.id}: нет image.source_url`);req(c.image?.license,`${c.id}: нет image.license`);
 if(c.image?.local){
  const local=path.join(root,c.image.local),exists=await fs.access(local).then(()=>true).catch(()=>false);req(exists,`${c.id}: нет локального изображения ${c.image.local}`);
  req(!imagePaths.has(c.image.local),`${c.id}: изображение повторяет ${imagePaths.get(c.image.local)} — ${c.image.local}`);imagePaths.set(c.image.local,c.id);
  if(exists&&c.image.local.endsWith('.svg')){const text=await fs.readFile(local,'utf8');const vb=text.match(/viewBox=["'](?:-?\d+(?:\.\d+)?\s+){2}(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)["']/);req(!!vb,`${c.id}: SVG без viewBox`);if(vb){const ratio=Number(vb[1])/Number(vb[2]);req(ratio>.55&&ratio<1.15,`${c.id}: неверные пропорции SVG ${ratio.toFixed(2)}`);}}
 }
}
for(const r of relations){req(ids.has(r.source),`${r.id}: нет source ${r.source}`);req(ids.has(r.target),`${r.id}: нет target ${r.target}`);}
const allMissionIds=new Set(campaigns.flatMap(c=>c.nodes.map(n=>n.id)));for(const c of campaigns){req(c.chapters?.length>0,`${c.id}: нет глав`);for(const m of c.nodes){for(const id of [...(m.cards||[]),...(m.unlockCards||[])])req(ids.has(id),`${m.id}: нет карты ${id}`);req(lessons[m.id],`${m.id}: нет урока`);if(m.quiz)req(quizzes[m.quiz],`${m.id}: нет квиза ${m.quiz}`);const l=lessons[m.id];if(l){req(l.story?.length>=2,`${m.id}: слабый рассказ`);req(l.chronology?.length>=3,`${m.id}: нет хронологии`);req(l.concepts?.length>=3,`${m.id}: нет понятий`);req(l.theory?.paragraphs?.length>=5,`${m.id}: теория короткая`);req((l.theory?.paragraphs||[]).join(' ').split(/\s+/).length>=250,`${m.id}: теория меньше 250 слов`);req(l.activity?.type,`${m.id}: нет практики`);}}}
for(const p of pools.pools){for(const id of p.cardIds)req(ids.has(id),`${p.id}: нет карты ${id}`);if(!String(p.unlockMission).includes('_CHAPTER_'))req(allMissionIds.has(p.unlockMission),`${p.id}: нет миссии ${p.unlockMission}`);}
for(const [id,a] of Object.entries(pools.acquisition)){req(ids.has(id),`Acquisition: нет карты ${id}`);if(a.pool)req(pools.pools.some(p=>p.id===a.pool),`${id}: нет пула ${a.pool}`);}
for(const [id,s] of Object.entries(stories)){req(ids.has(s.cardId),`${id}: нет карты ${s.cardId}`);req(s.steps?.length>0,`${id}: нет шагов`);}
const eras=await read(d.eras),catalog=await read(d.campaignCatalog),timeline=await read(d.worldTimeline);const catIds=new Set(catalog.map(x=>x.id));for(const e of eras)for(const id of e.campaignIds)req(catIds.has(id),`${e.id}: нет кампании ${id}`);for(const c of catalog){req(c.chapterCount===c.chapters.length,`${c.id}: chapterCount`);req(c.releasedChapters<=c.chapterCount,`${c.id}: releasedChapters`);}for(const t of timeline)req(catIds.has(t.campaignId),`Timeline: нет ${t.campaignId}`);
const rarities=['COMMON','UNCOMMON','RARE','EPIC','LEGENDARY','MYTHIC'];const rc=Object.fromEntries(rarities.map(r=>[r,cards.filter(c=>c.rarity===r).length]));req(rc.COMMON>rc.UNCOMMON&&rc.UNCOMMON>rc.RARE&&rc.RARE>rc.EPIC&&rc.EPIC>rc.LEGENDARY&&rc.LEGENDARY>rc.MYTHIC,`Нарушена пирамида ${JSON.stringify(rc)}`);req(daily.interval_days?.length>0,'Daily: нет интервалов');
const egypt=campaigns.find(c=>c.id==='EGYPT_EARLY');req(egypt?.chapters.length===10,'Египет: ожидалось 10 глав');req(egypt?.nodes.length===60,'Египет: ожидалось 60 миссий');req(cards.filter(c=>c.campaign==='EGYPT').length===160,'Египет: ожидалось 160 карточек');

const cmp=campaigns.find(c=>c.id==='DAWN_PARALLEL');req(cmp?.chapters.length===6,'Сравнение: ожидалось 6 глав');req(cmp?.nodes.length===24,'Сравнение: ожидалось 24 миссии');req(cards.filter(c=>c.campaign==='COMPARISON').length===36,'Сравнение: ожидалось 36 карточек');
const china=campaigns.find(c=>c.id==='CHINA_EARLY');req(china?.chapters.length===8,'Китай: ожидалось 8 глав');req(china?.nodes.length===48,'Китай: ожидалось 48 миссий');req(cards.filter(c=>c.campaign==='CHINA').length===96,'Китай: ожидалось 96 карточек');
const indus=campaigns.find(c=>c.id==='INDUS');req(indus?.chapters.length===7,'Инд: ожидалось 7 глав');req(indus?.nodes.length===42,'Инд: ожидалось 42 миссии');req(cards.filter(c=>c.campaign==='INDUS').length===91,'Инд: ожидалось 91 карточка');
const meso=campaigns.find(c=>c.id==='MESOPOTAMIA_DAWN');req(meso?.chapters.length===10,'Месопотамия: ожидалось 10 глав');req(meso?.nodes.length===60,'Месопотамия: ожидалось 60 миссий');req(cards.filter(c=>c.campaign==='MESOPOTAMIA').length>=155,'Месопотамия: мало карточек');
const dawn=campaigns.find(c=>c.id==='DAWN_WORLD');req(dawn?.chapters.length===6,'Общий слой эпохи: ожидалось 6 глав');req(dawn?.nodes.length===30,'Общий слой эпохи: ожидалось 30 миссий');const dawnCards=cards.filter(c=>c.campaign==='CIVILIZATIONS');req(dawnCards.length===60,'Общий слой эпохи: ожидалось 60 карточек');req(new Set(dawnCards.map(c=>c.summary)).size===dawnCards.length,'Общий слой эпохи: повторяются summary карточек');req(new Set(dawnCards.map(c=>c.importance)).size===dawnCards.length,'Общий слой эпохи: повторяются importance карточек');req(new Set(dawnCards.map(c=>c.facts?.[0])).size===dawnCards.length,'Общий слой эпохи: повторяются ключевые факты карточек');for(const c of dawnCards){req(!c.summary.includes('Карточка нужна'),`${c.id}: шаблонный summary`);req(!c.importance.includes('Нужна для'),`${c.id}: шаблонный importance`);}
const dawnParagraphs=new Map();for(const m of dawn?.nodes||[]){const l=lessons[m.id],words=(l?.theory?.paragraphs||[]).join(' ').split(/\s+/).filter(Boolean).length;req(words>=300,`${m.id}: теория общего слоя меньше 300 слов`);for(const paragraph of l?.theory?.paragraphs||[]){req(!dawnParagraphs.has(paragraph),`${m.id}: повтор теоретического абзаца из ${dawnParagraphs.get(paragraph)}`);dawnParagraphs.set(paragraph,m.id);}}for(const chapter of dawn?.chapters||[]){const chapterWords=(dawn.nodes.filter(m=>m.chapterId===chapter.id).flatMap(m=>lessons[m.id]?.theory?.paragraphs||[]).join(' ').split(/\s+/).filter(Boolean).length);req(chapterWords>=1000&&chapterWords<=2500,`${chapter.id}: теория главы ${chapterWords} слов, ожидалось 1000–2500`);}
const dawnPools=pools.pools.filter(p=>p.campaign==='CIVILIZATIONS');req(dawnPools.length===6,'Общий слой эпохи: ожидалось 6 пулов');req(dawnPools.flatMap(p=>p.cardIds).length===24,'Общий слой эпохи: ожидалось 24 архивных карты');
const eraExam=dawn?.nodes.find(n=>n.id==='CIV_06_05');req(eraExam?.examModules?.length===6,'Экзамен эпохи: ожидалось 6 модулей');for(const mod of eraExam?.examModules||[])req(quizzes[mod.id],`Экзамен эпохи: нет квиза ${mod.id}`);const dawnQuizEntries=Object.entries(quizzes).filter(([id])=>id.startsWith('QUIZ_CIV_'));const dawnQuestions=dawnQuizEntries.flatMap(([,q])=>q.questions||[]);req(dawnQuizEntries.length===11,'Общий слой эпохи: ожидалось 11 квизов');req(dawnQuestions.length===54,'Общий слой эпохи: ожидалось 54 вопроса');req(new Set(dawnQuestions.map(q=>q.text)).size===dawnQuestions.length,'Общий слой эпохи: повторяются вопросы');const answerPositions=[0,0,0,0];for(const q of dawnQuestions){req(q.options?.length===4,`Вопрос «${q.text}»: ожидалось 4 варианта`);req(Number.isInteger(q.correct)&&q.correct>=0&&q.correct<4,`Вопрос «${q.text}»: неверный correct`);if(Number.isInteger(q.correct)&&q.correct>=0&&q.correct<4)answerPositions[q.correct]++;}for(let i=0;i<4;i++)req(answerPositions[i]>=10,`Квизы общего слоя: позиция ответа ${i} встречается только ${answerPositions[i]} раз`);
req(dawn?.eraLayer?.regions?.length===4,'Глобальная карта: ожидалось 4 региона');req(dawn?.eraLayer?.parallelTimeline?.length>=4,'Параллельная хронология слишком короткая');
const babylon=campaigns.find(c=>c.id==='BABYLON_OLD');req(babylon?.chapters.length===8,'Вавилон: ожидалось 8 глав');req(babylon?.nodes.length===48,'Вавилон: ожидалось 48 миссий');const babylonCards=cards.filter(c=>c.campaign==='BABYLON');req(babylonCards.length===96,'Вавилон: ожидалось 96 карточек');req(babylonCards.filter(c=>c.acquisition==='STORY').length===64,'Вавилон: ожидалось 64 сюжетные карточки');req(babylonCards.filter(c=>c.acquisition==='ARCHIVE').length===32,'Вавилон: ожидалось 32 архивные карточки');req(new Set(babylonCards.map(c=>c.summary)).size===babylonCards.length,'Вавилон: повторяются summary карточек');req(new Set(babylonCards.map(c=>c.image?.local)).size===babylonCards.length,'Вавилон: повторяются изображения карточек');
const babylonParagraphs=new Map();for(const m of babylon?.nodes||[]){const l=lessons[m.id],words=(l?.theory?.paragraphs||[]).join(' ').split(/\s+/).filter(Boolean).length;req(words>=300,`${m.id}: теория Вавилона меньше 300 слов`);for(const paragraph of l?.theory?.paragraphs||[]){req(!babylonParagraphs.has(paragraph),`${m.id}: повтор теоретического абзаца из ${babylonParagraphs.get(paragraph)}`);babylonParagraphs.set(paragraph,m.id);}}for(const chapter of babylon?.chapters||[]){const chapterWords=(babylon.nodes.filter(m=>m.chapterId===chapter.id).flatMap(m=>lessons[m.id]?.theory?.paragraphs||[]).join(' ').split(/\s+/).filter(Boolean).length);req(chapterWords>=1000&&chapterWords<=2500,`${chapter.id}: теория главы ${chapterWords} слов, ожидалось 1000–2500`);}
const babylonPools=pools.pools.filter(p=>p.campaign==='BABYLON');req(babylonPools.length===8,'Вавилон: ожидалось 8 пулов');req(babylonPools.flatMap(p=>p.cardIds).length===32,'Вавилон: ожидалось 32 карты в архивных пулах');const babylonStories=Object.values(stories).filter(s=>String(s.cardId||'').startsWith('BAB_'));req(babylonStories.length===8,'Вавилон: ожидалось 8 личных историй');
const babylonQuizEntries=Object.entries(quizzes).filter(([id])=>id.startsWith('QUIZ_BAB_'));const babylonQuestions=babylonQuizEntries.flatMap(([,q])=>q.questions||[]);req(babylonQuizEntries.length===12,'Вавилон: ожидалось 12 квизов');req(babylonQuestions.length===68,'Вавилон: ожидалось 68 вопросов');req(new Set(babylonQuestions.map(q=>q.text)).size===babylonQuestions.length,'Вавилон: повторяются вопросы');const babylonAnswerPositions=[0,0,0,0];for(const q of babylonQuestions){req(q.options?.length===4,`Вопрос Вавилона «${q.text}»: ожидалось 4 варианта`);req(Number.isInteger(q.correct)&&q.correct>=0&&q.correct<4,`Вопрос Вавилона «${q.text}»: неверный correct`);if(Number.isInteger(q.correct)&&q.correct>=0&&q.correct<4)babylonAnswerPositions[q.correct]++;}for(let i=0;i<4;i++)req(babylonAnswerPositions[i]>=12,`Квизы Вавилона: позиция ответа ${i} встречается только ${babylonAnswerPositions[i]} раз`);
const babylonExam=babylon?.nodes.find(n=>n.id==='BAB_08_06');req(babylonExam?.campaignExamModules?.length===4,'Экзамен Вавилона: ожидалось 4 модуля');for(const mod of babylonExam?.campaignExamModules||[])req(quizzes[mod.id],`Экзамен Вавилона: нет квиза ${mod.id}`);req(babylon?.eraLayer?.regions?.length===6,'Карта бронзового века: ожидалось 6 регионов');req(babylon?.eraLayer?.parallelTimeline?.length>=8,'Хронология бронзового века: ожидалось не меньше 8 периодов');req(d.maps?.BABYLON_OLD==='data/maps/babylon.json','Manifest: нет карты Вавилона');req(d.maps?.BRONZE_WORLD==='data/maps/bronze-world.json','Manifest: нет глобальной карты бронзового века');

const egyptBronze=campaigns.find(c=>c.id==='EGYPT_MIDDLE_NEW');
req(egyptBronze?.chapters.length===10,'Египет Среднего и Нового царства: ожидалось 10 глав');
req(egyptBronze?.nodes.length===60,'Египет Среднего и Нового царства: ожидалось 60 миссий');
const egyptBronzeCards=cards.filter(c=>c.campaign==='EGYPT_BRONZE');
req(egyptBronzeCards.length===120,'Египет Среднего и Нового царства: ожидалось 120 карточек');
req(egyptBronzeCards.filter(c=>c.acquisition==='STORY').length===80,'Египет Среднего и Нового царства: ожидалось 80 сюжетных карточек');
req(egyptBronzeCards.filter(c=>c.acquisition==='ARCHIVE').length===40,'Египет Среднего и Нового царства: ожидалось 40 архивных карточек');
req(new Set(egyptBronzeCards.map(c=>c.summary)).size===egyptBronzeCards.length,'Египет Среднего и Нового царства: повторяются summary карточек');
req(new Set(egyptBronzeCards.map(c=>c.image?.local)).size===egyptBronzeCards.length,'Египет Среднего и Нового царства: повторяются изображения карточек');
const egyptBronzeParagraphs=new Map();
for(const m of egyptBronze?.nodes||[]){
 const l=lessons[m.id],words=(l?.theory?.paragraphs||[]).join(' ').split(/\s+/).filter(Boolean).length;
 req(words>=300,`${m.id}: теория Египта Среднего и Нового царства меньше 300 слов`);
 for(const paragraph of l?.theory?.paragraphs||[]){req(!egyptBronzeParagraphs.has(paragraph),`${m.id}: повтор теоретического абзаца из ${egyptBronzeParagraphs.get(paragraph)}`);egyptBronzeParagraphs.set(paragraph,m.id);}
}
for(const chapter of egyptBronze?.chapters||[]){
 const chapterWords=(egyptBronze.nodes.filter(m=>m.chapterId===chapter.id).flatMap(m=>lessons[m.id]?.theory?.paragraphs||[]).join(' ').split(/\s+/).filter(Boolean).length);
 req(chapterWords>=1000&&chapterWords<=2500,`${chapter.id}: теория главы ${chapterWords} слов, ожидалось 1000–2500`);
}
const egyptBronzePools=pools.pools.filter(p=>p.campaign==='EGYPT_BRONZE');
req(egyptBronzePools.length===10,'Египет Среднего и Нового царства: ожидалось 10 пулов');
req(egyptBronzePools.flatMap(p=>p.cardIds).length===40,'Египет Среднего и Нового царства: ожидалось 40 карт в архивных пулах');for(const c of egyptBronzeCards.filter(c=>c.acquisition==='ARCHIVE'))req(pools.acquisition[c.id]?.kind==='ARCHIVE',`${c.id}: архивная карточка должна иметь acquisition.kind ARCHIVE`);
const egyptBronzeStories=Object.values(stories).filter(s=>String(s.cardId||'').startsWith('EMN_'));
req(egyptBronzeStories.length===10,'Египет Среднего и Нового царства: ожидалось 10 личных историй');
const egyptBronzeQuizEntries=Object.entries(quizzes).filter(([id])=>id.startsWith('QUIZ_EMN_'));
const egyptBronzeQuestions=egyptBronzeQuizEntries.flatMap(([,q])=>q.questions||[]);
req(egyptBronzeQuizEntries.length===14,'Египет Среднего и Нового царства: ожидалось 14 квизов');
req(egyptBronzeQuestions.length===80,'Египет Среднего и Нового царства: ожидалось 80 вопросов');
req(new Set(egyptBronzeQuestions.map(q=>q.text)).size===egyptBronzeQuestions.length,'Египет Среднего и Нового царства: повторяются вопросы');
const egyptBronzeAnswerPositions=[0,0,0,0];
for(const q of egyptBronzeQuestions){req(q.options?.length===4,`Вопрос Египта «${q.text}»: ожидалось 4 варианта`);req(Number.isInteger(q.correct)&&q.correct>=0&&q.correct<4,`Вопрос Египта «${q.text}»: неверный correct`);if(Number.isInteger(q.correct)&&q.correct>=0&&q.correct<4)egyptBronzeAnswerPositions[q.correct]++;}
for(let i=0;i<4;i++)req(egyptBronzeAnswerPositions[i]>=15,`Квизы Египта: позиция ответа ${i} встречается только ${egyptBronzeAnswerPositions[i]} раз`);
const egyptBronzeExam=egyptBronze?.nodes.find(n=>n.id==='EMN_10_06');
req(egyptBronzeExam?.campaignExamModules?.length===4,'Экзамен Египта: ожидалось 4 модуля');
for(const mod of egyptBronzeExam?.campaignExamModules||[])req(quizzes[mod.id],`Экзамен Египта: нет квиза ${mod.id}`);
req(d.maps?.EGYPT_MIDDLE_NEW==='data/maps/egypt-middle-new.json','Manifest: нет карты Египта Среднего и Нового царства');
const egyptBronzeMap=await read(d.maps?.EGYPT_MIDDLE_NEW||'data/maps/egypt-middle-new.json');
req(Object.keys(egyptBronzeMap?.points||{}).length===28,'Карта Египта Среднего и Нового царства: ожидалось 28 точек');
const egyptBronzeCatalog=catalog.find(c=>c.id==='EGYPT_MIDDLE_NEW');
req(egyptBronzeCatalog?.status==='PLAYABLE','Каталог: кампания Египта должна быть PLAYABLE');
req(egyptBronzeCatalog?.releasedChapters===10,'Каталог: у Египта должно быть открыто 10 глав');
req(babylon?.eraLayer?.regions?.find(r=>r.id==='EGYPT_BRONZE')?.status==='PLAYABLE','Карта бронзового века: Египет должен быть PLAYABLE');
req(timeline.filter(t=>t.campaignId==='EGYPT_MIDDLE_NEW').length>=12,'Глобальная хронология: мало событий Египта Среднего и Нового царства');

const indexText=await fs.readFile(path.join(root,'index.html'),'utf8');const versionFiles=[['package.json',JSON.parse(await fs.readFile(path.join(root,'package.json'),'utf8')).version],['manifest.webmanifest',JSON.parse(await fs.readFile(path.join(root,'manifest.webmanifest'),'utf8')).name],['index.html',indexText],['js/bootstrap.js',await fs.readFile(path.join(root,'js/bootstrap.js'),'utf8')],['sw.js',await fs.readFile(path.join(root,'sw.js'),'utf8')],['README.md',await fs.readFile(path.join(root,'README.md'),'utf8')],['data/core/packs.json',(await read('data/core/packs.json')).version]];for(const [file,value] of versionFiles)req(String(value).includes(manifest.version),`${file}: версия не совпадает с ${manifest.version}`);req(indexText.includes(`js/bootstrap.js?v=${manifest.version}`),`index.html: устаревшая версия bootstrap cache-busting`);for(const script of manifest.scripts.filter(x=>/(?:v2-(?:5-egypt-learning|6-onboarding|7-parallel-civilizations|8-indus|9-china)|v3-(?:0-dawn-world|1-babylon|2-egypt-middle-new))\.js$/.test(x))){const text=await fs.readFile(path.join(root,script),'utf8');req(text.includes(`const V='${manifest.version}'`),`${script}: runtime-версия не совпадает с ${manifest.version}`);}
const refreshAllowed=new Set(['js/features/settings.js','js/features/v1-5-polish.js','js/features/v3-0-dawn-world.js']);for(const script of manifest.scripts){const text=await fs.readFile(path.join(root,script),'utf8');if(!refreshAllowed.has(script))req(!text.includes('forceRefresh()'),`${script}: принудительное обновление должно быть только в настройках`);}
const runtime=await fs.readFile(path.join(root,'js/core/runtime.js'),'utf8');req(runtime.includes("const STORE = 'codex_history_v02_ru'"),'Изменён ключ старых сохранений');req(runtime.includes('unlocked:[]'),'Runtime: новый профиль должен начинаться без карт');req(!runtime.includes('initial.unlocked.forEach'),'Runtime: стартовые карты снова добавляются принудительно');const hotfix=await fs.readFile(path.join(root,'js/features/v3-1-1-hotfix.js'),'utf8');req(manifest.scripts.at(-3)==='js/features/v3-1-1-hotfix.js','Hotfix должен загружаться перед визуальным модулем');req(manifest.scripts.at(-2)==='js/features/v3-1-3-visual-semantics.js','Визуальный модуль должен загружаться последним перед start.js');req(hotfix.includes('seedStarterCampaign'),'Hotfix: нет выбора стартовой кампании');req(hotfix.includes('resetProgress=function'),'Hotfix: нет финального сброса');
const imageManifest=await read('data/image_manifest.json');req(imageManifest.count===cards.length,`Image manifest: ${imageManifest.count} вместо ${cards.length}`);const historicalImages=cards.filter(c=>c.image?.prefer_remote);req(historicalImages.length===42,`Статические исторические изображения: ${historicalImages.length} вместо 42`);req(imageManifest.historicalImageCount===historicalImages.length,'Image manifest: неверный historicalImageCount');req(imageManifest.staticHistoricalImageCount===historicalImages.length,'Image manifest: неверный staticHistoricalImageCount');const imageQueries=await read(d.imageQueries);req(imageQueries.version===manifest.version,'Image queries: версия не совпадает');req(imageQueries.count===cards.length,`Image queries: ${imageQueries.count} вместо ${cards.length}`);req(Object.keys(imageQueries.cards||{}).length===cards.length,'Image queries: неполный каталог');for(const c of cards){const q=imageQueries.cards?.[c.id];req(!!q,`${c.id}: нет image query`);req((q?.candidates||[]).length>=2,`${c.id}: мало кандидатов изображения`);req((q?.candidates||[]).length<=6,`${c.id}: слишком много кандидатов изображения`);req(!!q?.semantic,`${c.id}: нет semantic profile`);req((q?.semantic?.group_terms||[]).length>=4,`${c.id}: нет исторического контекста image query`);req(Array.isArray(q?.semantic?.forbidden),`${c.id}: нет запрещённых контекстов`);req((q?.candidates||[]).some(x=>x.scope==='exact'),`${c.id}: нет точного кандидата`);req((q?.candidates||[]).some(x=>x.scope==='context'),`${c.id}: нет контекстного fallback`);for(const x of q?.candidates||[]){req(['ru','en'].includes(x.lang),`${c.id}: неверный язык image query`);req(['exact','context'].includes(x.scope),`${c.id}: неверный scope image query`);req(!!x.title,`${c.id}: пустой image query`);}}req(imageQueries.cards?.REG_MES_002?.candidates?.[0]?.title==='Тигр (река)','Тигр: первым должен быть речной контекст');req(imageQueries.cards?.CITY_LOW_005?.candidates?.[0]?.title==='Cosa','Коза: первым должна быть римская колония Cosa');req(imageQueries.cards?.EMN_S_04_02?.candidates?.[0]?.title==='Avaris','Аварис: первым должен быть точный исторический контекст');req(imageQueries.cards?.EMN_S_07_01?.candidates?.[0]?.title==='Hatshepsut','Хатшепсут: первым должен быть точный исторический контекст');req(imageQueries.cards?.EMN_S_10_03?.candidates?.[0]?.title==='Battle of Kadesh','Кадеш: первым должна быть историческая битва');req(imageManifest.dynamicQueryCount===cards.length-historicalImages.length,'Image manifest: неверный dynamicQueryCount');const visualModule=await fs.readFile(path.join(root,'js/features/v3-1-3-visual-semantics.js'),'utf8');for(const token of ['pageimages','extmetadata','semanticDecision','wrong-history-context','forbidden-context','MAX_CONTEXT_REUSE','refreshHistoricalImages','data-card-image'])req(visualModule.includes(token),`Visual module: нет ${token}`);

console.log(`Codex Validator v${manifest.version}`);console.log(`Карточки ${cards.length}; кампании ${campaigns.length}; миссии ${campaigns.reduce((n,c)=>n+c.nodes.length,0)}; уроки ${Object.keys(lessons).length}; пулы ${pools.pools.length}; редкость ${rarities.map(r=>rc[r]).join('/')}`);if(warnings.length)warnings.forEach(x=>console.log('WARN',x));if(errors.length){errors.forEach(x=>console.error('ERROR',x));process.exit(1);}console.log('✓ Контент валиден');
